"""Diagnosis-specific depth blocks for owner-facing cancer pages.

These are deliberately not generic filler. Histiocytic sarcoma is the quality bar:
each diagnosis gets practical waiting guidance and questions that reflect decisions
specific to that disease. Blocks may still be omitted by the renderer when empty.
"""

DOG_DEPTH = {
'lymphoma': {'waiting':'If lymphoma is confirmed but treatment has not started, avoid making an unplanned prednisone decision just to bridge a long wait unless your veterinarian feels it is medically necessary. Ask whether flow cytometry or other classification should be completed first, and check trials before first-line chemotherapy because treatment-naive status can matter.', 'questions':['Is this B-cell or T-cell lymphoma, and what anatomic form and grade are we dealing with?','Do we need flow cytometry, PARR, or another test before treatment starts?','Would prednisone or chemotherapy now close any trial or diagnostic options?']},
'mast cell tumor': {'waiting':'Use the wait to get the full pathology report, including grade, mitotic count and measured margins, and to decide whether the draining lymph node should be sampled. A high-grade, recurrent, large or node-positive mast cell tumor deserves faster oncology review than a small completely removed low-risk tumor.', 'questions':['What is the Kiupel grade, mitotic count and measured margin status?','Should the regional lymph node be sampled even if it feels normal?','Would KIT testing, radiation, or systemic treatment change the plan in this risk category?']},
'soft tissue sarcoma': {'waiting':'If the tumor is still present, avoid an unplanned narrow excision simply because an oncology appointment is delayed; the first surgery can determine whether durable local control is achievable. If it was already removed, obtain the grade and measured margins before deciding whether to watch, re-excise or use radiation or another local treatment.', 'questions':['What grade is the sarcoma and what are the measured surgical margins?','Is wider surgery still feasible, or is radiation or another local treatment more sensible?','Does this grade and site justify metastatic staging or systemic therapy?']},
'hemangiosarcoma': {'waiting':'Visceral hemangiosarcoma is different from many cancers because bleeding can become urgent. Collapse, pale gums, abdominal distension or breathing difficulty should not wait for a routine oncology visit. If surgery has already occurred, gather pathology, rupture/bleeding history and staging before the oncology discussion.', 'questions':['Was there rupture or internal bleeding, and what stage is the disease now?','Is there any evidence of cardiac involvement or distant metastasis?','What benefit is realistically expected from chemotherapy or a trial in this stage?']},
'osteosarcoma': {'waiting':'Pain and fracture risk come before preserving theoretical trial eligibility. Complete chest staging and local imaging promptly, and check trials before definitive local treatment only when doing so is medically safe. If amputation is not feasible, ask early about radiation or other local pain-control options.', 'questions':['Is this appendicular or axial disease, and is there visible metastasis?','What is the safest and most durable local-control option for pain and fracture risk?','Should a trial be considered before amputation, radiation or chemotherapy starts?']},
'oral melanoma': {'waiting':'Do not let a long wait delay staging of the mouth, regional lymph nodes and lungs. If the tumor is still measurable, trial eligibility may change after surgery or radiation, so checking options before local treatment can be useful when it does not delay necessary care.', 'questions':['What stage is this melanoma based on tumor size, nodes and lungs?','Should the regional lymph nodes be sampled even if they are not enlarged?','What local-control plan gives the best balance of margin, function and metastatic risk?']},
'melanoma': {'waiting':'First make sure the melanoma is being classified by site rather than treated as one disease. A low-risk cutaneous melanoma, digital melanoma and mucosal melanoma have different staging needs and urgency. Preserve pathology material if confirmation or further testing may be needed.', 'questions':['Where exactly did this melanoma originate, and how aggressive is that site expected to be?','Do we need regional-node or chest staging for this location?','Is local treatment alone reasonable, or is systemic treatment worth discussing?']},
'oral squamous cell carcinoma': {'waiting':'Local anatomy drives the next decision. Obtain biopsy confirmation and imaging of bone and deep tissue before a major oral surgery when possible. Worsening pain, bleeding, inability to eat or airway problems should accelerate evaluation rather than wait for a routine slot.', 'questions':['How much bone or deep tissue is involved, and is complete surgery realistic?','Do the regional lymph nodes need sampling?','If surgery cannot achieve useful margins, what local treatment gives the best chance of control or comfort?']},
'squamous cell carcinoma': {'waiting':'Use the waiting period to establish the exact primary site and local extent because SCC behavior varies sharply by location. A small cutaneous lesion should not trigger the same plan as oral, nasal or deeply invasive disease.', 'questions':['What is the exact primary site and subtype of this SCC?','Is this mainly a local-control problem, or is metastatic staging important here?','If margins are incomplete, is more local treatment recommended now rather than waiting for regrowth?']},
'urothelial carcinoma': {'waiting':'Protect urine flow first. Increasing straining, a weak stream or inability to urinate can become urgent. While waiting, clarify whether the tumor involves the trigone, urethra or prostate, whether obstruction is developing, and whether a BRAF test or tissue confirmation is still needed.', 'questions':['Where exactly is the tumor and is urine flow at risk?','Do we have enough evidence for diagnosis, or is tissue still required?','Which medical, radiation or interventional options are realistic if obstruction worsens?']},
'hepatocellular carcinoma': {'waiting':'The most important question is whether this is a solitary resectable liver mass or multifocal/diffuse disease. High-quality imaging and surgical review are usually more useful than treating all liver tumors as one category.', 'questions':['Is this a solitary massive HCC, or is disease multifocal or diffuse?','Is the mass resectable given its vessels and location?','If surgery is not feasible, what exactly makes it unresectable and what alternatives follow from that?']},
'mammary carcinoma': {'waiting':'Record every mammary nodule and its size, assess regional lymph nodes and complete chest staging when indicated. If surgery is planned, the extent should be decided intentionally rather than removing only the most obvious lump and sorting out stage later.', 'questions':['What are the tumor size, grade, lymphovascular-invasion and node findings?','What extent of surgery is appropriate for this pattern of disease?','Does this pathology justify systemic treatment or closer metastatic surveillance?']},
'thyroid carcinoma': {'waiting':'Clarify whether the thyroid mass is mobile or fixed and whether major vessels or surrounding structures are involved. That distinction often matters more than simply knowing that the mass is thyroid in origin.', 'questions':['Is the mass mobile and surgically removable, or fixed/invasive?','Is there vascular invasion or metastatic disease?','Would radioactive iodine, radiation or systemic treatment be preferable to surgery in this anatomy?']},
'prostate cancer': {'waiting':'Urinary obstruction and pain can become the immediate problem. While waiting for oncology, monitor urine flow closely and ask whether local imaging, renal values or an interventional procedure is needed before systemic treatment decisions.', 'questions':['Is urine flow threatened, and do we need an intervention before cancer treatment?','Where has the disease spread, including nodes, lungs or bone?','What local and systemic treatments are realistic for this extent of disease?']},
'primary lung tumor': {'waiting':'Confirm that a lung mass is likely primary rather than metastatic from another cancer. For a solitary lesion, CT and surgical assessment can determine resectability and lymph-node involvement before the window for surgery closes.', 'questions':['Does this look like a primary lung tumor or metastasis from another site?','Is the lesion surgically resectable and are intrathoracic nodes suspicious?','If surgery is done, will lymph nodes be sampled and how will pathology affect follow-up treatment?']},
'glioma': {'waiting':'Control seizures and brain swelling first. MRI review should establish whether the lesion is consistent with glioma and whether biopsy, surgery, radiation or a trial is realistically available. A neurologically worsening dog should not wait simply to preserve a research option.', 'questions':['How confident are we that this is glioma based on MRI, and would biopsy change management?','What are the roles of radiation, surgery and medical symptom control for this location?','Could steroids, anticonvulsants or prior local treatment affect trial eligibility?']},
'meningioma': {'waiting':'Neurologic stability matters more than waiting for a preferred appointment. Keep seizures and other symptoms controlled, obtain a good MRI review, and compare surgery with radiation based on location rather than assuming one is automatically superior.', 'questions':['Is this tumor surgically accessible, and what morbidity would surgery carry?','Would radiation offer comparable control for this location?','Do we need tissue confirmation, and would the answer change treatment or trial access?']},
'nasal tumor': {'waiting':'Biopsy and CT should usually come before committing to a cancer-specific treatment because different nasal cancers can look similar. Worsening bleeding, airflow obstruction or neurologic signs can make local treatment more urgent.', 'questions':['What does biopsy show, and how far does CT show the tumor extending?','Is the cribriform plate involved and do lymph nodes need assessment?','Is radiation the main local treatment, and what options remain if the tumor recurs?']},
'leukemia': {'waiting':'Acute and chronic leukemia have very different urgency. Severe anemia, bleeding, fever, infection risk or weakness can require immediate supportive care while lineage and subtype are being established.', 'questions':['Is this acute or chronic, and lymphoid or myeloid?','Do we need flow cytometry or bone-marrow sampling to classify it?','What blood-count changes would require urgent supportive care or treatment modification?']},
'multiple myeloma': {'waiting':'Do not focus only on the cancer label. Kidney injury, hypercalcemia, anemia, hyperviscosity and painful bone lesions can require treatment promptly while the full myeloma workup is being completed.', 'questions':['Which myeloma complications are present right now?','What marker will we follow to know whether treatment is working?','Are there focal bone lesions that need radiation or another local intervention?']},
'chemodectoma': {'waiting':'A heart-base mass does not always require immediate tumor treatment, but pericardial fluid, compression, arrhythmia or progressive symptoms can change urgency. Serial imaging can help distinguish a stable incidental mass from clinically important progression.', 'questions':['Is the mass causing pericardial fluid, compression or arrhythmia?','Is it clearly growing, and do we need tissue confirmation?','Would radiation, targeted therapy or observation best fit the current pace and symptoms?']},
'histiocytic sarcoma': {'waiting':'Waiting does not mean there is nothing to do. Ask about a cancellation list or another oncology center if the appointment is far away. Complete recommended staging if your veterinary team can arrange it, and check clinical trials before the next treatment decision. Some trials require a tumor to remain measurable or exclude certain previous chemotherapy or radiation.', 'questions':['Is this localized HS or is there evidence that it has spread?','Is the staging complete enough for the next decision?','If surgery was done, are margins adequate and does the site need more local treatment?','Do you recommend systemic treatment now, and what are the realistic options?','Could treatment we start now affect trial eligibility later?']},
}

CAT_DEPTH = {
'lymphoma': {'waiting':'Before starting treatment, clarify whether this is low-grade intestinal, high-grade gastrointestinal, nasal, mediastinal, renal or another form. Prednisolone can be appropriate in feline lymphoma, but when the diagnosis or trial eligibility is still uncertain, ask whether sampling or classification should happen first.', 'questions':['What anatomic form and grade of lymphoma does my cat have?','Do we need biopsy, immunophenotyping or another test before treatment?','Is this a form where oral therapy is reasonable, or is multi-agent chemotherapy or radiation more appropriate?']},
'mast cell tumor': {'waiting':'Do not apply canine mast-cell grading rules automatically. Establish whether this is a solitary skin tumor, splenic disease, intestinal disease or disseminated mast-cell disease, because those forms lead to very different decisions.', 'questions':['Is this cutaneous, splenic, intestinal or disseminated mast-cell disease?','Is surgery or splenectomy likely to be definitive for this form?','What evidence supports systemic treatment in this specific feline presentation?']},
'soft tissue sarcoma': {'waiting':'For a suspected injection-site sarcoma, avoid a narrow unplanned excision simply to remove the lump quickly. Imaging and deliberate surgical planning before the first definitive surgery can materially affect local control.', 'questions':['Is this consistent with injection-site sarcoma or another soft tissue sarcoma?','What surgical margins are realistically achievable on the first definitive operation?','Should radiation be planned before or after surgery for this location?']},
'hemangiosarcoma': {'waiting':'If disease is visceral, monitor urgently for bleeding, weakness or collapse. If it is cutaneous or subcutaneous, prognosis and treatment may be very different, so establish the anatomic form before borrowing expectations from canine visceral disease.', 'questions':['Is this superficial or visceral hemangiosarcoma?','Is there active bleeding or disease elsewhere?','What feline evidence supports any systemic treatment being proposed?']},
'osteosarcoma': {'waiting':'Pain control and fracture risk still come first, but feline osteosarcoma should not be managed from canine assumptions alone. Determine whether the tumor is appendicular or axial and complete appropriate staging before deciding how much systemic therapy adds.', 'questions':['Is this appendicular or axial osteosarcoma and is metastasis visible?','Is amputation or another local treatment feasible?','What feline evidence supports chemotherapy in this particular case?']},
'oral melanoma': {'waiting':'Because feline oral melanoma is rare, diagnostic confirmation matters. Ask whether immunohistochemistry is needed for an amelanotic lesion, and stage nodes and lungs before assuming canine melanoma pathways apply.', 'questions':['How secure is the diagnosis and was immunohistochemistry needed?','What is the local extent and metastatic stage?','Which proposed treatments are supported by feline data versus extrapolated from dogs?']},
'melanoma': {'waiting':'First identify whether the tumor is ocular, oral, cutaneous or another melanocytic tumor. Site drives both treatment and prognosis, and canine melanoma vaccine or survival data should not be treated as feline evidence.', 'questions':['Where did the melanoma originate and what behavior is expected at that site in cats?','Is local surgery the main treatment, and what staging is appropriate?','Which systemic or immune options have actual feline evidence?']},
'oral squamous cell carcinoma': {'waiting':'Pain, eating and local progression can become urgent in feline oral SCC. Obtain biopsy and local imaging quickly enough to decide whether meaningful surgery is possible; nutritional support should be planned early rather than after major weight loss.', 'questions':['How much jaw, tongue or deep tissue is involved?','Is complete surgery realistically possible with acceptable function?','What is the plan for pain control and nutrition if local control is limited?']},
'squamous cell carcinoma': {'waiting':'Separate sun-associated cutaneous SCC from oral disease. Small nasal-planum, pinna or eyelid lesions can be excellent local-treatment candidates, while oral SCC follows a much more aggressive pathway.', 'questions':['What is the exact site and depth of this SCC?','Which local treatment best preserves function at this site?','Is this a case where electrochemotherapy, radiation, cryotherapy or surgery is most appropriate?']},
'urothelial carcinoma': {'waiting':'Urine flow and kidney function are immediate priorities. Because feline evidence is sparse, make sure treatment choices are based on feline safety rather than a direct copy of canine bladder-cancer protocols.', 'questions':['Is urine flow threatened and where exactly is the tumor located?','How certain is the diagnosis and is tissue required?','Which proposed drugs or procedures have feline safety and outcome data?']},
'hepatocellular carcinoma': {'waiting':'Clarify whether this is a solitary resectable liver mass or multifocal/diffuse disease. Surgical anatomy is central, and favorable outcomes from solitary resectable tumors should not be generalized to diffuse liver cancer.', 'questions':['Is this a solitary resectable HCC?','What major vessels or liver structures limit surgery?','If surgery is not feasible, what evidence supports the proposed alternative in cats?']},
'mammary carcinoma': {'waiting':'Feline mammary carcinoma is often aggressive, so stage before assuming surgery alone is enough. Record tumor size and multiplicity, assess regional nodes and lungs, and plan the extent of surgery intentionally.', 'questions':['What are the tumor size, grade, lymphovascular invasion and node status?','What extent of mammary surgery is recommended for this pattern?','Does this risk profile justify chemotherapy or closer metastatic monitoring?']},
'thyroid carcinoma': {'waiting':'Most feline hyperthyroidism is not carcinoma, so first confirm that this is truly a malignant thyroid tumor and assess fixation, invasion and metastasis before choosing a cancer treatment pathway.', 'questions':['What evidence supports thyroid carcinoma rather than benign hyperthyroid disease?','Is the mass localized and removable or invasive/fixed?','Would radioactive iodine, surgery or radiation be most appropriate if the tumor is iodine-avid or invasive?']},
'prostate cancer': {'waiting':'Feline prostate cancer is exceptionally rare, so obstruction and diagnosis deserve priority over importing a standard canine pathway. Difficulty urinating or defecating may require intervention before oncology treatment.', 'questions':['How secure is the diagnosis and what structures are obstructed or invaded?','Is there evidence of nodal, lung or bone spread?','Which treatment options are supported by feline experience versus extrapolated from dogs?']},
'primary lung tumor': {'waiting':'For a solitary lung mass, determine whether it is likely primary and resectable. Nodal or pleural disease can change the value of surgery, so CT and surgical staging are often more informative than waiting without further workup.', 'questions':['Does this look like a primary lung tumor or metastasis?','Is it resectable and are thoracic nodes or pleura involved?','How will pathology and node status change the need for additional treatment?']},
'glioma': {'waiting':'Control seizures or brain swelling first, then use MRI to frame the diagnosis and local-treatment options. Feline glioma data are sparse, so canine survival figures should not be used as though they predict a cat.', 'questions':['How confident is the MRI diagnosis and would biopsy change treatment?','Is radiation, surgery or medical management realistic for this location?','Which outcome estimates are actually feline rather than canine?']},
'meningioma': {'waiting':'Many feline meningiomas are surgically approachable, so obtain a surgical-neurology opinion rather than assuming radiation is the only local option. Worsening seizures or neurologic deficits should accelerate assessment.', 'questions':['Is this meningioma surgically accessible and what morbidity is expected?','If surgery is incomplete or not feasible, what control can radiation provide?','Do we need tissue confirmation before choosing treatment?']},
'nasal tumor': {'waiting':'Biopsy matters because feline nasal lymphoma and carcinoma may look similar clinically but require very different treatment. CT should define local extent before a definitive local-treatment plan is chosen.', 'questions':['What histology does biopsy show?','How extensive is disease on CT and is the cribriform plate involved?','If this is lymphoma versus carcinoma, how does the treatment plan change?']},
'leukemia': {'waiting':'Distinguish leukemia from FeLV infection and distinguish acute from chronic disease. Severe cytopenias, fever, bleeding or weakness can require immediate supportive care while the exact lineage is being established.', 'questions':['Is this acute or chronic leukemia, and what lineage is involved?','What role does FeLV status play in this case?','Do we need bone marrow or flow cytometry, and what blood-count changes need urgent treatment?']},
'multiple myeloma': {'waiting':'Assess kidney function, calcium, anemia, blood proteins and painful bone disease while confirming the diagnosis. In cats, the disease is uncommon enough that diagnosis should rest on the full pattern rather than one abnormal protein value.', 'questions':['Which diagnostic criteria for myeloma are met in this cat?','Are kidney injury, hypercalcemia or bone lesions present now?','What marker will we follow to judge response to systemic treatment?']},
'chemodectoma': {'waiting':'Because feline chemodectoma is extremely rare, focus on what the mass is doing: pericardial or pleural fluid, compression, arrhythmia and documented growth. Canine outcome data should be labeled as extrapolation, not feline evidence.', 'questions':['Is the mass causing fluid, compression or arrhythmia?','How certain is the diagnosis without tissue?','Which treatment recommendations are based on feline evidence and which are extrapolated from dogs?']},
'histiocytic sarcoma': {'waiting':'Confirm the diagnosis carefully because feline HS is rare and immunohistochemistry may be important. Complete staging promptly enough to distinguish localized from disseminated disease, but avoid presenting canine survival figures or CCNU expectations as established feline evidence.', 'questions':['Is this truly localized HS or is disease present elsewhere?','Was the diagnosis supported by appropriate immunohistochemistry?','If local control is possible, what are the margin or radiation options?','What systemic options have any feline evidence, and which are extrapolated from dogs?']},
}
