"""Additional baseline decision branches needed for HS-level owner guidance."""

DOG_BASELINE_BRANCHES = {
    'lymphoma': [('Lymphoma is confirmed and treatment has not started', 'This is the best time to make sure the diagnosis is classified well enough for the treatment decision. Ask whether immunophenotyping or other testing should be completed before prednisone or chemotherapy, and check trials that require untreated disease.')],
    'mast cell tumor': [('The tumor is still present', 'Before the first definitive surgery, review tumor size and location and whether the draining lymph node should be sampled. For a difficult site or a higher-risk tumor, planned surgery or another local approach is usually better than a narrow unplanned excision.')],
    'soft tissue sarcoma': [('The mass is still present', 'The first definitive local treatment matters. Ask whether biopsy or imaging would change the surgical plan and whether wide margins are realistically achievable before the tumor is removed.')],
    'oral melanoma': [('The oral tumor is still present', 'Stage the primary tumor, regional lymph nodes and lungs while planning local control. If a trial requires measurable disease, check it before surgery or radiation when doing so will not delay necessary treatment.')],
    'oral squamous cell carcinoma': [('The tumor is still present and surgery is being considered', 'Define local extent and bone involvement before a major oral surgery. The useful question is whether complete removal is realistic with acceptable function, not simply whether the visible mass can be cut out.')],
    'urothelial carcinoma': [('Urination is still normal', 'This is the time to establish tumor location, stage and a plan for monitoring urine flow before obstruction becomes an emergency. Medical treatment is commonly used even when the dog is still urinating normally.')],
    'hepatocellular carcinoma': [('There is one apparently resectable liver mass', 'Ask for surgical review of the mass in relation to major vessels and central liver structures. A solitary resectable massive HCC can have a very different outlook from multifocal or diffuse liver cancer.')],
    'mammary carcinoma': [('The mammary tumor is still present', 'Record the number and size of mammary tumors, assess the appropriate regional lymph nodes and decide the intended extent of surgery before operating. Staging first can prevent making the local plan in isolation.')],
    'thyroid carcinoma': [('The thyroid mass is mobile and appears resectable', 'A freely movable thyroid mass can be a good surgical problem in selected dogs. Confirm local anatomy and metastatic stage before assuming that a fixed or invasive-tumor treatment pathway is needed.')],
    'primary lung tumor': [('There is one apparently resectable lung mass', 'Confirm that the lesion is likely a primary lung tumor rather than metastasis and use imaging to assess resectability and intrathoracic lymph nodes before surgery.')],
    'osteosarcoma': [('The primary bone tumor is still present', 'Pain control and fracture risk come first while staging and local-treatment decisions are made. If surgery is planned, check trials before definitive treatment only when that can be done without compromising comfort or safety.')],
}

CAT_BASELINE_BRANCHES = {
    'histiocytic sarcoma': [('The lesion is still present and appears localized', 'If the lesion is removable, ask whether surgery can achieve useful margins and whether staging shows disease elsewhere. Because feline HS evidence is sparse, preserving tissue for diagnostic confirmation can be especially valuable.')],
    'oral squamous cell carcinoma': [('The oral tumor is still present and surgery is being considered', 'Define jaw, tongue and deep-tissue involvement before major surgery. The key question is whether complete removal is realistically possible with acceptable function, while pain and nutritional support are addressed at the same time.')],
    'urothelial carcinoma': [('Urination is still reasonably normal', 'Use this window to define tumor location, kidney function and risk of future obstruction before urine flow becomes an emergency. Because feline evidence is limited, treatment choices should be checked for feline safety rather than copied directly from canine protocols.')],
    'hepatocellular carcinoma': [('There is one apparently resectable liver mass', 'Ask for surgical review of the mass and its relationship to major vessels. A solitary resectable tumor should not be grouped with multifocal or diffuse liver cancer when discussing prognosis or treatment.')],
    'mammary carcinoma': [('The mammary tumor is still present', 'Record tumor size and multiplicity, assess regional nodes and lungs as appropriate, and decide the intended extent of surgery before operating rather than treating only the most obvious nodule.')],
    'primary lung tumor': [('There is one apparently resectable lung mass', 'Confirm that it is likely a primary lung tumor and use imaging to assess resectability, lymph nodes and pleural disease before deciding on lobectomy.')],
}
