"""Owner-facing cancer education copy used on every English diagnosis page.

No survival-time estimates are included here by design: prognosis is too dependent
on subtype, grade, stage, site, treatment and the individual patient to present as
a single owner-facing number on a diagnosis landing page.
"""

CONTENT = {
'histiocytic sarcoma': (
    'Histiocytic sarcoma is a cancer of histiocytic immune cells. In dogs it can begin as one localized tumor or involve several organs. It often behaves aggressively, so finding out where the disease is present is an important part of planning treatment. Chest and abdominal imaging are commonly used for staging, with other tests chosen according to the tumor location.',
    'If the disease is localized and the tumor can be removed, surgery is usually considered for local control. Radiation may be used when surgery cannot fully control the tumor. Because this cancer has a meaningful risk of microscopic or distant spread, systemic chemotherapy is often discussed; lomustine (CCNU) is one of the drugs commonly used in dogs. Clinical trials may offer additional systemic or targeted approaches.',
    'Treatment choices are strongly affected by whether disease is localized or disseminated, the primary site, surgical margins, measurable disease, metastasis, previous treatment and the dog’s overall health.'),
'lymphoma': (
    'Lymphoma is a cancer of lymphocytes, a type of immune cell. It can involve lymph nodes, blood, spleen, liver, gastrointestinal tract, skin or other organs. Lymphoma is not one single disease: its behavior and treatment can differ substantially by location, grade and whether the cells are B-cell or T-cell.',
    'For most dogs with high-grade multicentric lymphoma, systemic multi-drug chemotherapy such as a CHOP-based protocol is a common first-line treatment. Other chemotherapy drugs and newer targeted treatments may be used in selected cases or after relapse. Cats are treated according to the form and location of lymphoma; some low-grade gastrointestinal lymphomas can be managed with oral medication, while high-grade disease usually needs more intensive chemotherapy. Radiation or surgery has a role in selected localized forms.',
    'Important treatment factors include B-cell versus T-cell type, grade, anatomic form, stage, previous chemotherapy, response or relapse history, organ involvement and the pet’s general health.'),
'mast cell tumor': (
    'Mast cell tumors arise from mast cells, which normally take part in allergic and inflammatory responses. Some remain local and are readily controlled, while others are biologically aggressive and can spread. Pathology grade, tumor location and evidence of spread are especially important in understanding an individual tumor.',
    'Surgery is usually the main treatment for a removable localized skin mast cell tumor. Radiation can help control disease left behind when another surgery is not practical. For higher-risk, unresectable, recurrent or metastatic tumors, systemic treatment may include chemotherapy or targeted tyrosine-kinase inhibitors. Intratumoral treatment is also an option for some appropriately located canine mast cell tumors.',
    'Treatment choices depend on grade, size and location, surgical margins, lymph-node or distant spread, recurrence, KIT-related tumor biology when tested, and previous treatment.'),
'soft tissue sarcoma': (
    'Soft tissue sarcoma is a group of cancers that arise from connective and supporting tissues such as muscle, fibrous tissue, nerves and blood-vessel-associated tissues. These tumors often grow into nearby tissue rather than staying neatly separated from it. Their risk of spreading elsewhere varies considerably with subtype and grade.',
    'For a removable tumor, wide surgical excision is usually the main local treatment. If margins are incomplete or narrow and another surgery is not practical, radiation can be considered to improve local control. Chemotherapy is more often discussed for high-grade, metastatic or otherwise high-risk tumors. Some centers also offer investigational local treatments, immunotherapy or other trial options.',
    'The most useful details for treatment planning are the exact subtype when known, grade, tumor size and location, whether clean surgical margins are achievable, margin status after surgery, measurable residual disease and evidence of metastasis.'),
'hemangiosarcoma': (
    'Hemangiosarcoma is a malignant cancer associated with blood-vessel-forming cells. In dogs it commonly arises in the spleen, heart or liver, although it can occur in other sites. Internal tumors can rupture and bleed, and microscopic spread may already be present even when imaging does not show visible metastases. Skin forms can behave differently from internal disease.',
    'When an internal primary tumor can be safely removed, surgery is used for local control and definitive diagnosis. Because systemic spread is a major concern, chemotherapy, commonly doxorubicin-based in dogs, is often discussed after surgery. Treatment for cutaneous disease depends on how deeply the tumor extends. Clinical trials may investigate new systemic, immune or targeted approaches.',
    'Treatment planning depends heavily on the primary site, whether rupture or bleeding has occurred, pathology, stage, visible metastasis, whether the primary tumor can be removed and the patient’s cardiovascular and overall condition.'),
'osteosarcoma': (
    'Osteosarcoma is the most common primary bone cancer in dogs. It damages normal bone, causing pain and increasing the risk of fracture. Even when the primary tumor appears localized, microscopic metastatic disease is a major concern, most commonly involving the lungs.',
    'For osteosarcoma of a limb, amputation or limb-sparing surgery can provide local control and pain relief. Systemic chemotherapy, commonly a platinum-based drug such as carboplatin, is usually discussed because of metastatic risk. When surgery is not appropriate, stereotactic or palliative radiation and other pain-control strategies can be used. Several immunotherapy and other investigational approaches are also being studied.',
    'Key factors include tumor location, whether the bone can be surgically treated, visible lung or other metastases, pathologic fracture, pain and mobility, previous therapy and the dog’s ability to tolerate local and systemic treatment.'),
'oral melanoma': (
    'Oral melanoma is a cancer arising from melanocytes in the mouth. In dogs it can invade nearby tissues and has a significant risk of spreading to regional lymph nodes and the lungs. Tumor size, exact location and stage matter greatly when deciding what can be controlled locally and whether systemic treatment should also be considered.',
    'Surgery is preferred when the tumor can be removed while preserving acceptable function. Radiation is commonly used when complete surgery is not possible or as another form of local control. Because metastatic risk can be substantial, systemic and immunotherapeutic approaches may also be discussed, including clinical trials when appropriate.',
    'Treatment choices depend on tumor size and oral location, lymph-node involvement, lung or other metastases, surgical feasibility and margins, previous local treatment and measurable disease.'),
'melanoma': (
    'Melanoma arises from pigment-producing melanocytes, but its behavior varies greatly by location. Some skin melanomas are relatively low risk, while oral, nail-bed and other mucosal melanomas can be much more aggressive and more likely to spread.',
    'Complete surgical removal is preferred for a localized tumor when feasible. Radiation can be used when surgery is incomplete or impractical. For biologically aggressive, recurrent or metastatic melanoma, systemic or immunotherapeutic approaches may be considered. The best plan depends on where the melanoma began rather than on the word melanoma alone.',
    'The primary site, pathology, tumor size, surgical margins, lymph-node status, distant metastasis, recurrence and previous treatment are major factors in choosing therapy.'),
'oral squamous cell carcinoma': (
    'Oral squamous cell carcinoma is a locally invasive cancer arising from the lining of the mouth. It can involve the jaw, tongue or surrounding tissues. In cats it is often especially difficult to control locally because many tumors are advanced by the time they are diagnosed.',
    'Surgery offers the best local control when complete removal is anatomically possible. Radiation, including definitive or palliative treatment, may be considered for tumors that cannot be fully removed. Systemic treatments have more limited and variable roles, which is one reason new local, targeted and immune approaches are actively studied.',
    'Treatment choices depend on species, exact oral location, tumor size, bone involvement, lymph-node or distant spread, surgical feasibility, pain and eating function, and previous treatment.'),
'squamous cell carcinoma': (
    'Squamous cell carcinoma is a cancer of squamous epithelial cells. It can arise in the skin, mouth, nasal tissues and other sites, and its behavior differs substantially depending on where it starts. A skin lesion and an oral or nasal tumor therefore should not be treated as the same disease.',
    'Local treatment may include surgery, radiation or other site-specific therapies. Systemic treatment can be considered for selected advanced or metastatic cases. Because the disease behaves differently by location, treatment recommendations should be based on the specific primary site and stage.',
    'The primary site, tumor size and depth, pathology, surgical margins, local invasion, lymph-node or distant spread and previous treatment are the main factors guiding therapy.'),
'urothelial carcinoma': (
    'Urothelial carcinoma, historically called transitional cell carcinoma, most often affects the urinary bladder or urethra. Its location can make complete surgical removal difficult, and progression can interfere with normal urine flow. It may also spread to lymph nodes or distant organs.',
    'Medical treatment is common and often includes an NSAID together with chemotherapy in dogs. Radiation, surgery or interventional procedures can be useful in selected cases, particularly when local disease or urinary obstruction needs to be addressed. Clinical trials may offer additional drug or targeted-treatment options.',
    'Treatment choices depend on the exact bladder or urethral location, ability to urinate normally, local invasion, lymph-node or distant metastasis, kidney function, previous drugs and whether measurable disease is present.'),
'hepatocellular carcinoma': (
    'Hepatocellular carcinoma is a primary cancer of liver cells. In dogs, a single large liver mass can behave very differently from multifocal or diffuse disease. Imaging is important for determining how much of the liver is involved and whether the tumor appears surgically removable.',
    'Surgery is generally preferred for a resectable solitary liver mass and can provide strong local control. Multifocal, diffuse, unresectable or metastatic disease requires a different plan and may lead to discussion of systemic, local interventional or investigational treatments.',
    'The number and location of liver lesions, involvement of major vessels, surgical resectability, liver function, pathology and evidence of metastasis are central to treatment planning.'),
'mammary carcinoma': (
    'Mammary carcinoma is a malignant tumor of mammary tissue. Its behavior varies with species, tumor size, pathology and stage. Feline mammary carcinomas are often biologically aggressive, while canine mammary tumors span a broader range of behavior.',
    'Surgery is the main treatment for localized mammary carcinoma. The recommended extent of surgery differs between dogs and cats and according to how many glands are involved. Chemotherapy may be considered for higher-risk tumors, lymph-node involvement or metastatic disease, particularly when pathology suggests aggressive behavior.',
    'Species, tumor size and number, histologic type and grade, surgical margins, lymph-node involvement, distant metastasis and hormone-receptor information when available can affect treatment choices.'),
'thyroid carcinoma': (
    'Thyroid carcinoma usually appears as a neck mass and can range from a movable, surgically approachable tumor to an invasive mass attached to surrounding structures. Some tumors produce thyroid hormone, while others do not, and metastatic risk varies.',
    'Surgery is preferred for a resectable mobile thyroid tumor. Radiation is an important option for invasive, incompletely removed or non-surgical disease. Radioactive iodine can be appropriate for selected iodine-avid tumors, and systemic or targeted therapy may be considered for progressive or metastatic disease.',
    'Mobility and invasiveness of the mass, vascular involvement, thyroid function, iodine avidity when evaluated, surgical margins and metastatic stage help determine the treatment plan.'),
'prostate cancer': (
    'Prostatic carcinoma is an aggressive cancer in dogs that can invade the urinary tract and spread to lymph nodes, lungs or bone. Because of the prostate’s location and the biology of the disease, complete surgical removal is often difficult.',
    'Treatment is commonly multimodal and may include NSAIDs, chemotherapy and radiation. Procedures to maintain urine flow can be important when obstruction develops. Surgery is reserved for selected cases, and clinical trials may provide additional systemic or local options.',
    'Urinary function, local extent, lymph-node, lung or bone metastasis, pain, previous treatment and whether the disease can be safely targeted with local therapy all influence treatment decisions.'),
'primary lung tumor': (
    'A primary lung tumor begins in lung tissue and is different from cancer that has spread to the lungs from another site. A single pulmonary mass can have very different treatment options from multiple lung nodules or widespread metastatic disease.',
    'Surgical removal of the affected lung lobe is the usual local treatment for a solitary resectable primary lung tumor when staging does not show prohibitive spread. Chemotherapy or other systemic treatment may be discussed for higher-risk pathology, lymph-node involvement, unresectable disease or metastasis.',
    'The number and location of lung lesions, lymph-node status, pathology, surgical resectability, respiratory function and evidence of disease elsewhere are important treatment factors.'),
'glioma': (
    'Gliomas are primary brain tumors arising from glial cells. Depending on their location, they can cause seizures, behavior changes, weakness, balance problems or other neurologic signs. MRI can strongly suggest a glioma, but a definitive tissue diagnosis may require biopsy or surgery.',
    'Radiation therapy, including stereotactic radiation at specialty centers, is a common local treatment. Surgery may be possible for selected accessible tumors. Medications are used to control problems such as seizures and brain swelling but do not by themselves treat the tumor. Clinical trials are actively studying local drug delivery, chemotherapy, immune therapy and other approaches.',
    'Tumor location and size, MRI appearance, whether biopsy is feasible or required, neurologic status, previous radiation or chemotherapy and the ability to undergo anesthesia are important when considering treatment or a trial.'),
'meningioma': (
    'Meningioma arises from the membranes surrounding the brain or spinal cord. Many grow relatively slowly, but even a slow-growing tumor can cause major neurologic problems by compressing nearby nervous tissue. Location and surgical accessibility are therefore especially important.',
    'Surgical removal is often considered for accessible intracranial meningiomas, particularly in cats. Radiation can be used when surgery is incomplete, not feasible or not chosen, and can also be used for recurrence. Medications may control seizures, inflammation or other neurologic symptoms alongside tumor-directed treatment.',
    'Species, tumor location and size, surgical accessibility, neurologic condition, imaging characteristics, previous treatment and anesthesia risk all influence the treatment plan.'),
'nasal tumor': (
    'Nasal tumors arise within the nasal cavity or sinuses and are usually more threatening because of local invasion than early distant spread. Common signs include persistent nasal discharge, nosebleeds, noisy breathing or facial changes. The exact tumor type still matters because several cancers can occur in this location.',
    'Radiation therapy is the main definitive local treatment for many canine and feline nasal cancers because complete surgery is rarely practical. Both conventionally fractionated and stereotactic radiation are used. Chemotherapy or targeted treatment may be added for selected tumor types or more advanced disease.',
    'Pathology, extent within the nasal cavity and surrounding structures, lymph-node or distant spread, previous radiation, breathing symptoms and the specific tumor type guide treatment choices.'),
'leukemia': (
    'Leukemia is a cancer of blood-forming cells. Acute and chronic leukemias are biologically different diseases, and identifying the cell type is essential because treatment intensity and expected response can differ greatly.',
    'Acute leukemias generally require systemic multi-drug chemotherapy and substantial supportive care. Some chronic leukemias can be managed for longer periods with oral chemotherapy or targeted drugs. The exact protocol depends on whether the leukemia is lymphoid or myeloid, acute or chronic, and on the patient’s blood counts and clinical condition.',
    'Acute versus chronic disease, lymphoid versus myeloid origin, blood and bone-marrow findings, cytopenias, organ involvement, previous therapy and overall clinical stability are key treatment factors.'),
'multiple myeloma': (
    'Multiple myeloma is a cancer of plasma cells that usually affects the body systemically rather than as a single isolated tumor. It can involve bone marrow and bones and can cause abnormal blood proteins, kidney problems or other organ effects.',
    'Systemic drug therapy is the main treatment. Melphalan with a corticosteroid has long been a commonly used canine protocol, with other chemotherapy or targeted agents considered when appropriate. Radiation can be useful for painful focal bone lesions or other sites needing local control.',
    'Blood-protein abnormalities, bone-marrow involvement, kidney function, calcium level, bone lesions, blood counts, response to previous therapy and the pet’s general condition influence treatment.'),
'chemodectoma': (
    'Chemodectoma, also called an aortic body tumor, usually develops at the base of the heart. Some grow slowly, while others cause problems by compressing nearby structures, producing fluid around the heart or spreading elsewhere.',
    'Because of the location, surgery can be difficult or impossible for many heart-base tumors. Radiation, including stereotactic approaches, may provide local control in selected patients. Medical or targeted therapy can also be considered, and procedures may be needed to manage recurrent pericardial fluid.',
    'Tumor size and growth, compression of cardiac structures, pericardial effusion, metastasis, cardiac function, surgical feasibility and previous treatment determine which options are reasonable.'),
}
