"""Treatment-choice factors that are useful enough to deserve their own owner block."""

DOG_FACTORS = {
'histiocytic sarcoma':'Localized versus disseminated disease, primary site, resectability, surgical margins, measurable disease, metastasis, previous treatment and overall health are the main treatment-changing factors.',
'lymphoma':'B-cell versus T-cell immunophenotype, grade, anatomic form, organ involvement, whether treatment has already started, depth and duration of response, relapse history and overall health can change the plan.',
'mast cell tumor':'Kiupel grade, mitotic count, tumor size and site, measured margins, regional lymph-node involvement, recurrence, metastatic disease and selected KIT findings can change treatment choices.',
'soft tissue sarcoma':'Histologic grade, size, anatomic site, whether this is a first tumor or recurrence, measured margins, resectability and metastatic evidence determine how much local and systemic treatment is justified.',
'hemangiosarcoma':'Visceral versus superficial disease, rupture or active bleeding, primary site, stage, cardiac involvement, metastasis, recovery from surgery and overall health are central.',
'osteosarcoma':'Appendicular versus axial location, pain and fracture risk, surgical feasibility, visible metastasis, alkaline phosphatase in context, prior local therapy and mobility or comorbidities affect choices.',
'oral melanoma':'Clinical stage, primary tumor size and site, bone invasion, regional-node status, lung metastasis, ability to achieve local control and prior treatment matter most.',
'melanoma':'Primary site is critical. Cutaneous, digital and mucosal melanomas have different behavior; pathology features, node status, metastasis, resectability and recurrence further change treatment.',
'oral squamous cell carcinoma':'Exact oral site, tumor size, bone invasion, regional nodes, ability to obtain useful surgical margins, expected oral function and metastatic evidence shape treatment.',
'squamous cell carcinoma':'Primary site, depth and local invasion, pathology subtype, margins, regional-node risk, recurrence and metastasis determine whether the problem is mainly local or also systemic.',
'urothelial carcinoma':'Tumor location in bladder, trigone, urethra or prostate, urine-flow obstruction, metastatic stage, kidney function, prior drugs and whether a measurable lesion remains all affect treatment.',
'hepatocellular carcinoma':'Solitary massive versus multifocal or diffuse disease, relationship to major vessels, resectability, liver function, metastasis and overall surgical fitness are the major decision points.',
'mammary carcinoma':'Tumor number and size, histologic grade, lymphovascular invasion, measured margins, regional-node status, ulceration, metastatic stage and prior surgery affect risk and treatment.',
'thyroid carcinoma':'Mobility versus fixation, vascular invasion, unilateral versus bilateral disease, iodine avidity, metastasis, surgical feasibility and prior local treatment can change the preferred approach.',
'prostate cancer':'Urinary obstruction, local invasion, pelvic or bone pain, nodal or distant metastasis, kidney function, prior NSAIDs or systemic therapy and feasibility of radiation or intervention matter.',
'primary lung tumor':'Solitary versus multifocal disease, likelihood that the lesion is truly primary, resectability, intrathoracic-node involvement, histology, margins and metastasis affect treatment.',
'glioma':'MRI location and extent, neurologic status, seizure control, presumed versus tissue-confirmed diagnosis, surgical accessibility, steroid requirement and previous radiation affect options.',
'meningioma':'Tumor location, surgical accessibility, neurologic status, residual disease, pathology grade when available, prior surgery or radiation and overall anesthetic risk guide treatment.',
'nasal tumor':'Histologic type, CT extent, cribriform-plate involvement, regional nodes, severity of bleeding or obstruction, previous radiation and recurrence affect the plan.',
'leukemia':'Acute versus chronic disease, lymphoid versus myeloid lineage, blood counts, marrow function, organ involvement, infection or bleeding risk, previous therapy and response determine treatment intensity.',
'multiple myeloma':'Kidney function, calcium, anemia, hyperviscosity, bone lesions, monoclonal-protein burden, response to treatment and overall health affect both urgency and drug choice.',
'chemodectoma':'Tumor growth rate, pericardial fluid, cardiac or airway compression, arrhythmia, metastasis, symptoms, prior drainage and ability to tolerate radiation or systemic therapy matter.',
}

CAT_FACTORS = {
'histiocytic sarcoma':'Localized versus disseminated disease, confidence in the immunohistochemical diagnosis, resectability, margins, metastasis, previous treatment and the very limited feline evidence base affect decisions.',
'lymphoma':'Anatomic form, low versus high grade, biopsy or cytology certainty, FeLV status when relevant, organ involvement, previous corticosteroid or chemotherapy exposure and overall health matter.',
'mast cell tumor':'Cutaneous versus splenic versus intestinal or disseminated disease, resectability, recurrence, organ involvement, blood or marrow findings when relevant and overall health determine treatment.',
'soft tissue sarcoma':'Injection-site versus other sarcoma, size, location, fascial extension, first surgery versus recurrence, measured margins, feasibility of wide excision and metastatic evidence are central.',
'hemangiosarcoma':'Cutaneous or subcutaneous versus visceral disease, active bleeding, primary site, resectability, metastasis and the limited evidence for feline systemic therapy shape the plan.',
'osteosarcoma':'Appendicular versus axial location, pain and fracture risk, resectability, metastatic stage, histology, mobility and the uncertain incremental benefit of chemotherapy in cats matter.',
'oral melanoma':'Diagnostic certainty, exact oral site, local invasion, regional nodes, distant metastasis, surgical feasibility and the lack of an established feline systemic standard affect treatment.',
'melanoma':'Ocular, oral, cutaneous or other primary site, local invasion, pathology confirmation, metastatic stage, resectability and whether proposed systemic therapy has feline evidence matter.',
'oral squamous cell carcinoma':'Tumor location, jaw or tongue involvement, bone invasion, ability to achieve useful margins, eating and pain status, regional spread and overall condition are major determinants.',
'squamous cell carcinoma':'Cutaneous versus oral or other site, lesion size and depth, anatomic constraints, local invasion, margins, recurrence and nodal or distant spread determine the local-treatment strategy.',
'urothelial carcinoma':'Exact urinary-tract location, obstruction, kidney function, metastatic stage, diagnostic certainty, prior drugs and feline safety data for proposed therapies shape treatment.',
'hepatocellular carcinoma':'Solitary versus multifocal or diffuse disease, vascular anatomy, resectability, liver function, metastasis and surgical fitness matter more than the diagnosis label alone.',
'mammary carcinoma':'Tumor size and multiplicity, histologic grade, lymphovascular invasion, regional-node involvement, metastatic stage, surgical extent and prior surgery strongly affect risk.',
'thyroid carcinoma':'Diagnostic certainty, local fixation or invasion, iodine avidity, metastasis, surgical feasibility, concurrent hyperthyroidism and kidney function can influence the safest option.',
'prostate cancer':'Obstruction, local invasion, metastatic sites, kidney function, diagnostic certainty and the scarcity of feline outcome data make treatment highly individualized.',
'primary lung tumor':'Solitary versus multifocal disease, resectability, pleural involvement, thoracic-node status, histology, margins and metastatic evidence affect whether surgery is worthwhile.',
'glioma':'MRI location and extent, neurologic status, seizure or edema control, confidence in a presumed diagnosis, feasibility of biopsy or surgery and access to radiation matter.',
'meningioma':'Location, surgical accessibility, neurologic status, multiplicity, residual disease after surgery, recurrence and anesthetic risk influence surgery-versus-radiation decisions.',
'nasal tumor':'Histologic type is crucial, especially lymphoma versus carcinoma; CT extent, cribriform involvement, airflow or bleeding symptoms, nodes and previous treatment also matter.',
'leukemia':'Acute versus chronic disease, lineage, FeLV status when relevant, severity of cytopenias, marrow function, infection or bleeding risk, organ involvement and response affect treatment intensity.',
'multiple myeloma':'Kidney injury, calcium, anemia, protein abnormalities, bone lesions, marrow involvement, diagnostic certainty and response to therapy guide treatment and monitoring.',
'chemodectoma':'Pericardial or pleural fluid, compression, arrhythmia, documented growth, metastasis, symptoms, diagnostic certainty and the lack of robust feline treatment data determine the plan.',
}
