EXTRA_PROFILES = {
    "Tufts University Cummings School of Veterinary Medicine": {"title":"About Tufts Veterinary Oncology","about":"Tufts' Harrington Oncology Service at Foster Hospital brings medical oncology, radiation oncology and clinical trials together for dogs and cats. The Clinical Trials Office supports studies of new treatments, diagnostics and devices and routinely enrolls veterinary patients in oncology research.","research":"The Clinical Trials Office is directed by veterinary oncologist Cheryl London, DVM, PhD. Current Tufts cancer research includes immunotherapy, CAR-T approaches, osteosarcoma, melanoma, soft tissue sarcoma and hemangiosarcoma studies.","links":[("Tufts oncology service","https://vet.tufts.edu/foster-hospital-small-animals/specialty-services/oncology"),("Tufts clinical trials","https://vet.tufts.edu/clinical-trials")]},
    "University of Georgia College of Veterinary Medicine": {"title":"About UGA Veterinary Oncology","about":"The University of Georgia Veterinary Teaching Hospital provides multidisciplinary medical, radiation and surgical oncology and participates in multi-institutional cancer clinical trials.","research":"UGA comparative oncology research includes lymphoma, bladder cancer and translational cancer therapeutics. Oncology professor Corey Saba, DVM, DACVIM, conducts clinical trials in companion animals.","links":[("UGA oncology service","https://vet.uga.edu/hospital-and-primary-care/hospital/cora-nunnally-miller-small-animal-hospital/dogs-cats/oncology/"),("UGA clinical trials","https://vet.uga.edu/research/clinical-trials/")]},
    "Oklahoma State University College of Veterinary Medicine": {"title":"About Oklahoma State Comparative Oncology","about":"Oklahoma State's College of Veterinary Medicine supports oncology and cancer-cell biology research spanning basic science and translational veterinary medicine.","research":"Current strengths include tumor biology, comparative oncology, radiation science, tumor microenvironment research and device-directed cancer therapy. The Nanomedicine and Targeted Therapy Laboratory translates focused-ultrasound and nanomedicine approaches into canine cancer studies.","links":[("OSU oncology and cancer biology","https://vetmed.okstate.edu/about/departments/physiological-sciences/oncology_cancer_cell_biology"),("OSU nanomedicine lab","https://vetmed.okstate.edu/research/nanomedicine-lab")]},
    "UT Southwestern Veterinary Research and Oncology Clinic": {"title":"About UT Southwestern VROC","about":"UT Southwestern's Veterinary Research and Oncology Clinic in Dallas is a dedicated companion-animal cancer clinic embedded in an academic medical center. Dogs and cats are evaluated for clinical trials that pair veterinary oncology care with translational cancer research.","research":"VROC studies advanced radiation therapy, focused ultrasound and histotripsy, immunotherapy, nanoparticle treatments and combination approaches for spontaneous cancers in dogs and cats.","links":[("UT Southwestern VROC","https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/"),("VROC current trials","https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html")]},
    "UC Davis Veterinary Center for Clinical Trials": {"title":"About the UC Davis Veterinary Center for Clinical Trials","about":"The UC Davis Veterinary Center for Clinical Trials coordinates clinical research at the Veterinary Medical Teaching Hospital and connects veterinary patients with active studies across oncology and other specialties.","research":"Cancer studies are coordinated with the school's oncology programs and Center for Companion Animal Health. The VCCT is directed by veterinary oncologist Robert Rebhun, DVM, PhD, whose research focuses on cancer metastasis and comparative oncology.","links":[("UC Davis VCCT","https://clinicaltrials.vetmed.ucdavis.edu/"),("UC Davis cancer studies","https://ccah.vetmed.ucdavis.edu/areas-study/cancer/cancer-clinical-studiestrials")]},
    "Ethos Veterinary Health / Ethos Discovery": {"title":"About Ethos Veterinary Oncology Research","about":"Ethos Veterinary Health conducts clinical studies through its national network of specialty hospitals. Ethos Discovery develops investigator-led studies, while Ethos Science also supports externally sponsored veterinary research. Enrollment and study visits are handled by the participating specialty hospital listed for each protocol.","research":"","image":"https://www.ethosvet.com/wp-content/uploads/Dog-Outside-on-Green-Grass-625x375.jpg","image_alt":"Dog featured by Ethos Veterinary Health","image_caption":"Photo: Ethos Veterinary Health.","links":[("Ethos clinical studies","https://www.ethosvet.com/clinical-studies/"),("How Ethos studies work","https://www.ethosvet.com/faqs-clinical-studies-at-ethos/")]},
    "Colorado Animal Specialty & Emergency (CASE)": {"title":"About CASE Clinical Studies","about":"Colorado Animal Specialty & Emergency in Boulder is a specialty and emergency hospital that participates in veterinary clinical research, including oncology studies conducted with Ethos Discovery and other research partners.","research":"Its clinical-studies program includes experimental cancer treatments and precision-medicine studies. Oncology protocols are managed through the hospital's specialty team with study-specific eligibility and benefits.","links":[("CASE clinical studies","https://www.coloradoanimalspecialty.com/clinical-studies")]},
    "MedVet Clinical Studies Center": {"title":"About MedVet Clinical Studies","about":"MedVet's Clinical Studies Center coordinates veterinary research across its specialty-hospital network, including cancer studies involving new diagnostics, pharmaceuticals, biologics, procedures and medical devices.","research":"MedVet has board-certified medical oncologists across multiple hospitals and conducts single-center and multicenter studies. Current oncology research includes an experimental EGFR/HER2 tumor vaccine at selected MedVet locations.","links":[("MedVet clinical studies","https://www.medvet.com/clinical-studies/"),("MedVet medical oncology","https://www.medvet.com/specialty/medical-oncology/")]},
    "Veterinary Referral Center of Central Oregon": {"title":"About VRCCO Oncology Clinical Trials","about":"Veterinary Referral Center of Central Oregon is a specialty hospital with an oncology service that participates in veterinary cancer clinical trials and multicenter research collaborations.","research":"The hospital's clinical-trial program evaluates investigational cancer treatments in dogs and cats; current enrollment status is published on its clinical-trials page.","links":[("VRCCO clinical trials","https://vrcvet.com/clinical-trials/"),("VRCCO oncology","https://vrcvet.com/veterinary-oncology/")]},
    "Virginia-Maryland College of Veterinary Medicine / Virginia Tech": {"title":"About Virginia Tech Veterinary Clinical Research","about":"Virginia Tech's Veterinary Clinical Research Office facilitates clinical trials and translational studies at the Virginia-Maryland College of Veterinary Medicine and Veterinary Teaching Hospital, including oncology research for companion animals.","research":"The program lists oncology among its research specialties and works with veterinary investigators, research staff, sponsors and pet owners to test new approaches to diagnosis and treatment.","links":[("Virginia Tech veterinary clinical trials","https://research.vetmed.vt.edu/clinical-trials.html")]},
}

# Exact site-name variants that occur in the treatment catalog.
_ALIASES = {
    "UT Southwestern Veterinary Research & Oncology Clinic": "UT Southwestern Veterinary Research and Oncology Clinic",
    "UT Southwestern Veterinary Research and Oncology Clinic": "UT Southwestern Veterinary Research and Oncology Clinic",
    "Ethos Veterinary Health": "Ethos Veterinary Health / Ethos Discovery",
    "Ethos Discovery / specialty-hospital network": "Ethos Veterinary Health / Ethos Discovery",
    "Colorado Animal Specialty & Emergency (CASE) / Ethos Discovery": "Colorado Animal Specialty & Emergency (CASE)",
    "MedVet Clinical Studies Center": "MedVet Clinical Studies Center",
    "Veterinary Referral Center of Central Oregon / CASTR Alliance": "Veterinary Referral Center of Central Oregon",
    "Virginia-Maryland College of Veterinary Medicine / Virginia Tech": "Virginia-Maryland College of Veterinary Medicine / Virginia Tech",
}
for _alias, _target in _ALIASES.items():
    EXTRA_PROFILES[_alias] = EXTRA_PROFILES[_target]
