"""Feline-specific practical cancer guidance. Never substitute canine outcome data."""

FELINE_PRACTICAL = {
    'lymphoma': {
        'prognosis': 'Feline lymphoma is not one disease, so one survival number would be misleading. Low-grade intestinal lymphoma can often be controlled much longer than aggressive high-grade disease. In one selected series of cats with discrete high-grade gastrointestinal lymphoma treated with surgery followed by CHOP chemotherapy, median survival was 417 days. Site, grade, stage and response to treatment matter greatly.',
        'next': 'Confirm the anatomic form and whether the lymphoma is low-grade or high-grade before assuming a prognosis or treatment plan. Intestinal, nasal, mediastinal, renal and multicentric lymphoma can behave differently. Treatment decisions for high-grade disease generally should not wait for months.',
        'tests': 'Ask whether cytology or biopsy is sufficient to establish grade and whether flow cytometry, PARR or immunohistochemistry would change treatment. CBC/chemistry and site-appropriate staging are commonly useful. Before starting steroids or chemotherapy, check whether a trial requires untreated measurable disease or a diagnostic sample.'},
    'mast cell tumor': {
        'prognosis': 'Feline mast cell tumors behave very differently by location. A solitary cutaneous mast cell tumor is often cured by surgery, while splenic, intestinal, multiple or disseminated disease needs a different discussion. In a 64-cat splenic mast cell tumor study, median tumor-specific survival was 856 days in cats that underwent splenectomy versus 342 days in cats that did not; another splenectomy series reported overall median survival of 390 days.',
        'next': 'First establish whether this is a solitary skin tumor or whether the spleen, intestine, lymph nodes or multiple skin sites are involved. Do not apply canine mast-cell grading rules to a cat. For splenic disease, splenectomy can be an important treatment decision when the cat is an appropriate surgical candidate.',
        'tests': 'For a solitary skin tumor, pathology after removal may be enough. With multiple, recurrent or visceral disease, ask what staging will change management. CBC, abdominal imaging and sampling of suspicious spleen or lymph nodes may be useful depending on the presentation.'},
    'soft tissue sarcoma': {
        'prognosis': 'Feline soft tissue sarcoma includes ordinary soft tissue sarcomas and injection-site sarcomas, which should not be treated as interchangeable. Local recurrence is a major concern, particularly for injection-site sarcoma, so the quality of the first definitive local treatment matters. Outcome varies with location, tumor size, margins, grade and whether the tumor recurs or spreads.',
        'next': 'If this could be an injection-site sarcoma, plan the first definitive surgery carefully rather than simply removing the visible lump. Wide margins and imaging may change the operation. If the tumor was already removed, pathology, measured margins and whether it fits the injection-site pattern determine what comes next.',
        'tests': 'Biopsy and cross-sectional imaging can be useful before radical surgery when the mass is large, fixed or in a difficult location. Ask the pathologist for grade and margins, and preserve blocks/slides if review or a trial may be considered.'},
    'osteosarcoma': {
        'prognosis': 'Feline osteosarcoma often behaves less aggressively than canine osteosarcoma, especially when it arises in a limb, but metastasis can occur. Appendicular and axial disease should not be given the same prognosis, and visible lung metastasis is an important adverse finding. Individual outcome depends strongly on site, stage and whether adequate local control is possible.',
        'next': 'Separate appendicular from axial disease and stage the lungs before assuming the prognosis. For a limb tumor, surgery is often the main local treatment. Pain and fracture risk still need attention immediately even though feline osteosarcoma may have a longer course than the canine form.',
        'tests': 'Orthopedic imaging, chest staging and pathology are central. Ask whether CT is needed for surgical planning or lung staging and whether adjuvant chemotherapy is reasonable for this specific cat, especially when metastatic risk appears higher.'},
    'oral squamous cell carcinoma': {
        'prognosis': 'Feline oral squamous cell carcinoma is usually aggressive locally and is often difficult to control because it is advanced when found. Published outcomes vary by site and treatment: one study reported median survival from about 33–51 days for mandibular, sublingual and maxillary tumors and 151 days for oropharyngeal tumors; a prospective radiation-plus-carboplatin study reported median survival of 163 days. A few cats do substantially better, especially when a small tumor can be completely controlled locally.',
        'next': 'This is a diagnosis where weeks can matter. Determine the exact site, tumor size and bone involvement and whether complete surgery or radiation is realistic. Eating, pain and hydration deserve attention at the same time as cancer treatment planning.',
        'tests': 'Biopsy confirmation and imaging of local extent are important before major jaw surgery or radiation. CT is often useful for defining bone invasion and treatment planning. Ask whether regional lymph nodes need sampling and whether any additional assay would actually change treatment or trial eligibility.'},
    'squamous cell carcinoma': {
        'prognosis': 'For feline cutaneous squamous cell carcinoma, location and stage matter enormously. Small superficial tumors of the nasal planum, pinnae or eyelids can sometimes be controlled for years. In a 61-cat series, surgery produced a median disease-free interval of 594 days. A 44-cat nasal-planum radiation series reported a median disease-free interval of 916 days and median overall survival of 902 days. These numbers should not be applied to oral SCC, which behaves very differently.',
        'next': 'First establish whether this is cutaneous SCC or oral SCC and record the exact site and tumor size. Early superficial skin lesions generally offer more local-treatment choices. Surgery, radiation, cryotherapy and electrochemotherapy can all be relevant in selected cutaneous cases; the best choice depends on stage, location and how much tissue would have to be removed.',
        'tests': 'Biopsy confirmation is useful when the diagnosis is uncertain or treatment would be substantial. For larger or invasive lesions, ask whether imaging is needed to define depth or bone involvement. If electrochemotherapy is being considered, tumor size and stage matter because early-stage disease has generally produced better control.'},
    'hepatocellular carcinoma': {
        'prognosis': 'Feline hepatocellular carcinoma is uncommon, and resectability is one of the most important practical questions. In a 19-cat series, cats that underwent surgical resection had a median survival of 2.4 years. A larger multicenter study of malignant feline liver tumors reported a median survival of 868 days for hepatocellular carcinoma and found much longer survival after liver lobectomy than with nonsurgical management across the full liver-tumor group. These are selected retrospective populations, not a prediction for an individual cat.',
        'next': 'Determine whether the liver tumor is a single resectable mass or multifocal/invasive disease and whether there is evidence of spread. A large liver mass is not automatically hopeless: some solitary hepatocellular carcinomas can have useful long-term control after surgery. Surgical risk and tumor location need to be assessed by a team comfortable with liver surgery.',
        'tests': 'Abdominal ultrasound or CT helps define which lobes are involved and whether surgery is realistic. Chest staging and evaluation for abdominal metastasis are reasonable before major surgery. Tissue diagnosis matters because hepatocellular carcinoma, bile duct carcinoma and other liver tumors do not have the same prognosis.'},
    'mammary carcinoma': {
        'prognosis': 'Feline mammary carcinoma is usually biologically aggressive, but outcome varies substantially with tumor size, stage and pathology. Tumors larger than 3 cm, lymph-node metastasis, lymphovascular invasion, ulceration and higher histologic grade are repeatedly associated with shorter survival. Because published cohorts and stages differ, a single median survival number is less useful than these individual findings.',
        'next': 'Measure and stage the disease before assuming surgery alone is enough. Record how many glands are involved, evaluate regional lymph nodes and lungs, and discuss the appropriate extent of feline mammary surgery. Pathology after surgery should guide whether additional treatment is worth considering.',
        'tests': 'Pathology should report histologic grade, margins and lymphovascular invasion when assessable. Ask whether regional lymph nodes should be sampled and whether chest imaging is adequate for staging. Biomarker testing should have a clear treatment or trial purpose before you pay for it.'},
    'thyroid carcinoma': {
        'prognosis': 'Feline thyroid carcinoma is rare, and most feline thyroid disease is benign hyperplasia or adenoma rather than cancer. Published carcinoma series are small, so a single survival estimate is not reliable. Long control is possible in selected cats with localized disease; a published non-hypersecretory thyroid carcinoma case remained clinically well for more than two years after thyroidectomy before suspected metastatic disease appeared.',
        'next': 'First confirm that the thyroid mass is actually suspected or proven carcinoma rather than ordinary feline hyperthyroidism. Determine whether it is freely movable or invasive, whether one or both thyroid lobes are involved, and whether there is evidence of metastasis. Surgery and radioiodine may both be considered depending on the presentation and iodine avidity.',
        'tests': 'Thyroid hormone testing alone cannot prove carcinoma. Imaging of the neck and chest can help assess invasion and spread; scintigraphy may be useful when radioiodine is being considered. Ask what tissue diagnosis is needed and whether obtaining it would change the treatment plan.'},
    'primary lung tumor': {
        'prognosis': 'Feline primary lung tumors vary sharply by grade and stage. Lymph-node involvement, pleural disease, tumor grade and completeness of local control are important prognostic features. Cats with a solitary resectable primary lung tumor can do substantially better than cats with nodal or pleural spread, so staging should drive the discussion rather than a single survival number.',
        'next': 'First confirm that this is likely a primary lung tumor rather than metastasis from another cancer. For a solitary mass, CT, surgical resectability, lymph-node status and pleural effusion are major decision points. Cats with respiratory distress or pleural fluid may need stabilization before cancer planning.',
        'tests': 'Chest CT is useful for defining the mass, intrathoracic nodes and pleural disease before surgery. Ask whether suspicious lymph nodes will be sampled and whether pathology grade will change recommendations after lobectomy.'},
    'meningioma': {
        'prognosis': 'Feline intracranial meningioma can have a very favorable long-term outlook after surgery compared with many other brain tumors. A 121-cat multicenter series reported median survival of 37 months after excision. A newer small surgical series also found long survival in many cats, while documenting meaningful perioperative risk. Tumor location and the cat’s neurologic condition still matter.',
        'next': 'Stabilize seizures or other neurologic signs, then discuss MRI and surgical accessibility. In cats, surgery is often a particularly strong option for accessible intracranial meningiomas. Radiation remains relevant when surgery is not feasible, incomplete or declined.',
        'tests': 'MRI is the key planning test. Ask whether the imaging appearance is sufficiently typical for meningioma, what the surgical risk is for that location, and whether tissue diagnosis would change the plan if surgery is not chosen.'},
    'nasal tumor': {
        'prognosis': 'Feline nasal tumors are usually dominated by local disease, but the exact histology matters. In a 42-cat intranasal carcinoma study, definitive-intent radiation produced median overall survival of 721 days versus 284 days with palliative-intent radiation. An older small series of non-lymphoid nasal tumors treated with megavoltage radiation reported median survival of 382 days.',
        'next': 'Get the tissue diagnosis and define local extent before choosing treatment. Nasal lymphoma and nasal carcinoma are not the same disease. Radiation is commonly central for non-lymphoid intranasal tumors, while lymphoma may require a different systemic/local approach.',
        'tests': 'CT of the nasal cavity plus biopsy are usually the core tests. Ask whether the cribriform plate, orbit or regional nodes are involved and whether the pathology represents lymphoma, carcinoma or another tumor type.'},
    'multiple myeloma': {
        'prognosis': 'Feline myeloma-related disease is uncommon and published outcome data are limited. A 2024 multicenter study of 50 cats reported median survival of 122 days overall, with anemia and thrombocytopenia associated with shorter survival. Older reports include individual cats living well over a year, so the disease course is variable rather than uniformly short.',
        'next': 'Assess what the plasma-cell disease is doing now: anemia, low platelets, kidney injury, high calcium, bone pain, pathologic fracture or hyperviscosity can drive urgency. Systemic therapy is usually the main treatment, with local radiation sometimes useful for painful bone lesions.',
        'tests': 'CBC/chemistry, calcium, serum and urine protein studies, imaging for bone lesions and bone-marrow evaluation may all contribute. Ask which findings are needed to confirm the diagnosis and which will be used to monitor response.'},
}

SOURCES = {
    'lymphoma': ['PMID:26333999'],
    'mast cell tumor': ['PMID:28168776', 'PMID:26083443', 'PMID:30244666'],
    'soft tissue sarcoma': ['PMID:19999355', 'PMID:21718202', 'PMID:30982391'],
    'osteosarcoma': ['PMID:41962564', 'PMID:38327132', 'PMID:11105889'],
    'oral squamous cell carcinoma': ['PMID:31113565', 'PMID:21539605', 'PMID:41158948'],
    'squamous cell carcinoma': ['PMID:23603503', 'PMID:9204469', 'PMID:28376918', 'PMID:40685551', 'PMID:42349630'],
    'hepatocellular carcinoma': ['PMID:26606201', 'PMID:36635958'],
    'mammary carcinoma': ['PMID:40150308', 'PMID:31113336', 'PMID:24741029'],
    'thyroid carcinoma': ['PMID:32655154'],
    'primary lung tumor': ['PMID:26420583', 'PMID:9662772', 'PMID:24710595'],
    'meningioma': ['PMID:26032173', 'PMID:41617661', 'PMID:38568826'],
    'nasal tumor': ['PMID:33660305', 'PMID:12027506'],
    'multiple myeloma': ['PMID:38517293', 'PMID:16112593', 'PMID:10896403'],
}
