#!/usr/bin/env python3
"""Generate crawlable owner-facing SEO pages from the effective treatment catalog."""
from __future__ import annotations
import html,json,re,shutil
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'seo'/'site'
FINDER='https://vet-cancer-trial-finder.streamlit.app/'; SITE='https://vettrialfinder.com'
EUROPE={'Belgium','Denmark','France','Germany','Italy','Netherlands','Portugal','Spain','Sweden','Switzerland','UK','Ireland','Austria','Czechia','Poland','Finland','Norway','Hungary','Slovenia','Cyprus'}
REGIONS={'north-america':{'USA','Canada'},'uk-europe':EUROPE}; SPECIES={'dogs':'Dog','cats':'Cat'}
LANGS={'en':('Clinical Trials and Cancer Treatment Studies','current treatment opportunities','Check your pet against these options'),'de':('Klinische Studien und Krebsbehandlungsstudien','aktuelle Behandlungsmöglichkeiten','Behandlungsoptionen prüfen'),'fr':('Essais cliniques et études de traitement du cancer','options thérapeutiques actuelles','Vérifier les options de traitement'),'es':('Ensayos clínicos y estudios de tratamiento del cáncer','opciones terapéuticas actuales','Consultar opciones de tratamiento'),'it':('Studi clinici e studi sul trattamento del cancro','opzioni terapeutiche attuali','Controlla le opzioni di trattamento'),'nl':('Klinische onderzoeken en kankerbehandelingsstudies','huidige behandelingsmogelijkheden','Bekijk behandelingsopties')}; EU_LANGS=('en','de','fr','es','it','nl')
CANONICAL_RULES=(('oral squamous cell carcinoma',('oral squamous cell carcinoma','oral scc','feline oral scc')),('squamous cell carcinoma',('squamous cell carcinoma','scc')),('oral melanoma',('oral melanoma','mucosal melanoma')),('melanoma',('melanoma',)),('mast cell tumor',('mast cell tumor','mast cell tumour','mct')),('soft tissue sarcoma',('soft tissue sarcoma','soft-tissue sarcoma','sts')),('histiocytic sarcoma',('histiocytic sarcoma',)),('hemangiosarcoma',('hemangiosarcoma','haemangiosarcoma','hsa')),('osteosarcoma',('osteosarcoma','bone cancer')),('urothelial carcinoma',('urothelial','transitional cell carcinoma','bladder cancer','tcc')),('hepatocellular carcinoma',('hepatocellular carcinoma','hepatic carcinoma')),('mammary carcinoma',('mammary carcinoma','mammary cancer','mammary tumor','mammary tumour')),('thyroid carcinoma',('thyroid carcinoma','thyroid cancer','thyroid tumor','thyroid tumour')),('prostate cancer',('prostate cancer','prostatic carcinoma')),('primary lung tumor',('primary lung tumor','primary lung tumour','pulmonary carcinoma','lung cancer')),('glioma',('glioma','brain tumor (glioma)','brain tumour (glioma)')),('meningioma',('meningioma',)),('nasal tumor',('nasal tumor','nasal tumour','nasal cancer','nasal carcinoma')),('lymphoma',('lymphoma','lymphosarcoma')),('leukemia',('leukemia','leukaemia')),('multiple myeloma',('multiple myeloma',)),('chemodectoma',('chemodectoma',)))
GENERIC_WORDS=('any type','other','multiple cancers','solid tumor','solid tumour','advanced unresectable')
LABELS={'active_treatment_target':'active tumor required','measurable_disease':'measurable disease required','measurable_tumor':'measurable tumor required','prior_treatment_allowed':'prior treatment allowed','progressive_disease':'progressive disease required','chemo_washout_days':'chemotherapy washout','radiation_washout_days':'radiation washout','radiation_washout_weeks':'radiation washout','no_concurrent_anticancer':'no concurrent anticancer treatment','no_concurrent_anticancer_therapy':'no concurrent anticancer therapy','no_pregnant_household_members':'household pregnancy restriction'}
DISEASE_INFO={
'histiocytic sarcoma':('Histiocytic sarcoma is an aggressive cancer of histiocytic immune cells. In dogs it may arise as a localized mass or as disseminated disease involving multiple organs, and metastatic risk is substantial. Staging commonly includes chest imaging and abdominal imaging, with additional tests guided by the primary site.','When disease is localized and removable, surgery is generally the main local treatment; radiation may be considered when complete surgical control is not possible. Because microscopic or distant spread is common, systemic chemotherapy—most often lomustine (CCNU) in canine practice—is frequently considered. Treatment is individualized by site, stage, margins and the patient’s overall health.'),
'lymphoma':('Lymphoma is a cancer of lymphocytes and can involve lymph nodes, blood, spleen, liver, gastrointestinal tract, skin or other organs. Behavior and prognosis vary substantially by anatomic form and immunophenotype, especially B-cell versus T-cell disease.','For most dogs with high-grade multicentric lymphoma, multi-agent chemotherapy such as a CHOP-based protocol is the standard first-line approach. Cats are treated according to lymphoma type and site; multi-agent chemotherapy is common for high-grade disease, while some low-grade gastrointestinal lymphomas are managed with oral chemotherapy and corticosteroids. Radiation or surgery may have roles in selected localized forms.'),
'mast cell tumor':('Mast cell tumors arise from mast cells and range from relatively indolent skin tumors to aggressive cancers with metastatic potential. Prognosis depends on grade, location, surgical margins, proliferation markers and evidence of spread.','Surgery with appropriate margins is the primary treatment for most localized cutaneous mast cell tumors. Radiation can provide local control when margins are incomplete and further surgery is not feasible. Higher-risk, unresectable or metastatic disease may require systemic therapy, including chemotherapy or targeted tyrosine-kinase inhibitors, depending on tumor biology and clinical circumstances.'),
'soft tissue sarcoma':('Soft tissue sarcomas are a diverse group of tumors arising from connective and supporting tissues. They tend to invade locally; metastatic risk varies with histologic subtype and grade.','Wide surgical excision is the principal treatment for resectable soft tissue sarcoma. Radiation is commonly considered for incomplete or narrow margins when additional surgery is impractical. Chemotherapy may be discussed for high-grade, metastatic or selected high-risk tumors, but its role varies by subtype and patient.'),
'hemangiosarcoma':('Hemangiosarcoma is an aggressive malignant tumor of blood-vessel-forming cells. In dogs it commonly affects the spleen, heart or liver and can rupture and bleed; microscopic metastasis is often present even when imaging does not show it.','For a resectable primary tumor, surgery is used for local control and to obtain a diagnosis. Because metastatic risk is high, adjuvant systemic chemotherapy—commonly doxorubicin-based in dogs—is often recommended. Treatment differs for cutaneous forms and depends on site, stage and whether rupture or metastasis has occurred.'),
'osteosarcoma':('Osteosarcoma is the most common primary bone cancer in dogs and is highly metastatic, most often spreading to the lungs. Pain and structural weakening of the affected bone are major clinical concerns.','For appendicular osteosarcoma in dogs, amputation or limb-sparing surgery provides local control, followed by systemic chemotherapy—commonly carboplatin or another platinum-based protocol—to address metastatic risk. Stereotactic or palliative radiation can be used when surgery is not appropriate.'),
'oral melanoma':('Oral melanoma is an aggressive oral cancer in dogs with significant risks of local invasion and spread to regional lymph nodes and lungs. Biological behavior can vary, but staging is important before treatment planning.','Surgery is preferred when the tumor can be removed with acceptable function. Radiation is commonly used for tumors that cannot be completely excised or when surgery is not feasible. Systemic and immunotherapeutic approaches may be considered because metastatic risk is substantial, although benefit varies by patient and disease stage.'),
'melanoma':('Melanoma arises from pigment-producing melanocytes. Its behavior depends strongly on location: some cutaneous tumors are relatively benign, while oral, nail-bed and other mucosal melanomas can be aggressive and metastatic.','Complete surgical removal is preferred for localized resectable melanoma. Radiation may be used for local control when surgery is incomplete or impractical. For aggressive or metastatic forms, systemic or immunotherapeutic options may be discussed according to site, stage and available evidence.'),
'oral squamous cell carcinoma':('Oral squamous cell carcinoma is a locally invasive epithelial cancer of the mouth. In cats it is particularly aggressive locally and is often diagnosed when complete surgical removal is difficult.','Surgery offers the best chance of durable local control when complete excision is anatomically possible. Radiation, including definitive or palliative approaches, may be considered for unresectable or incompletely excised tumors. Systemic therapies have limited and variable benefit, which is why new local and targeted treatments are actively studied.'),
'squamous cell carcinoma':('Squamous cell carcinoma is a malignant tumor of squamous epithelial cells. Behavior varies greatly by site, from some relatively controllable skin lesions to invasive oral, nasal or other tumors.','Local treatment is selected by site and extent and may include surgery, radiation or other local therapies. Systemic treatment is considered for selected advanced or metastatic cases. Site-specific staging and pathology are important because treatment and prognosis differ substantially.'),
'urothelial carcinoma':('Urothelial carcinoma, historically called transitional cell carcinoma, most often affects the urinary bladder or urethra and can obstruct urine flow or spread to lymph nodes and distant organs.','Medical treatment is common because many bladder tumors are not amenable to complete surgery. NSAID therapy combined with chemotherapy is frequently used in dogs; radiation, surgery or interventional procedures may be appropriate in selected cases. Treatment depends on tumor location, obstruction and metastatic stage.'),
'hepatocellular carcinoma':('Hepatocellular carcinoma is a primary liver cancer. A solitary massive form can behave very differently from diffuse or nodular disease, so imaging pattern and resectability strongly influence prognosis.','Surgical removal is the preferred treatment for a resectable solitary massive hepatocellular carcinoma and can provide prolonged control. Diffuse, multifocal, unresectable or metastatic disease requires individualized management, and systemic or investigational options may be considered.'),
'mammary carcinoma':('Mammary carcinoma is a malignant tumor of mammary tissue. Risk and behavior vary by species, tumor size, histologic features, lymph-node involvement and metastatic status; feline mammary carcinomas are often biologically aggressive.','Surgery is the principal treatment for localized mammary carcinoma. The extent of surgery differs between dogs and cats and by distribution of disease. Chemotherapy may be considered for high-risk, node-positive or metastatic tumors, particularly in cats, based on pathology and stage.'),
'thyroid carcinoma':('Thyroid carcinoma can occur as a movable, surgically approachable neck mass or as an invasive tumor involving surrounding structures. Functional status and metastatic risk vary.','Surgery is preferred for resectable, mobile thyroid tumors. Radiation is an important option for invasive or incompletely resectable disease. Radioactive iodine may be appropriate for selected iodine-avid tumors, while systemic therapy can be considered for metastatic or progressive disease.'),
'prostate cancer':('Prostatic carcinoma is an aggressive cancer in dogs that can invade the urinary tract and metastasize to lymph nodes, lungs and bone. Complete surgical removal is often difficult because of anatomy and disease behavior.','Treatment is usually multimodal and may include NSAIDs, chemotherapy, radiation and procedures to relieve urinary obstruction. Surgery is reserved for selected cases. Choice of therapy depends heavily on local extent, urinary function and metastatic disease.'),
'primary lung tumor':('Primary lung tumors arise from lung tissue and are distinct from cancers that have metastasized to the lungs. Solitary pulmonary carcinomas may be surgically treatable, while multifocal or metastatic disease requires a different approach.','Surgical lung-lobe removal is the standard local treatment for a solitary resectable primary lung tumor without prohibitive spread. Chemotherapy or other systemic treatment may be considered for high-risk histology, nodal involvement, unresectable disease or metastasis.'),
'glioma':('Gliomas are primary brain tumors arising from glial cells. Their location can cause seizures, behavior changes or other neurologic signs, and tissue diagnosis may be difficult without biopsy or surgery.','Treatment may include radiation therapy, surgery in selected accessible tumors, and medical management of neurologic symptoms such as seizures or brain swelling. Stereotactic radiation is commonly used at specialty centers. Experimental local, immune and targeted therapies are active areas of veterinary research.'),
'meningioma':('Meningioma is a tumor arising from the membranes surrounding the brain or spinal cord. Many are relatively slow growing, but clinical impact depends on location, compression of nervous tissue and surgical accessibility.','Surgical removal is often preferred for accessible intracranial meningiomas, particularly in cats. Radiation therapy is used for incompletely removed, inaccessible or recurrent tumors and may also be chosen as primary treatment. Supportive neurologic medications are used as needed.'),
'nasal tumor':('Nasal tumors are locally invasive cancers of the nasal cavity and sinuses. They commonly cause nasal discharge, bleeding or facial changes and may eventually invade nearby structures; distant metastasis is less immediate than local progression for many cases.','Radiation therapy is the main definitive local treatment for most canine and feline nasal cancers because complete surgery is rarely feasible. Stereotactic and conventionally fractionated radiation are both used. Chemotherapy or targeted treatment may be added for selected histologies or advanced disease.'),
'leukemia':('Leukemia is a cancer of blood-forming cells and includes biologically distinct acute and chronic forms. Diagnosis usually relies on blood and bone-marrow findings plus immunophenotyping or molecular tests.','Treatment depends on leukemia subtype. Acute leukemias generally require intensive multi-agent chemotherapy and carry a guarded prognosis, while some chronic leukemias can be controlled for longer periods with oral chemotherapy or targeted drugs. Supportive care is often important.'),
'multiple myeloma':('Multiple myeloma is a plasma-cell cancer that can affect bone marrow, bones, kidneys and blood proteins. Diagnosis is based on a combination of monoclonal protein, marrow or tumor findings and associated organ effects.','Systemic therapy is standard because myeloma is generally a disseminated disease. Melphalan with a corticosteroid has long been a common canine protocol, with other chemotherapy or targeted agents used when appropriate. Radiation can help control painful focal bone lesions.'),
'chemodectoma':('Chemodectoma, also called aortic body tumor, usually arises at the heart base. Some tumors grow slowly, while others cause cardiac compression, pericardial effusion or metastasis.','Management depends on size, symptoms and resectability. Surgery is difficult for many heart-base tumors; radiation, including stereotactic approaches, may provide local control. Medical or targeted therapy and procedures for pericardial effusion may be used in selected patients.'),
}
def load_effective():
 base=json.loads((ROOT/'data'/'trials_base.json').read_text()); upd=json.loads((ROOT/'data'/'trial_updates.json').read_text()); rows={r['id']:r for r in base}
 for p in upd.get('upsert',[]): rows[p['id']]={**rows.get(p['id'],{}),**p}
 for rid in upd.get('delete',[]): rows.pop(rid,None)
 return [r for r in rows.values() if r.get('study_type')=='treatment' and r.get('available_for_matching') is True]
def esc(x): return html.escape(str(x or ''))
def slugify(x): return re.sub(r'-+','-',re.sub(r'[^a-z0-9]+','-',x.lower())).strip('-')
def norm(x): return re.sub(r'[^a-z0-9]+',' ',str(x).lower()).strip()
def species_ok(r,s):
 v=r.get('species',''); vals=v if isinstance(v,list) else re.split(r'[/,;]',str(v)); vals={norm(x) for x in vals}; return norm(s) in vals or ('dog' in vals and 'cat' in vals)
def canonical_cancer(c):
 raw=norm(c)
 if not raw or any(norm(g) in raw for g in GENERIC_WORDS): return None
 for key,aliases in CANONICAL_RULES:
  if any(norm(a) in raw for a in aliases): return key
 return None
def row_cancers(r): return {x for x in (canonical_cancer(c) for c in r.get('cancers',[])) if x}
def display_name(k): return ' '.join({'scc':'SCC','aml':'AML'}.get(w,w.capitalize()) for w in k.split())
def prose(v):
 if v is None or v is False or v=='': return ''
 if isinstance(v,str): return v.strip()
 if isinstance(v,list): return '; '.join(filter(None,(prose(x) for x in v)))
 if isinstance(v,dict):
  out=[]
  for k,x in v.items():
   if x is False or x is None or x=='': continue
   label=LABELS.get(k,k.replace('_',' '))
   if x is True: out.append(label.capitalize())
   elif k.endswith('_days'): out.append(f'{label}: {x} days')
   elif k.endswith('_weeks'): out.append(f'{label}: {x} weeks')
   else: out.append(f'{label.capitalize()}: {prose(x)}')
  return '; '.join(out)
 return str(v)
def contact_text(r):
 v=r.get('contacts') or r.get('contact')
 if not v: return ''
 if isinstance(v,list): return '; '.join(filter(None,(prose(x) for x in v)))
 return prose(v)
def cards(rows):
 out=[]
 for r in rows:
  p=[f'<article class="card"><h3>{esc(r.get("title"))}</h3><p class="meta"><strong>{esc(r.get("center"))}</strong> · {esc(r.get("country"))}</p>']
  if r.get('status'): p.append(f'<p class="status">{esc(r["status"])}</p>')
  treatment=prose(r.get('intervention') or r.get('treatment') or r.get('notes'))
  if treatment: p.append(f'<p><b>Treatment:</b> {esc(treatment)}</p>')
  req=prose(r.get('requires')); exc=prose(r.get('excludes')); funding=prose(r.get('funding')); contact=contact_text(r)
  if req: p.append(f'<p><b>Key eligibility:</b> {esc(req)}</p>')
  if exc: p.append(f'<p><b>Important exclusions:</b> {esc(exc)}</p>')
  if funding: p.append(f'<p><b>Costs:</b> {esc(funding)}</p>')
  if contact: p.append(f'<p><b>Contact:</b> {esc(contact)}</p>')
  if r.get('last_verified'): p.append(f'<p class="verified">Last verified: {esc(r["last_verified"])}</p>')
  if r.get('url'): p.append(f'<p><a class="official" href="{esc(r["url"])}" rel="noopener">Official study / enrollment information →</a></p>')
  p.append('</article>'); out.append(''.join(p))
 return ''.join(out)
def page(title,desc,body,canonical,lang='en',alts=None):
 alternate=''.join(f'<link rel="alternate" hreflang="{k}" href="{v}">' for k,v in (alts or {}).items())
 css='*{box-sizing:border-box}body{margin:0;background:#f6f8fb;color:#17243b;font:16px/1.58 system-ui,-apple-system,sans-serif}.wrap{max-width:900px;margin:auto;padding:24px 20px 48px}header{padding:6px 0 22px;border-bottom:1px solid #dce4ec}header a{font-weight:750;text-decoration:none}header p{color:#607086;margin:.35rem 0 0}h1{font-size:clamp(2rem,5vw,3rem);line-height:1.12;margin:30px 0 12px}h2{margin:30px 0 8px;font-size:1.45rem}.lead{font-size:1.08rem;color:#42536a}.free{background:#eaf3fb;border:1px solid #d3e6f5;border-radius:12px;padding:15px 17px;margin:22px 0 14px}.free small{color:#42536a}.cta{display:inline-block;background:#175b8c;color:#fff!important;text-decoration:none;font-weight:750;padding:12px 18px;border-radius:9px}.disease{background:#fff;border:1px solid #e0e6ed;border-radius:14px;padding:2px 20px 18px;margin:26px 0}.card{background:#fff;border:1px solid #d9e2ea;border-radius:14px;padding:20px;margin:18px 0;box-shadow:0 1px 2px rgba(23,36,59,.04)}.card h3{font-size:1.28rem;line-height:1.3;margin:0 0 8px}.meta,.verified{color:#5a697c}.status{font-weight:700}.official{font-weight:650}a{color:#175b8c}footer{border-top:1px solid #dce4ec;margin-top:34px;padding-top:12px;color:#607086}@media(max-width:600px){.wrap{padding:18px 15px 36px}.card,.disease{padding-left:16px;padding-right:16px}h1{font-size:2rem}.cta{width:auto;max-width:100%}}'
 return f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{canonical}">{alternate}<style>{css}</style></head><body><div class="wrap"><header><a href="{SITE}/">← Cancer Trial Finder For Dogs And Cats</a><p>Find cancer treatment options and clinical trials for dogs and cats.</p></header><main>{body}</main><footer><p><small>Listings change. Final eligibility and enrollment decisions are made by each research or treatment team. General treatment information is educational and does not replace veterinary oncology advice.</small></p></footer></div></body></html>'
def main():
 rows=load_effective(); shutil.rmtree(OUT,ignore_errors=True); OUT.mkdir(parents=True); links=[]; index=[]; cancers=sorted(DISEASE_INFO)
 for region,countries in REGIONS.items():
  rrows=[r for r in rows if r.get('country') in countries]; langs=EU_LANGS if region=='uk-europe' else ('en',); region_label='USA & Canada' if region=='north-america' else 'UK & Europe'
  for skey,sname in SPECIES.items():
   srows=[r for r in rrows if species_ok(r,sname)]
   for key in cancers:
    hit=[r for r in srows if key in row_cancers(r)]
    label=display_name(key); slug=slugify(key)
    for lang in langs:
     prefix='' if lang=='en' else lang+'/'; path=f'{prefix}{region}/{skey}/{slug}/'; url=f'{SITE}/{path}'; alts={l:f'{SITE}/{"" if l=="en" else l+"/"}{region}/{skey}/{slug}/' for l in langs}; alts['x-default']=f'{SITE}/{region}/{skey}/{slug}/'
     h1=f'{label}: Clinical Trials and Cancer Treatment Studies for {sname}s in {region_label}' if lang=='en' else f'{label}: {LANGS[lang][0]} for {sname}s in {region_label}'
     intro=f'<h1>{esc(h1)}</h1><p class="lead">{len(hit)} {LANGS[lang][1]} in our catalog. Trial names, locations and official source links are shown below.</p>'
     intro+='<div class="free"><strong>100% FREE</strong> — view all matching trials, details, contacts and official enrollment links.<br><small>No registration. No hidden results. No paid report.</small></div>'
     intro+=f'<p><a class="cta" href="{FINDER}">{esc(LANGS[lang][2])}</a></p>'
     if lang=='en':
      about,standard=DISEASE_INFO.get(key,(f'{label} is a cancer diagnosis whose behavior, staging and treatment depend on the exact pathology, site and extent of disease.',f'Treatment for {label} is individualized according to pathology, location, stage, resectability and the patient’s overall health.'))
      intro+=f'<section class="disease"><h2>About {esc(label)}</h2><p>{esc(about)}</p><h2>Standard treatment</h2><p>{esc(standard)}</p></section><h2>Treatment &amp; research</h2><p>Below are treatment-focused clinical trials and advanced oncology options currently represented in our live catalog.</p>'
     intro+=cards(hit)
     dest=OUT/path; dest.mkdir(parents=True,exist_ok=True); (dest/'index.html').write_text(page(h1,f'Current {label} treatment trials, standard treatment overview and cancer treatment studies for {sname.lower()}s in {region_label}.',intro,url,lang,alts),encoding='utf-8'); links.append(url)
     if lang=='en': index.append((h1,path))
 body='<h1>Cancer Treatment Options and Clinical Trials for Dogs and Cats</h1><p class="lead">Browse current treatment-focused opportunities by diagnosis and region, or use the free matcher.</p><div class="free"><strong>100% FREE</strong> — view all matching trials, details, contacts and official enrollment links.<br><small>No registration. No hidden results. No paid report.</small></div><p><a class="cta" href="'+FINDER+'">Search treatment options</a></p><h2>Current treatment pages</h2><ul>'+''.join(f'<li><a href="{SITE}/{p}">{esc(n)}</a></li>' for n,p in sorted(index))+'</ul>'
 (OUT/'index.html').write_text(page('Cancer Trial Finder For Dogs And Cats | Treatment Options & Clinical Trials','Free finder for current dog and cat cancer treatment options and clinical trials.',body,SITE+'/'),encoding='utf-8'); links.insert(0,SITE+'/')
 sm='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{esc(u)}</loc></url>\n' for u in links)+'</urlset>\n'; (OUT/'sitemap.xml').write_text(sm,encoding='utf-8'); (OUT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {SITE}/sitemap.xml\n',encoding='utf-8'); (OUT/'.nojekyll').write_text(''); print(f'Generated {len(links)} pages from {len(rows)} treatment opportunities')
if __name__=='__main__': main()
