"""Practical owner-facing page section for canine histiocytic sarcoma."""
from __future__ import annotations
import re
from pathlib import Path

def canine_hs_section(label_html: str) -> str:
    return f'''<section class="disease hs-guide">
<h2>Understanding {label_html}</h2>
<p>Histiocytic sarcoma (HS) is an uncommon but aggressive cancer in dogs. It can start as <strong>one tumor in one part of the body</strong> (localized HS), or it can involve <strong>several organs</strong> (disseminated HS). The first important question is whether the cancer is still localized or has spread, because that changes both treatment options and prognosis.</p>
<div class="hs-reality"><h2>What does the prognosis look like?</h2><p>HS is serious, but the outlook varies a lot. In published groups of dogs, median survival has been roughly <strong>2–3 months for disseminated disease</strong> and about <strong>13–19 months in some dogs with localized HS treated aggressively</strong>. Some dogs do much better or worse than these numbers.</p><p><strong>No statistic can predict your dog.</strong> The practical point is that time matters. Waiting several months for an oncology appointment may mean losing useful treatment time or options.</p></div>
<h2>After an HS diagnosis</h2><p>An important next step is usually <strong>staging</strong> — checking whether cancer is present anywhere else in the body. This commonly includes chest imaging and abdominal imaging; other tests depend on where the original tumor was found. With HS, it makes sense to move the process along rather than simply wait for the next routine appointment.</p>
<h2>Where are you now?</h2><div class="hs-accordions"><details><summary>The tumor is still there</summary><div class="hs-detail"><p>If surgery is possible, ask whether it can realistically be removed with clean margins. Surgery is often the best local treatment for a removable localized tumor. If clean margins are unlikely, ask what other local-control options are reasonable.</p><p>It is also worth checking trials before surgery when there is time to do so safely: some studies require a measurable tumor, a biopsy, or direct treatment of the tumor. <strong>This is not a reason to delay surgery your veterinary team considers necessary.</strong></p></div></details><details><summary>The tumor was already removed</summary><div class="hs-detail"><p>Get the pathology report and check the margin status. The next questions are whether staging shows disease elsewhere, whether the surgical site needs more local treatment, and whether systemic treatment is recommended because HS can spread microscopically.</p></div></details><details><summary>The cancer has spread or cannot be removed</summary><div class="hs-detail"><p>Surgery may no longer be the main decision. Ask about systemic treatment, local treatment for a tumor that is causing problems, and clinical trials that accept measurable or metastatic disease.</p></div></details><details><summary>My dog is already in treatment</summary><div class="hs-detail"><p>You may still have trial options. Look specifically for studies that allow previous surgery, chemotherapy or radiation, and ask what options remain if the current treatment stops working.</p></div></details></div>
<div class="hs-waiting"><h2>If you are waiting for oncology</h2><p>Waiting does not mean there is nothing to do. Ask about a cancellation list or another oncology center if the appointment is far away. Complete recommended staging if your veterinary team can arrange it, and <strong>check clinical trials before the next treatment decision</strong>.</p><p>Some trials require a tumor to still be measurable or exclude certain previous chemotherapy or radiation. Checking early does not commit you to a trial — it simply shows you what options exist before one of them is accidentally closed.</p></div>
<div class="hs-accordions hs-more"><details><summary>Questions to ask your oncologist</summary><div class="hs-detail"><ul class="hs-questions"><li>Is this localized HS or is there evidence that it has spread?</li><li>Is the staging we have enough, or is anything important still missing?</li><li>If surgery was done, are the margins adequate and does the site need more local treatment?</li><li>Do you recommend systemic treatment now, and what are the realistic options?</li><li>Could treatment we start now affect eligibility for a clinical trial later?</li></ul></div></details><!-- How it is usually treated --><details><summary>How HS is usually treated</summary><div class="hs-detail"><p>For localized disease, surgery or radiation may be used for local control. Because HS has a meaningful risk of microscopic or distant spread, systemic chemotherapy is often discussed even after local treatment; lomustine (CCNU) is one commonly used drug in dogs. For disseminated disease, systemic treatment becomes the main focus. Clinical trials may offer additional approaches.</p></div></details><details><summary>What can affect treatment choices</summary><div class="hs-detail"><p>The biggest factors are whether HS is localized or disseminated, where it started, whether a tumor can be completely removed, surgical margins, measurable disease, metastasis, previous treatment and your dog’s overall health.</p></div></details><details><summary>Tests worth asking about</summary><div class="hs-detail"><p>There is no single cancer test that tells every dog with HS which treatment will work. If additional tumor testing or genomic profiling is available, ask one practical question before paying for it: <strong>will the result change treatment or trial eligibility now?</strong> If testing may be useful later, ask whether the pathology lab can retain the tumor block or slides from surgery.</p></div></details></div></section>'''

HS_CSS=r'''.hs-guide,.hs-guide p,.hs-guide li{color:#718096!important}.hs-guide strong{color:#60758b!important}.hs-guide h2{margin-top:25px;color:#477ca8!important;font-size:1.2rem;font-weight:700}.hs-reality,.hs-waiting{margin:19px 0;padding:16px 18px;border:1px solid #dbe7f0;border-radius:14px;background:#f8fbfd}.hs-reality h2,.hs-waiting h2{margin-top:0;color:#477ca8!important}.hs-accordions{display:grid;gap:9px;margin:12px 0 20px}.hs-accordions details{border:1px solid #dbe7f0;border-radius:12px;background:#fff;overflow:hidden}.hs-accordions summary{position:relative;cursor:pointer;list-style:none;padding:13px 42px 13px 15px;color:#4d7da3!important;font-weight:650;line-height:1.35}.hs-accordions summary::-webkit-details-marker{display:none}.hs-accordions summary:after{content:'+';position:absolute;right:15px;top:50%;transform:translateY(-50%);color:#9aabba;font-size:1.25rem;font-weight:400}.hs-accordions details[open] summary:after{content:'−'}.hs-accordions details[open] summary{background:#f8fbfd}.hs-detail{padding:2px 15px 13px;color:#718096!important}.hs-detail p{margin:.45rem 0}.hs-more{margin-top:22px}.hs-questions{padding-left:20px;margin:.35rem 0}.hs-questions li{margin:.45rem 0}@media(max-width:600px){.hs-guide h2{font-size:1.08rem;margin-top:20px;color:#477ca8!important}.hs-guide p{font-size:.96rem;line-height:1.5}.hs-reality,.hs-waiting{padding:13px 14px;margin:15px 0}.hs-accordions{gap:7px;margin:10px 0 17px}.hs-accordions summary{padding:11px 38px 11px 13px;font-size:.96rem;color:#4d7da3!important}.hs-accordions summary:after{right:13px}.hs-detail{padding:1px 13px 11px}.hs-questions{padding-left:18px}}'''.strip()

def apply_canine_hs_guide(root: Path)->int:
 root=Path(root);changed=0
 for region in ('north-america','uk-europe'):
  path=root/region/'dogs'/'histiocytic-sarcoma'/'index.html'
  if not path.exists():continue
  text=path.read_text(encoding='utf-8');new,n=re.subn(r'<section class="disease(?: hs-guide)?">.*?</section>',canine_hs_section('Histiocytic Sarcoma'),text,count=1,flags=re.S)
  if n!=1:raise AssertionError(f'Could not replace canine HS guide in {path}')
  if HS_CSS not in new:new=new.replace('</style>',HS_CSS+'</style>',1)
  if new!=text:path.write_text(new,encoding='utf-8');changed+=1
 if changed!=2:raise AssertionError(f'Expected 2 canine HS pages, changed {changed}')
 print('CANINE_HS_GUIDE_APPLIED',changed);return changed
