#!/usr/bin/env python3
"""Editorial, source-linked directory of patient-specific veterinary oncology teleconsults.

One entry per service, not per clinician or location. The named clinician may be
part of the team without being the assigned remote consultant.
"""
from __future__ import annotations

from html import escape
from pathlib import Path

import generate_seo as g
from site_config import SITE

# region, country, service, clinician label, exact credentials/context, access,
# specialty, consultation details, primary service URL, clinician/team URL, assignment.
# Country is the location of the practice, not a promise of cross-border access.
ROWS = [
('United States','United States','Malone Veterinary Cancer Consulting','Erin Malone','DVM, DACVIM (Oncology); Cornell medical oncology residency. Focuses on treatment choices and quality of life.','Owner; owner with vet','Medical oncology','First case review or second opinion; video or phone, 60 min, US$250; urgent US$350. Records and written summary.','https://www.malonecancervet.com/owners','https://www.malonecancervet.com/meet-dr-erin-malone','Named consultant'),
('United States','United States','Harris Veterinary Oncology','Krystal Harris','DVM, MS, DACVIM (Oncology); over a decade in oncology and experience developing specialty oncology services.','Owner','Medical oncology','Second opinion with records; referral not required. No new diagnosis or prescriptions online.','https://www.harris.vet/new-page','https://www.harris.vet/about','Named consultant'),
('United States','United States','Mobile Veterinary Cancer Care','Chamisa Herrera','DVM, DACVIM (Oncology); research in mast cell tumors, lung cancer, histiocytic sarcoma and Palladia.','Owner with vet','Medical oncology','Review with the owner using information from the local veterinarian; confirm scheduling and fees.','https://www.mobileveterinarycancercare.com/vets','https://www.mobileveterinarycancercare.com/about','Named consultant'),
('United States','United States','Veterinary Cancer Concierge','Lindsay Thalheim','VMD, DACVIM (Oncology); NC State oncology residency. Team also includes Brooke Britton, DACVIM, and Kari Rosen, DACVR (Radiation Oncology).','Owner','Medical oncology; radiation oncology','Phone/video case review with written summary; referral optional. Confirm which team member will consult.','https://vetcancerconcierge.com/telehealth-services/','https://vetcancerconcierge.com/about/','Team; confirm assigned clinician'),
('United States','United States','Pet Cancer Care Consulting','Rachel Venable','DVM, MS, DACVIM (Oncology); coordinates a treatment plan with the family veterinarian.','Owner with vet','Medical oncology','Joint video consultation at the local veterinarian’s practice; that practice arranges the appointment. Written summary.','https://petcancercareconsulting.com/for-vets/','https://petcancercareconsulting.com/','Named consultant'),
('United States','United States','PetCure Oncology','Kelsey Pohlmann','DVM, MS, DACVR (Radiation Oncology); Colorado State radiation oncology residency. Named for the Clifton remote radiation service; other team members are not confirmed as remote consultants.','Owner; owner with vet','Radiation oncology','Remote discussion of records and imaging before travel; physical examination and CT required before radiation treatment.','https://petcureoncology.com/telehealth/','https://petcureoncology.com/locations/clifton-newjersey/','Named at Clifton; confirm location'),
('United States','United States','Lotus Pet Oncology','Stacy Santoro Binstock','DVM, DACVIM (Oncology); oncology board certification since 2006; treatment planning and local veterinarian coordination.','Owner; owner with vet; vet only','Medical oncology','Video consultation, 45–60 min; owner can attend independently or with their veterinarian.','https://lotuspetoncology.com/for-vets/my-account/','https://lotuspetoncology.com/about/','Named consultant'),
('United States','United States','Hope Veterinary Oncology Services','Vanessa Rizzo','DVM; oncology service clinician and Western University of Health Sciences graduate. Specific oncology board credential is not stated on the reviewed page.','Owner; vet only','Oncology (credential not specified)','Owner Zoom consultation US$325; veterinarian treatment plan US$695.','https://hopevetoncology.com/pet-veterinarians-lacey-wa/','https://hopevetoncology.com/veterinarian-lacey-wa/','Named clinician; confirm booking'),
('United States','United States','Veterinary Cancer Services','Brooke Fowler','Veterinarian with oncology practice and tumor immunity research experience; precise board certification was not established on the reviewed page.','Owner','Oncology (credential not specified)','Zoom or phone consultation for families; physical treatment remains with the local veterinarian.','https://vetcancerservices.com/','https://vetcancerservices.com/about/','Named clinician; confirm booking'),
('United States','United States','Veterinary Referral Center of Central Oregon','Oncology specialist (name not published)','Clinic describes a board-certified oncology specialist but does not name the remote consultant.','Owner','Medical oncology','Informational visit after diagnosis only: canine lymphoma, osteosarcoma (including suspected cases) or splenic hemangiosarcoma. No remote treatment or prescription.','https://vrcvet.com/veterinary-oncologic-telemedicine/','','Clinician not named'),
('Other Americas','Canada','Cancer Vet Montreal','Maude Touret','DMV, MSc, DACVIM (Oncology); medical oncologist.','Owner','Medical oncology','Telephone oncology consultation for owners; confirm geographic eligibility and fee.','https://www.cancervetmontreal.com/','https://www.cancervetmontreal.com/','Named clinician; confirm booking'),
('Other Americas','Canada','Toronto Animal Cancer Centre','Christopher Pinard','DVM, DACVIM (Oncology); founder and lead oncologist. Team also includes Mia Livaccari. Assigned virtual clinician is not specified.','Owner with vet','Medical oncology','Referral from veterinarian; initial 45-minute remote conversation from home before travel or procedures.','https://www.torontoacc.com/services','https://www.torontoacc.com/ourteam','Team; confirm assigned clinician'),
('Other Americas','Canada','Dr Sarah Boston Telemedicine','Sarah Boston','DVM, DVSc, DACVS; ACVS Founding Fellow in Surgical Oncology and Oral & Maxillofacial Surgery. Surgical oncology fellowship at Colorado State University.','Owner with vet; vet only','Surgery','Video surgical oncology case review by referral. Owner consultation only for cases in Ontario; outside Ontario, veterinarian-to-veterinarian only. Written summary; fee on request.','https://drsarahboston.smart.vet/','https://drsarahboston.smart.vet/','Named consultant'),
('Other Americas','Mexico','Oncopet','Sigifredo López Arce','MVZ (UNAM); master’s in small animal clinical medicine (Barcelona) and postgraduate oncology training; clinical oncology and surgery.','Owner','Medical oncology; surgery','Video, 60 min, MXN 1,200; second opinion or follow-up after diagnosis and testing. Not an initial assessment of an unexplained lump.','https://www.oncopet.mx/service-page/teleconsulta','https://www.oncopet.mx/about-9','Named clinician'),
('Other Americas','Mexico','Oncopets México','Carlos Antelmo Celis Trejo','MVZ (UAM); postgraduate clinical oncology training at the University of Buenos Aires and diplomas in clinical oncology and oncologic surgery. No oncology board diplomate credential is claimed.','Owner','Medical oncology; surgery','Cancer video consultation for first guidance or second opinion; MXN 900 published. Confirm the assigned doctor and eligibility before paying. Separate provider from Oncopet.','https://oncopets.com.mx/','https://oncopets.com.mx/conozca-al-dr/','Founder; confirm assigned clinician'),
('Other Americas','Costa Rica','ONIVET','Carlos Coto Moya','Veterinarian with postgraduate oncology coursework and referral-service experience; DACVIM certification is not claimed.','Owner','Medical oncology','One-hour remote discussion of diagnosis, test results, options and prognosis; payment in advance.','https://oncologiaintegralveterinaria.com/consulta-virtual/','https://oncologiaintegralveterinaria.com/carlos-coto-veterinario-oncologo/','Named clinician'),
('Other Americas','Chile','OncomahuidaVet','Oncology team (Lorenzo Vargas Medina is medical director)','Founder Lorenzo Vargas Medina describes postgraduate oncology training and directs a specialist cancer and cancer surgery centre. Assigned remote clinician is not named.','Owner','Medical oncology; surgery','Video oncology case review and second opinion for owners outside Santiago or with limited mobility; examines existing biopsies and imaging. Fee on request.','https://www.oncomahuidavet.cl/servicios','https://www.oncomahuidavet.cl/centro-oncologico','Team; confirm assigned clinician'),
('Other Americas','Argentina','VetOncología','Vanda Guillén','Team member explicitly identified as providing teleconsultations to owners and veterinarians; team also includes director Matías Tellado and clinical oncologist Laura Pisano.','Owner; vet only','Medical oncology; radiation oncology','Video case review with written report; local veterinarian handles examination and prescriptions. Confirm the assigned consultant.','https://vetoncologia.com/consulta-online/','https://vetoncologia.com/nosotros/','Team; confirm assigned clinician'),
('Other Americas','Brazil','OnVeTH','Oncology team (consultant not named)','Amanda de Ascenção Rocha, CRMV RJ 7366, is listed as responsible veterinarian; the video consultant is not identified.','Owner','Oncology (credential not specified)','Initial video discussion of case history, tests and next steps. Ask who conducts the consultation.','https://onveth.com.br/','','Clinician not named'),
('Other Americas','Brazil','Samanta Rios Melo','Samanta Rios Melo','Veterinarian; surgical residency and MSc/PhD in small animal oncologic surgery at FMVZ-USP. Research and university teaching in veterinary oncology.','Owner','Medical oncology; surgery','Online second opinion and oncology follow-up by telemedicine; availability, format and fee on request.','https://sammarcursos.com.br/','https://sammarcursos.com.br/','Named practitioner; confirm booking'),
('Europe','United Kingdom','Hawk & Dove / Broadleys','Clare Knottenbelt','BVSc, MSc, DSAM, MRCVS; RCVS Recognised Specialist in Small Animal Medicine; formerly professor of small animal medicine and oncology at Glasgow. One clinician, one listing.','Owner with vet','Internal medicine with oncology practice','Zoom, 60 min, £196; written report to referring veterinarian. Local examination and veterinarian’s consent needed.','https://hawkanddovevets.co.uk/owners-page/','https://www.broadleysvets.co.uk/specialist-care/oncology/','Named consultant'),
('Europe','United Kingdom','Virtual Veterinary Specialists (VVS)','Clare Knottenbelt and Elsa Edery','Knottenbelt: RCVS Specialist in Small Animal Medicine. Edery: DipECVIM-CA and RCVS specialist in Small Animal Internal Medicine, MSc Clinical Oncology. Also listed at Hawk & Dove: separate service, shared clinician.','Owner with vet; vet only','Internal medicine with oncology practice','Practice-referral oncology teleconsultation can include specialist and owner; separate vet advice calls and case reports. Ask the referring practice whether the owner can attend and who consults.','https://www.vvs.vet/oncology-veterinary-specialists/','https://www.vvs.vet/oncology-veterinary-specialists/','Team; confirm assigned clinician'),
('Europe','United Kingdom','OncoTails','Sarah Mason','FRCVS, DipECVIM-CA (Oncology); medical and radiation oncology; over 15 years in referral hospitals.','Owner with vet','Medical oncology; radiation oncology','Video or telephone consultation arranged through the owner’s veterinary practice.','https://www.oncotails.com/','https://www.oncotails.com/about-us','Named consultant'),
('Europe','United Kingdom','Southfields','Oncology team (James Elliott is a team member)','James Elliott has European/UK oncology specialist credentials and American radiation oncology credentials; booking does not identify him as the guaranteed phone consultant.','Owner with vet','Medical oncology; radiation oncology','Telephone consultation up to 45 min with referring-vet records; in-person visit before treatment or prescriptions.','https://southfields.co.uk/remote-consultations','https://southfields.co.uk/team/oncology','Team; confirm assigned clinician'),
('Europe','United Kingdom','Cave Veterinary Specialists','Oncology service (Nele Van den Steen and Josh Hardwick)','Service leaders hold DipECVIM-CA in internal medicine and work with oncology cases; this is not an oncology diplomate credential.','Owner with vet','Internal medicine with oncology practice','Virtual discussion of options before travel; referring veterinarian’s form is available. Confirm assigned clinician.','https://www.cave-vet-specialists.co.uk/services/oncology','https://www.cave-vet-specialists.co.uk/services/oncology','Team; confirm assigned clinician'),
('Europe','United Kingdom','Royal Veterinary College','Oncology team (Andy Yale is a team member)','Andy Yale is a European and RCVS oncology specialist with interests in mast cell tumors and sentinel lymph node mapping; assigned remote clinician is not specified.','Owner','Medical oncology','Remote oncology discussion before initial travel or treatment decision.','https://www.rvc.ac.uk/small-animal-vet/specialist-referrals/clinical-services/veterinary-oncology','https://www.rvc.ac.uk/about/our-people/andy-yale','Team; confirm assigned clinician'),
('Europe','United Kingdom','Davies Veterinary Specialists','Oncology team (consultant not named)','The service does not assign a specific clinician to virtual appointments on the reviewed page.','Owner with vet','Medical oncology','Virtual first discussion of treatment options; confirm referral requirements when booking.','https://www.vetspecialists.co.uk/services/oncology/','','Clinician not named'),
('Europe','Italy','Beatrice–Villa clinic','Laura Beatrice','ACVIM Diplomate in Small Animal Internal Medicine, with oncology clinical experience; this is not ACVIM Oncology certification.','Owner; vet only','Internal medicine with oncology practice','Video second opinion; Italian, English and German offered.','https://www.ambvetbeatricevilla.eu/en/telemedicina','https://www.ambvetbeatricevilla.eu/en/telemedicina','Named clinician'),
('Europe','Czechia','CottOncology','Dagmar Kotlíková','MVDr.; worked in the oncology department at VETUNI Brno; oncology practice since 2024. ECVIM oncology diplomate status is not claimed.','Owner','Oncology (credential not specified)','Online consultation to understand diagnosis and treatment options.','https://www.dagmarkotlikova.cz/','https://www.dagmarkotlikova.cz/','Named clinician'),
('Europe','Czechia','Ondřej Škor / RegiaVet','Ondřej Škor','MVDr., DipECVIM-CA (Oncology), CertVO; European board-certified oncology specialist since 2017. Trained and worked at Vetmeduni Vienna, Animal Health Trust in the UK and Veterinary Cancer Specialists in California; interests include immunotherapy and genomics-guided treatment.','Owner','Medical oncology','Dr Škor publicly describes video consultations for owners. Contact the practice to confirm appointment format, records, fee, language and whether it accepts your location.','https://www.novinky.cz/clanek/lifestyle-osobnosti-veterinarni-onkolog-ondrej-skor-u-zvirat-chemoterapie-prodluzuje-zivot-bez-bolesti-a-potizi-40549659/','https://www.regiavet.cz/mvdr-ondrej-skor-decvim-ca-certvo','Named clinician; confirm booking'),
('Europe','Germany','Krebs beim Hund','Diana Schulenburg','Internal medicine specialist with GPcert Oncology and integrative approach; GPcert is not an ECVIM oncology diplomate.','Owner','Internal medicine with oncology practice','Second opinion by Teams or telephone, €119; German/English. Site lists both 40 and 45 min: confirm duration.','https://www.krebsbeimhund.com/service-page/tier%C3%A4rztliche-beratung-krebs','https://www.krebsbeimhund.com/service-page/tiermedizinische-onkologische-beratung','Named clinician'),
('Europe','Spain','Oncovet Online','Oncology team (Laura Arconada and Inés Álvarez)','Laura Arconada founded the service in 2010 and taught practical oncology at UCM; no ECVIM oncology diplomate credential is claimed.','Owner with vet','Medical oncology','Local veterinarian opens the case; initial remote discussion includes owner and vet, with written report.','https://www.online.oncovet.es/es','https://www.oncovet.es/quienes-somos','Team; confirm assigned clinician'),
('Europe','Spain','SOIVET','Oncology team (consultant not named)','Remote clinician and exact qualifications are not identified on the service page. Ask before booking.','Owner; vet only','Oncology (credential not specified)','Video with owner about diagnosis, options, prognosis or second opinion; separate colleague consultations and cytology reviews.','https://www.soivet.es/servicios/','','Clinician not named'),
('Asia','India','The Cancer Vet','Oncology team (Noopur Desai is founder)','Founder Noopur Desai, BVSc, MVSc (Surgery), DACVR (Radiation Oncology), trained at Wisconsin and taught at Ohio State. The assigned teleconsultant may be a different team member.','Owner','Medical oncology; radiation oncology','Owner teleconsult request with option to attach medical records; confirm assigned clinician.','https://thecancer.vet/tele-consults/','https://thecancer.vet/team/','Team; confirm assigned clinician'),
('Asia','Japan','Animal Cancer Clinic Tokyo','Yuta Ikeda','Japanese Veterinary Cancer Society Oncology I certification; over ten years with oncology patients and experience in cancer surgery. This is a Japanese credential, not DACVIM.','Owner','Medical oncology; surgery','Initial question, 30 min, ¥3,000; second opinion, 60 min, ¥5,000. Send history and test results in advance; confirm consultation language.','https://mirpet.co.jp/app/owner/clinic/detail/136','https://www.animal-cancer-clinic-tokyo.com/about','Named clinician; confirm booking'),
('Asia','Japan','TPC Hamamatsu / TPC浜松動物総合病院','Yukinori Takenobu (武信行紀)','Clinic director; Japanese Veterinary Cancer Society certified oncology level I. The platform does not guarantee he is the assigned remote clinician.','Owner','Medical oncology','Video oncology specialist opinion for untreated or treated tumors; reservation ¥3,300 plus base ¥5,500 (total ¥8,800). Send records in advance. Confirm the doctor and language.','https://mirpet.co.jp/app/owner/clinic/detail/74','https://hama-ah.com/','Clinic director; confirm assigned clinician'),
('Asia','Japan','Sakata Dog & Cat Hospital / 坂田犬猫病院','Raita Sakata (坂田雷太)','Hospital director; Japanese Veterinary Cancer Society certified oncology level II and Japanese veterinary dermatology certification. Director is explicitly named as second-opinion clinician.','Owner','Medical oncology; surgery','Online oncology second opinion for an existing diagnosis, ¥3,300 reservation plus ¥5,500 base (total ¥8,800); no new diagnosis or prescription.','https://mirpet.co.jp/app/owner/clinic/detail/208','https://www.sakatadogcathospital.jp/獣医師-動物看護師-スタッフ/','Named director'),
('Asia','Japan','Kamogawa Animal Medical Center / かもがわ動物医療センター','Oncology team (Toshiki Ito / 伊藤敏生)','The clinic lists oncologist Toshiki Ito and Japanese oncology certifications; its booking menu does not identify who conducts each remote case. Confirm a level II or level I oncology certified clinician.','Owner','Medical oncology','Online oncology second opinion; ¥3,300 reservation plus ¥11,000 base (total ¥14,300), extension after 30 min; no diagnosis or prescription.','https://mirpet.co.jp/app/owner/clinic/detail/129','https://www.kamogawa-ac.jp/staff/','Team; confirm assigned clinician'),
('Asia','Japan','Masumi Dog & Cat Hospital / ますみ犬猫病院','Masumi Nakahashi (中橋真澄)','Hospital director with a clinical interest in tumor management, palliative care and integrative medicine; no specialist oncology certification is listed in the booking profile. Confirm remote clinician.','Owner','Medical oncology','30-min online oncology second opinion, including treatment and palliative options; ¥1,100 reservation plus ¥5,500 base (total ¥6,600). No prescriptions during opinion.','https://mirpet.co.jp/app/owner/clinic/detail/299','https://masumi-ah.com/','Hospital director; confirm assigned clinician'),
('Asia','Japan','Akiyoshi Animal Clinic / アキヨシアニマルクリニック','Makoto Akiyoshi (秋吉亮人)','Clinic director; Japanese Veterinary Cancer Society oncology level I certification since 2016 and veterinary PhD from Azabu University.','Owner','Medical oncology','Zoom case consultation advertised from anywhere in Japan; oncology cases are a practice focus. Confirm new-case access, the assigned doctor, fee and language.','https://www.akiyoshi-ac.com/online','https://www.akiyoshi-ac.com/director','Clinic director; confirm assigned clinician'),
('Asia','Hong Kong','Harvest Veterinary Oncology Centre','Oncology service (remote expert not named)','Centre describes a remote discussion with an overseas expert; specialist name and credential are not stated on the service page.','Owner','Oncology (credential not specified)','Remote case review; confirm current availability, language and consultant identity.','https://hvoc.com.hk/en/oncology-services/','','Clinician not named'),
('Australia & New Zealand','Australia','MARS / Melbourne Animal Referral Services','Oncology team (Paul Crocker is a team member)','Paul Crocker is listed as lead oncology veterinarian; the telehealth page does not guarantee he personally conducts the video consultation.','Owner; vet only','Medical oncology','Video case review with written plan; offered Thursday/Friday on reviewed page. 2025–26 price list: A$300.','https://marsvets.com.au/services/vet-cancer-care-telehealth/','https://marsvets.com.au/about-us/meet-the-team/','Team; confirm assigned clinician'),
('Australia & New Zealand','Australia','Animal Cancer Centre WA','Jessica Finlay','BVSc, MVS, FANZCVS (Veterinary Oncology); registered oncology specialist, founder, medical oncology residency, research and teaching.','Owner with vet','Medical oncology','Zoom for most cases, including remote areas through the local veterinarian; confirm geographic access.','https://animalcancercentrewa.com.au/the-journey/','https://animalcancercentrewa.com.au/the-family/','Named clinician; confirm booking'),
('United States','United States','Upstate Veterinary Specialties','Specialist team (consultant not named)','Referral specialist team includes oncology; individual remote consultant is not named.','Vet only','Medical oncology','Veterinarian consults a specialist; direct owner access is not advertised.','https://www.uvsonline.com/referring-veterinarians/','','Clinician not named'),
('United States','United States','DVM STAT','Michelle Silver and Ester Yang (oncology team)','Both hold DACVIM (Oncology). Silver completed an oncology residency at New England Veterinary Oncology Group after clinical-trial work; Yang completed her residency at Virginia-Maryland College of Veterinary Medicine and teaches at Penn. Confirm which specialist accepts a particular case.','Vet only','Medical oncology','Only a treating veterinarian can request the specialist case review; confirm live call versus written options and fee.','https://www.dvmstat.com/oncology','https://www.dvmstat.com/specialists','Team; confirm assigned clinician'),
('United States','United States','University of Florida Small Animal Hospital','Paulo Vilar Saavedra (oncology service chief)','DVM, MSc, PhD, DACVIM (Oncology); medical oncology residency at Michigan State University and Virginia Tech. Research interests include clinical trials, immunotherapy and individualized treatment. The referral form does not name the responding doctor.','Vet only','Medical oncology','Referring veterinarian may request a patient-specific oncology consultation by phone or email. Upload records and diagnostic results; owner participation and the consultation fee are not stated.','https://smallanimal.vethospital.ufl.edu/contact-us/referring-veterinarians/for-referring-veterinarians-medical-oncology-referral-form/','https://www.vetmed.ufl.edu/profile/vilar-saavedra-paulo/','Team; confirm assigned clinician'),
('United States','United States','Veterinary Oncology Partners','M.J. Hamilton (co-founder)','DVM, DACVIM (Oncology); board-certified medical oncologist, oncology department builder and clinical-trial participant. Other founders have small animal internal medicine rather than oncology board credentials. The case reviewer is not identified in advance.','Vet only','Medical oncology','Written case-specific cancer opinion and treatment options submitted and received by the primary veterinarian; no direct owner consultation. Consultations available across US states; chemotherapy fulfillment has a narrower state list. Fee on request.','https://www.veterinaryoncologypartners.com/pet-owners.html','https://www.veterinaryoncologypartners.com/our-story.html','Team; confirm assigned clinician'),
('United States','United States','West Texas Veterinary Specialists','Avenelle Turner (team oncologist)','DVM, DACVIM (Oncology); Colorado State DVM, Gulf Coast oncology residency; former oncology service chief and clinical-trial investigator. Her personal assignment to a submitted case is not guaranteed.','Vet only','Medical oncology','Written individual cancer review and treatment recommendations delivered to the primary veterinarian; available to partner clinics in West Texas and Eastern New Mexico. No direct owner call. Fee on request.','https://txvetspecialty.com/services/oncology/','https://txvetspecialty.com/dr-turner/','Team; confirm assigned clinician'),
('Other Americas','Canada','Balto / ANI.ML Health','Specialist team (co-founder Christopher Pinard)','Christopher Pinard, DVM, DVSc, DACVIM (Oncology), is a Toronto medical oncologist and ANI.ML co-founder; his participation as a Balto case reviewer is not established. The service does not name the oncology consultant assigned to a case.','Vet only','Medical oncology','A veterinarian submits the cancer case online and receives a written specialist report, advertised within 24 hours. Owner cannot book a live oncology conversation through this service; ask who reviews the case and confirm price and coverage.','https://consult.animl.health/','https://www.uoguelph.ca/ovc/clinical-studies/faculty/christopher-pinard','Team; confirm assigned clinician'),
('Australia & New Zealand','Australia','Veterinary Oncology Consultants','Anthony Moore, Angela Frimberger, Penny Thomas and Amy Lane','Veterinary oncology consulting team; Penny Thomas and Amy Lane hold FANZCVS oncology credentials. Review individual biographies before booking.','Vet only','Medical oncology','Telephone/email case consultation for veterinarians worldwide; confirm currency and current price.','https://www.vetoncologyconsults.com/oncology-consulting/','https://www.vetoncologyconsults.com/about/','Team; confirm assigned clinician'),
('Australia & New Zealand','Australia','The Pet Oncologist','Cat Chan','Oncology training and ANZCVS/ACVIM oncology qualifications described by the practice; service FAQ explicitly limits individual advice to veterinarians.','Vet only','Medical oncology','Veterinarian-to-oncologist advice; no direct owner Zoom or individual advice.','https://www.thepetoncologist.com/faqs','https://www.thepetoncologist.com/about','Named consultant'),
('Australia & New Zealand','Australia','Online Oncologist','Sonya Yu','BVSc, FANZCVS (Veterinary Oncology); consulting for primary veterinarians.','Vet only','Medical oncology','Veterinary case consultation; Hong Kong offering describes a Teams-based subscription.','https://www.onlineoncologist.vet/hong-kong','https://www.onlineoncologist.vet/about','Named consultant'),
('Other Americas','Brazil','Onco Cats','Oncology team (consultant not named)','Feline oncology consultation is arranged through a veterinary colleague; confirm assigned consultant’s credentials.','Vet only','Medical oncology','Feline case consultation through the treating veterinarian.','https://www.oncocats.com/','','Clinician not named'),
('Europe','Germany','Vetonc','Franziska Hergt','DipECVIM-CA (Oncology); oncology specialist providing consultations to veterinarians.','Vet only','Medical oncology','Veterinarian-facing case review; direct owner teleconsultation is not advertised.','https://vetonc.de/','https://vetonc.de/','Named consultant'),
('Europe','France','Onkolia','Oncology team (consultant not named)','Service provides oncology opinions to veterinary colleagues; remote clinician is not individually identified on the reviewed page.','Vet only','Medical oncology','Written oncology opinion for the treating veterinarian; not a direct owner video appointment.','https://www.onkolia.fr/articles/avis-cancerologique-veterinaire-distance-confrere','','Clinician not named'),
('Australia & New Zealand','New Zealand','ARC Vets','Patrick Smith','DipECVIM-CA (Oncology); clinical interest in lymphoma.','Vet only; owner follow-up','Medical oncology','Initial remote expert discussion is through the referring veterinarian; owner remote follow-up is possible where appropriate.','https://arcvets.co.nz/services/oncology-cancer-care/','https://arcvets.co.nz/services/oncology-cancer-care/','Named clinician; confirm booking'),
]

REGIONS = ('United States', 'Other Americas', 'Europe', 'Asia', 'Australia & New Zealand')
IDS = ('united-states', 'other-americas', 'europe', 'asia', 'australia-new-zealand')
WRITTEN_VET_ONLY = {'Veterinary Oncology Partners', 'West Texas Veterinary Specialists', 'Balto / ANI.ML Health', 'Onkolia'}

CSS = '''<style>.tele-intro{max-width:850px}.tele-index{display:flex;flex-wrap:wrap;gap:8px;margin:22px 0}.tele-index a{padding:8px 12px;border:1px solid #cad9e4;border-radius:20px;text-decoration:none;background:#f5f9fb;font-weight:650}.tele-controls{display:flex;flex-wrap:wrap;gap:10px;margin:22px 0 8px}.tele-controls label{display:grid;gap:5px;font-size:.88rem;font-weight:650;color:#42566a}.tele-controls input,.tele-controls select{font:inherit;padding:10px 12px;border:1px solid #abbfce;border-radius:8px;background:#fff;color:#17324d;max-width:100%}.tele-controls input{width:min(360px,78vw)}.tele-count{color:#52677b;font-weight:650}.tele-region{margin:34px 0;scroll-margin-top:80px}.tele-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.tele-grid[hidden],.tele-card[hidden]{display:none}.tele-card{margin:0;padding:19px;border:1px solid #d6e2ea;border-radius:14px;background:#fff}.tele-card h3{margin:0 0 6px;font-size:1.16rem}.tele-card p{margin:9px 0;line-height:1.5}.tele-clinician{font-weight:700;color:#17324d}.tele-country{color:#52677b}.tele-badge{display:inline-block;margin:2px 6px 2px 0;padding:4px 8px;border-radius:15px;background:#edf4f8;color:#315f7d;font-size:.8rem}.tele-card details{border-top:1px solid #e1e9ee;padding-top:9px;margin-top:12px}.tele-card summary{cursor:pointer;font-weight:650;color:#175b8c}.tele-links a{margin-right:15px;font-weight:650}.tele-note{padding:15px 18px;border-left:4px solid #8aaec4;background:#edf4f8}.tele-empty{display:none;margin-top:14px;color:#52677b}@media(max-width:700px){.tele-grid{grid-template-columns:1fr}.tele-card{padding:15px}.tele-index{gap:6px}.tele-index a{font-size:.88rem;padding:6px 9px}} </style>'''
SCRIPT = '''<script>(()=>{const search=document.getElementById('tele-search'),audience=document.getElementById('tele-audience'),specialty=document.getElementById('tele-specialty'),count=document.getElementById('tele-count');function update(){let shown=0;document.querySelectorAll('.tele-region').forEach(region=>{let n=0;region.querySelectorAll('.tele-card').forEach(card=>{const access=card.dataset.access,match=card.dataset.search.includes(search.value.trim().toLocaleLowerCase())&&(audience.value==='all'||(audience.value==='owner'?access.includes('owner'):access.includes('vet')))&&(specialty.value==='all'||card.dataset.specialty.includes(specialty.value));card.hidden=!match;if(match){shown++;n++}});region.querySelector('.tele-grid').hidden=!n;region.querySelector('.tele-empty').style.display=n?'none':'block'});count.textContent=shown+' services shown';}for(const el of [search,audience,specialty])el.addEventListener(el===search?'input':'change',update);update()})()</script>'''


def access_key(value: str) -> str:
    # The NZ follow-up offer is conditional, so initial-case owner filter excludes it.
    return 'vet' if value.startswith('Vet only') else 'owner vet' if 'vet' in value.lower() else 'owner'


def card(row: tuple[str, ...]) -> str:
    _, country, service, clinician, bio, audience, specialty, offer, url, bio_url, assignment = row
    access = access_key(audience)
    search = ' '.join((country, service, clinician, bio, specialty, offer)).lower()
    kinds = '; '.join(x.strip() for x in specialty.split('; '))
    label = 'Clinician on video consultations' if service == 'Ondřej Škor / RegiaVet' else 'Consultation details'
    format_badge = '<span class="tele-badge">Written opinion via veterinarian</span>' if service in WRITTEN_VET_ONLY else ''
    source = f'<a href="{escape(url, quote=True)}" rel="noopener noreferrer">{label}</a>'
    if bio_url and bio_url != url:
        source += f'<a href="{escape(bio_url, quote=True)}" rel="noopener noreferrer">Clinician or team bio</a>'
    if service == 'MARS / Melbourne Animal Referral Services':
        source += '<a href="https://marsvets.com.au/wp-content/uploads/2025/08/MARS_Price-List-2025-26.pdf" rel="noopener noreferrer">2025–26 price list</a>'
    if service == 'Ondřej Škor / RegiaVet':
        source += '<a href="https://www.regiavet.cz/kontakt" rel="noopener noreferrer">Practice contact</a>'
    return (f'<article class="tele-card" data-access="{access}" data-specialty="{escape(specialty.lower(), quote=True)}" data-search="{escape(search, quote=True)}">'
            f'<h3>{escape(service)}</h3><p class="tele-clinician">{escape(clinician)} <span class="tele-country">· {escape(country)}</span></p>'
            f'<p><span class="tele-badge">{escape(audience)}</span><span class="tele-badge">{escape(kinds)}</span>{format_badge}</p>'
            f'<p>{escape(offer)}</p><details><summary>Credentials, role and sources</summary><p>{escape(bio)}</p>'
            f'<p><strong>Who conducts the appointment:</strong> {escape(assignment)}.</p><p class="tele-links">{source}</p></details></article>')


def build_page(root: Path) -> None:
    assert len(ROWS) == 56
    assert len({(row[1], row[2]) for row in ROWS}) == len(ROWS)
    assert sum(not row[5].startswith('Vet only') for row in ROWS) == 43
    jumps = ''.join(f'<a href="#{slug}">{escape(region)}</a>' for region, slug in zip(REGIONS, IDS))
    sections = ''.join(f'<section class="tele-region" id="{slug}"><h2>{escape(region)}</h2><div class="tele-grid">'
                       + ''.join(card(row) for row in ROWS if row[0] == region)
                       + '</div><p class="tele-empty">No services match these filters in this region.</p></section>'
                       for region, slug in zip(REGIONS, IDS))
    body = (CSS + '<h1>Online veterinary oncology consultations</h1>'
            '<p class="lead tele-intro">Find a remote, case-specific oncology discussion for a dog or cat. '
            'Some services let owners speak to an oncology clinician directly; others ask your local veterinarian to join or arrange the consultation. Several veterinarian-only services provide a written report instead of a live conversation. '
            'A first review of an existing case, a second opinion and follow-up are different services: read each clinic’s terms before booking.</p>'
            '<p class="tele-note"><strong>Practice country is shown beside each clinician.</strong> It does not establish where they can accept patients or prescribe. '
            'Confirm the clinician assigned to your appointment, referral and records requirements, language, fees, time zone and whether your location is eligible. '
            'A remote discussion does not replace an examination or urgent veterinary care. Published credentials are those described by the linked practice; inclusion is not an endorsement.</p>'
            + f'<nav class="tele-index" aria-label="Jump to region">{jumps}</nav>'
            '<div class="tele-controls"><label>Search clinician, service or country<input id="tele-search" type="search" autocomplete="off" placeholder="Try oncology, Mexico or Malone"></label>'
            '<label>Who can request it?<select id="tele-audience"><option value="all">All access types</option><option value="owner">Owner involved in initial review</option><option value="vet">Through a veterinarian</option></select></label>'
            '<label>Clinical focus<select id="tele-specialty"><option value="all">All oncology fields</option><option value="medical oncology">Medical oncology</option><option value="radiation oncology">Radiation oncology</option><option value="surgery">Cancer surgery</option><option value="internal medicine">Internal medicine with oncology practice</option></select></label></div>'
            '<p class="tele-count" id="tele-count" role="status" aria-live="polite">56 services shown</p>' + sections
            + '<p class="tele-note">Editorial review: September 26, 2026. These are 56 distinct services (43 involving owners in an initial review, 12 veterinarian-only, and 1 in New Zealand with owner follow-up under conditions), not a complete world registry or a count of individual doctors. Prices are published examples at the time of review; confirm current fees directly.</p>' + SCRIPT)
    dest = root / 'online-oncology-consultations'
    dest.mkdir(parents=True, exist_ok=True)
    (dest / 'index.html').write_text(g.page('Online veterinary oncology consultations | Vet Trial Finder',
        'Search veterinary oncology teleconsultations worldwide by clinician, country, specialty and owner or veterinarian access.',
        body, f'{SITE}/online-oncology-consultations/'), encoding='utf-8')
