"""Short owner-first 'Understanding' descriptions for cancer pages.

These are intentionally explanatory rather than literature-review style. They tell an
owner what the diagnosis is, what makes it behave differently, and what usually matters
next. Canine histiocytic sarcoma remains on its existing benchmark copy.
"""

DOG = {
'lymphoma': 'Lymphoma is a cancer of lymphocytes, the immune cells found throughout the body. In dogs it most often causes enlarged lymph nodes, but it can also involve the gastrointestinal tract, skin, chest, spleen, liver or other organs. The exact form matters because B-cell and T-cell disease, high-grade and low-grade disease, and localized and multicentric lymphoma can behave quite differently.',
'mast cell tumor': 'Mast cell tumors arise from mast cells, which normally help with allergic and inflammatory responses. In dogs these tumors range from small, low-risk skin masses to aggressive cancers that spread to lymph nodes or other organs. Grade, mitotic activity, location and evidence of spread are what turn the name “mast cell tumor” into a meaningful individual diagnosis.',
'soft tissue sarcoma': 'Soft tissue sarcoma is a family of tumors that arise from connective tissues such as muscle, fibrous tissue, nerves and related structures. They often send microscopic extensions into nearby tissue even when the visible mass looks well defined. Grade, subtype, size and location determine how likely the tumor is to recur locally or spread.',
'hemangiosarcoma': 'Hemangiosarcoma is a cancer of blood-vessel-forming cells. In dogs it often develops in the spleen, heart or liver, where it can rupture and cause sudden internal bleeding, although skin forms can behave very differently. Even when scans look clear, internal hemangiosarcoma carries a significant risk of microscopic spread.',
'osteosarcoma': 'Osteosarcoma is the most common primary bone cancer in dogs. It destroys normal bone, causes significant pain and can lead to fracture. The visible bone tumor is only part of the problem because microscopic spread, especially to the lungs, is common even when staging images look normal.',
'oral melanoma': 'Oral melanoma is a cancer of pigment-producing cells in the mouth. In dogs it can invade nearby bone and soft tissue and also spread to regional lymph nodes and the lungs. Tumor size, exact location and stage strongly affect both local treatment options and the risk of metastasis.',
'melanoma': 'Melanoma is a cancer of melanocytes, but the word alone does not tell you how dangerous it is. In dogs, many skin melanomas are relatively low risk, while oral, mucosal and some nail-bed melanomas are much more aggressive. The primary site and pathology are therefore essential before discussing prognosis or treatment.',
'oral squamous cell carcinoma': 'Oral squamous cell carcinoma is a cancer of the lining of the mouth that tends to grow into nearby tissue and bone. In dogs, some tumors can be controlled well if they are found in a surgically favorable location, while others are difficult because of size or anatomy. Exact site, bone invasion and stage matter greatly.',
'squamous cell carcinoma': 'Squamous cell carcinoma is a cancer of surface-lining cells and can arise in the skin, mouth, nasal cavity and other sites. Its behavior varies greatly by location, so a small cutaneous SCC and an oral or nasal SCC should not be thought of as the same disease. Site, depth and stage guide what the diagnosis means.',
'urothelial carcinoma': 'Urothelial carcinoma is a cancer of the lining of the urinary tract, most often the bladder or urethra. In dogs it commonly develops near the bladder neck, where surgery can be difficult and tumor growth can threaten urine flow. It can also spread to lymph nodes and distant organs, so both local anatomy and stage matter.',
'hepatocellular carcinoma': 'Hepatocellular carcinoma is a primary cancer of liver cells. A single large liver mass in a dog can behave very differently from multifocal or diffuse liver cancer, and some solitary tumors can be treated very successfully with surgery. The first questions are how much liver is involved, whether major vessels are affected and whether the mass can be removed safely.',
'mammary carcinoma': 'Canine mammary carcinoma is a malignant tumor of mammary tissue. These cancers range from relatively low-risk localized tumors to aggressive disease with lymph-node or lung spread. Tumor size, grade, lymphovascular invasion and stage are far more informative than the diagnosis name alone.',
'thyroid carcinoma': 'Thyroid carcinoma usually appears as a mass in the neck. In dogs, a small mobile mass that can be removed is a very different problem from a fixed tumor that wraps around major vessels or has already spread. Tumor mobility, vascular invasion and metastatic stage are central to treatment planning.',
'prostate cancer': 'Canine prostate cancer is usually an aggressive cancer that can invade the urinary tract and spread to lymph nodes, lungs or bone. Because the prostate sits in a difficult location, complete surgical removal is often not straightforward. Maintaining urine flow and understanding the extent of disease are immediate practical priorities.',
'primary lung tumor': 'A primary lung tumor starts in the lung itself and is different from cancer that has spread to the lungs from somewhere else. A single resectable mass can have a very different outlook from multiple nodules or pleural disease. Pathology, chest lymph nodes and evidence of cancer elsewhere help define the situation.',
'glioma': 'Glioma is a primary brain tumor arising from glial cells. Depending on where it sits, it may cause seizures, behavior changes, weakness, circling or balance problems. MRI often strongly suggests the diagnosis, but treatment decisions depend on location, neurologic status, control of brain swelling and whether biopsy or local therapy is feasible.',
'meningioma': 'Meningioma arises from the membranes surrounding the brain or spinal cord. Many grow relatively slowly, but they can still cause major neurologic problems by compressing normal tissue. Location, surgical accessibility and the dog’s neurologic condition are often more important than growth rate alone.',
'nasal tumor': 'Nasal tumors grow inside the nasal cavity or sinuses and usually cause problems through local invasion. Persistent discharge, nosebleeds, sneezing, noisy breathing or facial changes are common. The exact tumor type still matters, but for many dogs the key issue is how far the disease has extended locally.',
'leukemia': 'Leukemia is a cancer of blood-forming cells and includes several biologically different diseases. Acute leukemia can progress quickly, while some chronic leukemias behave much more slowly. Identifying the cell lineage and whether the disease is acute or chronic is essential before prognosis or treatment can be discussed meaningfully.',
'multiple myeloma': 'Multiple myeloma is a cancer of plasma cells, the antibody-producing cells of the immune system. It is usually a systemic disease rather than one isolated mass and can affect bone marrow, bones, kidneys, calcium levels and blood proteins. The complications it is causing are often as important as the cancer itself when treatment starts.',
'chemodectoma': 'Chemodectoma, also called an aortic body tumor, usually grows at the base of the heart. Some remain slow-growing for a long time, while others cause problems by compressing nearby structures, producing fluid around the heart or chest, or spreading. The practical significance depends on what the tumor is actually doing to the heart and surrounding organs.',
}

CAT = {
'lymphoma': 'Lymphoma is a cancer of lymphocytes and is one of the more common cancers in cats, but it is not one single disease. Intestinal, nasal, mediastinal, renal and other forms can behave very differently, and low-grade and high-grade lymphoma may need completely different treatment approaches.',
'mast cell tumor': 'Feline mast cell tumors are not simply the cat version of canine mast cell tumors. Cats can develop skin, splenic and intestinal forms, and those forms can behave very differently from one another. The anatomic site and extent of disease are usually more useful than applying canine grading rules.',
'soft tissue sarcoma': 'Soft tissue sarcoma is a group of tumors arising from connective tissues. In cats, injection-site sarcoma is especially important because microscopic tumor cells can extend far beyond the visible lump, making the first treatment plan critical. Ordinary soft tissue sarcomas and injection-site sarcomas should not automatically be treated as identical problems.',
'hemangiosarcoma': 'Feline hemangiosarcoma is a cancer of blood-vessel-forming cells and is uncommon. It can occur in the skin, under the skin or in internal organs such as the spleen. Superficial disease may behave differently from visceral disease, which can bleed and spread, so location is a major part of the diagnosis.',
'osteosarcoma': 'Osteosarcoma is a primary bone cancer in cats. It often behaves less aggressively than the typical canine form, especially in a limb, but it can still spread and axial tumors can be more difficult to control. Tumor site, resectability and staging are the most useful starting points.',
'oral melanoma': 'Feline oral melanoma is rare. It can invade nearby tissue and spread, but there is far less feline evidence than canine evidence, so a cat should not automatically be assigned a canine melanoma prognosis. Confirming the diagnosis and defining local extent and stage are the most important first steps.',
'melanoma': 'Melanoma is uncommon in cats and its behavior depends heavily on where it begins. Ocular, oral and cutaneous melanomas can follow very different courses. The primary site, pathology and stage are therefore more meaningful than the word “melanoma” by itself.',
'oral squamous cell carcinoma': 'Feline oral squamous cell carcinoma is usually an aggressive local cancer of the mouth. It often causes pain, difficulty eating and invasion of the tongue or jaw before distant spread becomes the main issue. Exact location, bone involvement and whether useful local control is anatomically possible are critical.',
'squamous cell carcinoma': 'Feline squamous cell carcinoma behaves very differently depending on where it starts. Small sun-associated lesions on the ears, eyelids or nasal planum can often be treated as local disease, while oral SCC is much more aggressive. Site and local extent are therefore central to understanding the diagnosis.',
'urothelial carcinoma': 'Feline urothelial carcinoma is an uncommon cancer of the urinary tract, usually the bladder or urethra. Local tumor growth can make urination difficult or impossible, and metastatic spread can occur. Tumor location, urine flow, kidney function and stage are the most practical concerns.',
'hepatocellular carcinoma': 'Feline hepatocellular carcinoma is a primary cancer of liver cells. A solitary liver mass that can be removed is a very different situation from multifocal or diffuse disease. Imaging is used to determine whether the tumor is truly localized and whether surgery is realistic.',
'mammary carcinoma': 'Feline mammary carcinoma is usually a biologically aggressive cancer. Smaller tumors found before lymph-node or lung spread generally carry a better outlook than larger or metastatic tumors. Tumor size, grade, lymphovascular invasion and stage are the key pieces owners should ask about.',
'thyroid carcinoma': 'Feline thyroid carcinoma is rare, and most thyroid disease in cats is benign rather than cancerous. A suspected carcinoma therefore needs to be distinguished from ordinary hyperthyroidism and assessed for invasion and spread. Resectability, iodine uptake and kidney function can all influence treatment choices.',
'prostate cancer': 'Feline prostate cancer is exceptionally rare. It can interfere with urination or defecation and may spread to lymph nodes, lungs or bone. Because published feline experience is limited, the most useful questions are what the tumor is obstructing, how far it has spread and what local control is realistically possible.',
'primary lung tumor': 'A primary lung tumor starts in the lung rather than representing cancer that has spread there from another site. In cats, a single removable mass can have a very different outlook from multiple lesions, pleural disease or lymph-node spread. Staging and resectability are therefore central.',
'glioma': 'Feline glioma is a rare primary brain tumor arising from glial cells. It may cause seizures, behavior changes, weakness or other neurologic signs. MRI is usually the key imaging test, but prognosis and treatment depend on location, neurologic status and whether local therapy is feasible.',
'meningioma': 'Meningioma is one of the more common primary brain tumors in cats and often grows as a relatively well-defined mass. Many are surgically accessible, but location and neurologic condition still determine whether surgery is realistic. It is one of the feline brain tumors where meaningful long-term control can sometimes be achieved.',
'nasal tumor': 'Feline nasal tumors grow within the nasal cavity or sinuses and can look very similar clinically even when the underlying cancer is different. Lymphoma, carcinoma and other tumors require different treatment, so biopsy results matter greatly. Local extent and breathing comfort are immediate practical concerns.',
'leukemia': 'Feline leukemia is a cancer of blood-forming cells and is not the same thing as feline leukemia virus infection, although FeLV can be associated with some cancers. Acute and chronic leukemias behave very differently, so cell lineage and disease tempo are essential before treatment or prognosis is discussed.',
'multiple myeloma': 'Multiple myeloma is a cancer of plasma cells and is uncommon in cats. It can affect bone marrow, bones, kidneys, calcium levels and blood proteins, so diagnosis usually depends on several findings together. The organ complications it causes are often important in deciding how urgently treatment is needed.',
'chemodectoma': 'Chemodectoma is a heart-base tumor and is extremely rare in cats. It may cause problems by compressing nearby structures, producing fluid around the heart or chest, causing arrhythmias or spreading. Because feline data are sparse, the individual tumor’s behavior matters more than borrowing expectations from dogs.',
'histiocytic sarcoma': 'Feline histiocytic sarcoma is a rare cancer of histiocytic immune cells. It may appear as one localized lesion or involve several organs, and confirming the diagnosis with pathology and immunohistochemistry is especially important because it can resemble other cancers. The distinction between localized and disseminated disease is central to treatment planning.',
}
