"""Owner-facing 'What matters next' copy for cancer pages.

The goal is to tell an owner what changes the next decision, not to reproduce an
oncology workup. Canine HS remains the benchmark and is intentionally untouched.
"""

DOG = {
'lymphoma': 'The first useful question is what kind of lymphoma this is. B-cell versus T-cell, high-grade versus low-grade and where the lymphoma is located can change both treatment and prognosis. If your dog is stable, ask before starting prednisone on your own or as a temporary measure: steroids can make some diagnostic tests less useful and can affect eligibility for some trials.',
'mast cell tumor': 'Find out the grade, mitotic count and whether the surgical margins are clean. The draining lymph node may need to be sampled even if it feels normal. Those details help separate a tumor likely to be solved with local treatment from one that needs staging or additional therapy.',
'soft tissue sarcoma': 'If the mass is still present, the first definitive surgery should be planned rather than treated as a simple lump removal because microscopic tumor can extend beyond what is visible. If it has already been removed, get the grade and measured margins from the pathology report before deciding whether more surgery, radiation or monitoring is appropriate.',
'hemangiosarcoma': 'First determine whether there is active or recent internal bleeding and whether the disease is confined to one site or already visible elsewhere. Collapse, marked weakness, pale gums or a swollen abdomen can be an emergency. After stabilization or surgery, pathology and staging guide the systemic-treatment discussion.',
'osteosarcoma': 'Pain control comes first, together with checking how much the affected bone has been weakened and whether there is visible spread to the lungs or elsewhere. Then the decision is how best to control the painful primary tumor—amputation, limb-sparing treatment, radiation or another approach—and whether systemic treatment should follow.',
'oral melanoma': 'The useful starting point is the stage: how large the oral tumor is, whether nearby lymph nodes contain melanoma and whether there is visible distant spread. Local control of the mouth tumor matters, but so does metastatic risk, so both questions should be addressed in the treatment plan.',
'melanoma': 'Make sure the diagnosis includes the exact site. A melanoma in haired skin, a nail bed, the mouth or another mucosal site can behave very differently. Once the site and pathology are clear, staging can be matched to the actual metastatic risk instead of treating every melanoma as the same disease.',
'oral squamous cell carcinoma': 'Define exactly where the tumor starts, how large it is and whether it has invaded jaw bone or nearby structures. Those findings often determine whether surgery can realistically remove it and whether radiation or another local treatment should be considered. Pain, bleeding and difficulty eating should be addressed at the same time.',
'squamous cell carcinoma': 'Start with the exact site and depth of the tumor. A small superficial skin SCC and a deeply invasive tumor in another location need very different plans. If it has already been removed, review the margins; if it is still present, plan local treatment around the amount of tissue involved.',
'urothelial carcinoma': 'Protect urine flow first. Ask exactly where the tumor is and whether it is narrowing the bladder outlet or urethra. Difficulty passing urine, repeated straining with little or no urine, or worsening kidney values can make the situation urgent. Once urine flow is safe, location and stage guide medical, radiation, interventional or selected surgical options.',
'hepatocellular carcinoma': 'The key question is whether this is one removable liver mass or more widespread liver disease. A large solitary mass can still be surgically treatable, so size alone should not make the decision. Imaging should show its relationship to major vessels and other liver lobes before the outlook is judged.',
'mammary carcinoma': 'Record how many mammary tumors are present and their sizes, and check the regional lymph nodes and lungs before assuming surgery is the whole treatment. After surgery, the pathology report—especially grade, margins and lymphovascular invasion—helps decide whether additional treatment is worth discussing.',
'thyroid carcinoma': 'Find out whether the thyroid mass moves freely or is fixed to surrounding tissues and whether major vessels or both thyroid lobes are involved. That often determines whether surgery is straightforward, whether more imaging is needed and whether radiation, radioactive iodine or systemic treatment should be discussed instead.',
'prostate cancer': 'Urination and comfort come first. Difficulty passing urine can require an intervention before the long-term cancer plan. Once your dog is stable, define how far the tumor extends around the prostate and urethra and whether it has spread, because those findings determine which local and systemic options are realistic.',
'primary lung tumor': 'First establish whether this looks like one primary lung tumor or could be spread from another cancer. If it is solitary, the important questions are whether it can be removed and whether chest lymph nodes or the pleura are involved. Breathing difficulty or fluid around the lungs needs stabilization before elective cancer planning.',
'glioma': 'Control seizures, severe neurologic signs and brain swelling first. MRI then helps define where the lesion is and which treatments are technically possible. The next discussion is whether the imaging diagnosis is sufficient or whether biopsy or surgery would provide information important enough to justify the added risk.',
'meningioma': 'Stabilize seizures or other neurologic problems, then use the MRI to discuss whether the tumor is safely accessible and whether surgery, radiation or both make sense for this dog. Location and neurologic condition matter more than simply asking whether a meningioma can be removed in general.',
'nasal tumor': 'Get a tissue diagnosis and define the local extent before choosing treatment. Nasal cancers can look similar on symptoms but respond differently depending on tumor type. CT is especially useful for showing whether the tumor has reached the orbit, nearby tissues or the barrier toward the brain.',
'leukemia': 'The first job is to determine whether this is acute or chronic leukemia and which blood-cell lineage is involved. Acute disease can become urgent when normal red cells, platelets or infection-fighting cells are severely reduced; chronic disease may allow more time for classification. The blood counts and your dog’s condition determine how quickly treatment or supportive care is needed.',
'multiple myeloma': 'Look first for problems the abnormal plasma cells or proteins are causing now: anemia, kidney injury, high calcium, bone pain or fractures, bleeding or neurologic signs from thickened blood. Treating those complications can be as important initially as choosing the anti-cancer drug.',
'chemodectoma': 'The immediate question is what the heart-base mass is doing, not just how large it is. Fluid around the heart or lungs, compression of nearby structures or an abnormal heart rhythm may need treatment; a stable mass causing no problems may allow a more measured discussion of monitoring, radiation or systemic therapy.',
}

CAT = {
'lymphoma': 'First establish where the lymphoma is and whether it is low-grade or high-grade. Intestinal, nasal, mediastinal, renal and other forms can behave very differently and are not treated as one disease. If your cat is stable, ask before starting prednisolone because steroids can make some diagnostic tests less useful and can affect eligibility for some trials.',
'mast cell tumor': 'Start by identifying whether this is one skin tumor or disease involving the spleen, intestine, multiple skin sites or other organs. A solitary skin mast cell tumor may need little beyond good local treatment, while visceral or disseminated disease is a different problem. Do not use canine mast-cell grading rules to interpret a cat’s tumor.',
'soft tissue sarcoma': 'If this could be an injection-site sarcoma, plan the first definitive local treatment before simply removing the visible lump; these tumors can extend much farther microscopically. If surgery has already happened, review the grade and measured margins before deciding whether another surgery or radiation should be considered.',
'hemangiosarcoma': 'First separate a skin or subcutaneous tumor from visceral disease and determine whether there is bleeding or spread. Collapse, pale gums, weakness, breathing difficulty or suspected internal bleeding can require urgent care. A completely removable skin lesion and multifocal visceral hemangiosarcoma should not be approached as the same situation.',
'osteosarcoma': 'Pain and fracture risk still matter immediately even though feline osteosarcoma often behaves differently from the canine disease. Determine whether the tumor is in a limb or an axial site and check for visible spread. Those findings help decide whether surgery can provide durable local control and whether systemic treatment is worth discussing.',
'oral melanoma': 'Confirm that the oral tumor really is melanoma, because poorly pigmented feline oral tumors can be difficult to classify. Then define how far it extends locally and whether it has spread. Eating, oral pain and bleeding need attention alongside decisions about surgery, radiation or other local treatment.',
'melanoma': 'Identify exactly where the melanoma began. Skin, oral and ocular melanomas in cats do not share one behavior or one treatment plan. Pathology and site-specific staging should guide the next step rather than canine oral-melanoma rules.',
'oral squamous cell carcinoma': 'Move quickly to define the exact site, tumor size and whether jaw bone or the tongue is involved. Those findings determine whether meaningful local control is possible. Eating, pain, hydration and weight loss deserve active management immediately rather than waiting until the cancer plan is finalized.',
'squamous cell carcinoma': 'First establish whether this is a superficial sun-associated skin lesion or a deeper SCC at another site. Small lesions on the ears, eyelids or nasal planum can have several effective local options when treated early. Oral SCC is a separate, much more difficult disease and should not be grouped with cutaneous SCC.',
'urothelial carcinoma': 'Protect urine flow first. Find out exactly where the tumor is in the bladder or urethra and whether it is causing obstruction. Repeated straining with little or no urine is urgent. Once urine flow is safe, anatomy and stage determine whether surgery, medical therapy, radiation or an interventional procedure is realistic.',
'hepatocellular carcinoma': 'The most useful first question is whether there is one removable liver mass or multifocal or invasive disease. A large solitary mass is not automatically untreatable. Imaging should define the involved liver lobes, major vessels and any visible spread before surgery is ruled in or out.',
'mammary carcinoma': 'Measure all mammary tumors and evaluate regional lymph nodes and the chest before surgery is treated as the only decision. In cats, the extent of mammary surgery can matter. Afterward, tumor size, grade, margins, lymphovascular invasion and node status help determine whether additional treatment should be discussed.',
'thyroid carcinoma': 'First make sure the thyroid mass is genuinely suspicious for carcinoma rather than ordinary feline hyperthyroidism. Then determine whether it is mobile or invasive, whether one or both lobes are involved and whether there is visible spread. Those findings help choose among surgery, radioiodine and other approaches.',
'prostate cancer': 'The immediate question is whether the mass is interfering with urination or defecation; inability to pass urine is an emergency. Once your cat is stable, define the tumor’s extent and whether it has spread before deciding whether surgery, a procedure to maintain urine flow, medical treatment or supportive care is realistic.',
'primary lung tumor': 'First determine whether this is likely one primary lung tumor rather than spread from another cancer. If it is solitary, resectability, chest lymph nodes and pleural involvement are the important decision points. Breathing distress or fluid around the lungs needs stabilization before elective surgery or cancer treatment.',
'glioma': 'Control seizures, brain swelling and other significant neurologic problems first. MRI then helps define the lesion and whether surgery, radiation or medical management is realistic. Because feline glioma is rare, ask how confident the imaging diagnosis is and whether a biopsy would actually change treatment enough to justify its risk.',
'meningioma': 'Stabilize seizures or other neurologic signs, then use MRI to determine whether the tumor is surgically accessible. In cats, surgery can be a particularly strong option for accessible meningiomas, while radiation remains useful when surgery is not feasible or complete local control is uncertain.',
'nasal tumor': 'Get a tissue diagnosis before assuming all feline nasal cancers behave the same way. Nasal lymphoma and nasal carcinoma can require very different treatment. CT helps show local extent and whether nearby structures are involved; breathing difficulty or significant bleeding can make supportive care more urgent.',
'leukemia': 'First establish whether the leukemia is acute or chronic and which cell lineage is involved. This is different from simply testing positive for feline leukemia virus. Severe anemia, low platelets or loss of infection-fighting cells can make acute leukemia urgent and may require supportive care while the exact type is being classified.',
'multiple myeloma': 'Start with the problems the plasma-cell disease is causing now: anemia, low platelets, kidney injury, high calcium, bone pain or fracture and effects of abnormal blood proteins. Those complications determine urgency and supportive care while systemic treatment is planned.',
'chemodectoma': 'First define what the heart-base mass is doing mechanically. Fluid around the heart or lungs, compression of major structures or an abnormal heart rhythm can matter more immediately than the tumor label. Once your cat is stable, imaging can guide whether treatment or careful monitoring is realistic.',
'histiocytic sarcoma': 'Confirm that the pathology and immunohistochemistry support histiocytic sarcoma and determine whether disease is localized to one area or present in several organs. A solitary lesion that can be controlled locally is a different situation from disseminated disease. Because feline experience is limited, preserve the pathology material if expert review or a research option may be useful.',
}
