"""Owner-facing factors that actually change cancer treatment choices."""

DOG = {
'lymphoma':'The biggest treatment-changing details are lymphoma type, grade, where it is in the body, whether treatment has already started and how the disease responds. A newly diagnosed B-cell lymphoma and a relapsed T-cell lymphoma are not the same treatment situation.',
'mast cell tumor':'Grade, mitotic activity, tumor location, surgical margins, lymph-node involvement, recurrence and spread are the main things that move treatment from local therapy alone toward radiation, systemic treatment or both.',
'soft tissue sarcoma':'Grade, size, location, whether this is the first tumor or a recurrence, and whether wide local control is still possible matter most. High-grade or metastatic disease makes systemic treatment more relevant.',
'hemangiosarcoma':'A superficial skin tumor and a ruptured splenic or cardiac tumor are very different diseases in practice. Primary site, bleeding, stage, metastasis and recovery from surgery drive the next choice.',
'osteosarcoma':'Tumor location, pain and fracture risk, whether surgery is feasible, visible metastasis and the dog’s mobility and other health problems determine which local and systemic options make sense.',
'oral melanoma':'Stage matters most: tumor size and site, lymph-node involvement, lung or other spread, and whether surgery or radiation can control the primary tumor.',
'melanoma':'Primary site is the key factor. Skin, nail-bed, oral and other mucosal melanomas can behave very differently, so pathology, local control, lymph nodes and distant spread are interpreted in that context.',
'oral squamous cell carcinoma':'Exact mouth location, tumor size, bone invasion, lymph-node involvement and whether local treatment can remove or control the tumor without unacceptable loss of function shape the plan.',
'squamous cell carcinoma':'Where the SCC starts, how deep it is, whether it invades nearby structures, margin status after surgery and whether it has spread determine whether this is mainly a local problem or needs a broader plan.',
'urothelial carcinoma':'Tumor location, whether urine flow is threatened, kidney function, metastatic spread and prior treatment are the main factors. A bladder-apex tumor and one involving the trigone or urethra can require very different approaches.',
'hepatocellular carcinoma':'Whether the cancer is one removable mass or multifocal or diffuse disease is the main dividing line. Its relationship to major vessels, liver function, metastasis and surgical fitness also matter.',
'mammary carcinoma':'Tumor size and number, grade, lymphovascular invasion, lymph-node involvement, margins and distant spread are the main risk factors that determine whether surgery alone is likely to be enough.',
'thyroid carcinoma':'A mobile removable mass is very different from a fixed invasive one. Vessel involvement, one versus both thyroid lobes, iodine avidity and metastasis determine whether surgery, radiation, radioiodine or systemic treatment is favored.',
'prostate cancer':'Urinary obstruction, local invasion, pain, kidney function and metastatic spread strongly affect treatment. Whether radiation or an interventional procedure can safely control the local disease is often as important as the systemic plan.',
'primary lung tumor':'A solitary removable primary tumor is different from multifocal or metastatic lung disease. Lymph-node involvement, pathology and whether complete surgery is possible are especially important.',
'glioma':'Tumor location and extent on MRI, neurologic condition, seizure control, whether the diagnosis is presumed or tissue-confirmed and whether surgery or radiation is technically feasible guide treatment.',
'meningioma':'Location, surgical accessibility, neurologic condition, residual disease after surgery, recurrence and anesthesia risk determine whether surgery, radiation or both are reasonable.',
'nasal tumor':'Tumor type, CT extent, involvement near the brain, severity of bleeding or obstruction, regional nodes and previous radiation or recurrence are the main treatment-changing details.',
'leukemia':'Acute versus chronic disease, lymphoid versus myeloid origin, blood counts, marrow function, infection or bleeding risk and response to treatment determine both urgency and treatment intensity.',
'multiple myeloma':'Kidney injury, high calcium, anemia, abnormal blood proteins, bone lesions and treatment response matter more than the diagnosis name alone because these complications often determine urgency.',
'chemodectoma':'Growth rate, fluid around the heart, compression, abnormal heart rhythm, metastasis and symptoms determine whether monitoring, radiation, systemic therapy or a procedure is most appropriate.',
}

CAT = {
'lymphoma':'Where the lymphoma is, whether it is low-grade or high-grade, how certain the diagnosis is, prior steroid or chemotherapy exposure and overall health are the main treatment-changing factors.',
'mast cell tumor':'Skin, splenic, intestinal and disseminated mast cell disease behave differently in cats. Location, resectability, recurrence and organ involvement matter more than canine grading rules.',
'soft tissue sarcoma':'Injection-site versus other sarcoma, size, location, microscopic extension, whether this is the first surgery or a recurrence and whether wide local control is still possible are the major factors.',
'hemangiosarcoma':'Cutaneous versus subcutaneous versus visceral disease, active bleeding, resectability and visible spread shape the plan. The limited feline evidence for systemic therapy also matters when weighing treatment.',
'osteosarcoma':'Limb versus axial location, pain and fracture risk, resectability and visible metastasis are the main drivers. The role of chemotherapy is less certain in cats than in dogs.',
'oral melanoma':'Diagnostic certainty, exact location, local invasion, lymph nodes, distant spread and whether complete local control is possible matter most. Systemic options should be judged by feline evidence, not canine assumptions.',
'melanoma':'Ocular, oral, cutaneous and other melanomas should be considered separately. Primary site, local invasion, pathology, metastatic stage and whether proposed systemic treatment has feline evidence guide decisions.',
'oral squamous cell carcinoma':'Tumor location, jaw or tongue involvement, bone invasion, ability to obtain useful local control, eating ability and pain are the most important treatment-changing factors.',
'squamous cell carcinoma':'Cutaneous versus oral or another site, lesion size and depth, local invasion, margins, recurrence and spread determine whether local treatment is likely to be curative or mainly palliative.',
'urothelial carcinoma':'Exact urinary-tract location, obstruction, kidney function, stage, diagnostic certainty and feline safety data for proposed drugs or procedures guide treatment.',
'hepatocellular carcinoma':'Solitary versus multifocal or diffuse disease, vascular anatomy, resectability, liver function and spread matter more than the cancer label alone.',
'mammary carcinoma':'Tumor size and number, grade, lymphovascular invasion, lymph-node involvement, metastatic stage and the extent of surgery strongly affect risk and treatment.',
'thyroid carcinoma':'Diagnostic certainty, local invasion, iodine avidity, metastasis, surgical feasibility, concurrent hyperthyroidism and kidney function determine which option is safest and most useful.',
'prostate cancer':'Obstruction, local invasion, metastasis, kidney function and confidence in the diagnosis matter most. Because feline data are sparse, every treatment choice is more individualized than in dogs.',
'primary lung tumor':'Solitary versus multifocal disease, pleural involvement, lymph-node status, pathology and whether complete surgery is possible determine whether lobectomy is worthwhile.',
'glioma':'MRI location and extent, neurologic condition, seizure and swelling control, confidence in the imaging diagnosis and access to surgery or radiation drive the plan.',
'meningioma':'Location, surgical accessibility, neurologic condition, residual disease, recurrence and anesthesia risk determine whether surgery, radiation or both are appropriate.',
'nasal tumor':'The biopsy diagnosis is crucial, especially lymphoma versus carcinoma. CT extent, involvement near the brain, airflow or bleeding problems and previous treatment also affect the plan.',
'leukemia':'Acute versus chronic disease, cell lineage, FeLV status when relevant, severity of low blood counts, infection or bleeding risk and treatment response determine urgency and intensity.',
'multiple myeloma':'Kidney injury, high calcium, anemia, abnormal proteins, bone lesions, marrow involvement and response to therapy guide both treatment and monitoring.',
'chemodectoma':'Fluid around the heart or lungs, compression, arrhythmia, documented growth, metastasis and symptoms determine whether treatment is needed at all and which option is realistic.',
'histiocytic sarcoma':'Localized versus disseminated disease, confidence in the pathology diagnosis, resectability, margins, metastasis and the limited feline evidence base shape every treatment decision.',
}
