"""Short diagnosis-specific context missing from the treatment-first cancer guides.

These blocks help an owner read the record they already have and recognize changes
that should be reported promptly. They deliberately omit breed predispositions.
"""

DOG_REPORT = {
    'histiocytic sarcoma': 'The report may describe localized histiocytic sarcoma, disseminated histiocytic sarcoma, or the distinct hemophagocytic form, which often involves the spleen and red blood cells. Because HS can resemble other poorly differentiated cancers, ask whether morphology and immunohistochemistry support the diagnosis. Keep the tumor block and slides available for review or trial screening.',
    'lymphoma': 'The word lymphoma is only the beginning of the diagnosis. Useful records identify the anatomic form, B-cell or T-cell lineage, and high- or low-grade behavior when those can be determined. Flow cytometry, PARR, cytology, biopsy, and immunohistochemistry answer different questions; not every dog needs every test.',
    'mast cell tumor': 'For a skin mast cell tumor, look for the Kiupel grade, mitotic count, measured margins, and any lymph-node result. Some reports also give a Patnaik grade. KIT pattern or c-kit mutation testing is a separate test and is most useful when it would change prognosis, targeted treatment, or trial eligibility.',
    'soft tissue sarcoma': 'Soft tissue sarcoma is a treatment group rather than one microscopic diagnosis. Reports may use names such as fibrosarcoma, peripheral nerve sheath tumor, myxosarcoma, or perivascular wall tumor. Grade, mitotic count, necrosis, and measured margins are usually more useful than the subtype name. Osteosarcoma, hemangiosarcoma, histiocytic sarcoma, and round-cell tumors should not automatically be treated as ordinary STS.',
    'hemangiosarcoma': 'A splenic mass seen on imaging is not yet a confirmed hemangiosarcoma; benign hematoma and other tumors can look similar. Surgical pathology establishes the diagnosis. The record should also distinguish superficial cutaneous, subcutaneous, splenic, cardiac, hepatic, or other visceral disease because these forms do not share one prognosis.',
    'osteosarcoma': 'The record should identify the affected bone and whether the tumor is appendicular, axial, or extraskeletal. Imaging can make osteosarcoma highly suspicious, but tissue may be required when the appearance is atypical or when confirmation is required for a treatment or trial. Pathology after surgery provides the definitive tumor type.',
    'oral melanoma': 'Oral melanoma may be melanotic or amelanotic, so it does not have to look black. Poorly pigmented tumors may need immunohistochemistry to confirm melanocytic origin. Record the original tumor diameter, exact oral site, bone invasion, measured margins, lymph-node findings, and distant stage.',
    'melanoma': 'The exact primary site belongs in the diagnosis: haired skin, digit or nail bed, oral cavity, another mucosal surface, or eye. A poorly pigmented melanoma may be called amelanotic and may require immunohistochemistry. Behavior and staging cannot be inferred from the word melanoma without the site.',
    'oral squamous cell carcinoma': 'The report should identify the exact oral site and whether jaw bone is invaded. Margin measurements and lymph-node results matter after surgery. Tonsillar squamous cell carcinoma should be identified separately because it generally carries greater metastatic concern than many non-tonsillar oral tumors.',
    'squamous cell carcinoma': 'Squamous cell carcinoma is site dependent. Keep the precise skin, nasal, digital, oral, tonsillar, or other primary site with the pathology report. Depth, invasion into bone or other structures, differentiation when reported, measured margins, and lymph-node findings can change the plan.',
    'urothelial carcinoma': 'The same disease may be called urothelial carcinoma or transitional cell carcinoma. The record should state whether it involves the bladder apex, trigone, urethra, or prostate. A positive urine BRAF mutation test strongly supports the diagnosis in the right setting; a negative result does not rule it out, and some trials still require cytology or tissue confirmation.',
    'hepatocellular carcinoma': 'Ask whether imaging and pathology describe a solitary massive hepatocellular carcinoma or nodular, multifocal, diffuse, or invasive liver disease. Those patterns have very different surgical possibilities. The report should also clarify involved lobes, vascular invasion, margins after surgery, and visible spread.',
    'mammary carcinoma': 'Record every mammary mass, not only the largest one. Useful pathology includes tumor type, grade, size, measured margins, lymphovascular invasion, and the result from the correct regional lymph node when sampled. Different nodules in the same dog can have different diagnoses.',
    'thyroid carcinoma': 'The record should distinguish a mobile, discrete thyroid tumor from fixed or invasive disease and note whether one or both lobes and major vessels are involved. Pathology may report vascular or capsular invasion and margins. Functional status and iodine avidity are separate questions that can affect selected treatments.',
    'prostate cancer': 'Reports may use prostatic carcinoma, adenocarcinoma, or urothelial carcinoma involving the prostate; these are not automatically interchangeable. Imaging and cytology or biopsy should clarify the likely origin when possible. Record involvement of the urethra, bladder, regional nodes, lungs, and bone.',
    'primary lung tumor': 'The central distinction is a primary lung tumor versus cancer metastatic to the lungs. For a removed primary tumor, keep the histologic type, differentiation or grade when reported, measured margins, lymph-node status, and any pleural involvement. Multiple nodules should not be assigned a primary-lung prognosis without establishing their origin.',
    'glioma': 'MRI may support a presumptive glioma diagnosis, while biopsy or surgery can provide a tissue diagnosis and tumor grade. These are not equivalent levels of certainty. Keep the MRI report and images, neurologic examination, steroid and seizure-medication history, and any pathology because trials may require different forms of confirmation.',
    'meningioma': 'MRI often strongly suggests meningioma, but pathology after surgery supplies the definitive type and grade. The useful record includes tumor location, relationship to critical structures, edema, whether removal was complete, and any residual tumor on postoperative imaging.',
    'nasal tumor': 'Nasal carcinoma, sarcoma, lymphoma, melanoma, and other tumors can produce similar symptoms but require different treatment. A biopsy diagnosis should be paired with CT-defined local extent, including bone destruction and involvement near the orbit or cribriform plate. “Nasal mass” alone is not a final cancer diagnosis.',
    'leukemia': 'The useful diagnosis states acute or chronic and lymphoid or myeloid lineage rather than leukemia alone. CBC and blood-smear findings may raise suspicion, while flow cytometry, PARR, bone-marrow evaluation, or other testing may be needed for classification. Keep serial blood counts because the direction and speed of change matter.',
    'multiple myeloma': 'Diagnosis usually rests on several findings rather than one test: abnormal plasma cells, a monoclonal protein, bone lesions, and organ effects may contribute. Keep serum or urine protein studies, marrow or tissue results, imaging, calcium, kidney values, CBC, and the marker chosen to follow response.',
    'chemodectoma': 'The imaging report may call this a heart-base tumor, aortic-body tumor, or chemodectoma. Imaging often supplies a presumptive diagnosis because biopsy can be difficult. Record tumor size and growth, vascular or airway compression, pericardial or pleural fluid, rhythm abnormalities, and any visible metastasis.',
}

DOG_SIGNS = {
    'histiocytic sarcoma': 'Report rapid growth, new masses, lameness, breathing changes, marked weakness, appetite loss, or pale gums. Collapse, breathing distress, or profound weakness needs urgent assessment. In hemophagocytic disease, worsening anemia can be part of the cancer rather than a local tumor problem.',
    'lymphoma': 'Track node size, appetite, weight, energy, vomiting or diarrhea, drinking and urination, and breathing. Fever, marked weakness, repeated vomiting, breathing difficulty, or rapid decline should not wait for a routine recheck. Remission means lymphoma is no longer detectable clinically; it is not the same as cure.',
    'mast cell tumor': 'Mast cell tumors can release inflammatory chemicals and suddenly swell, redden, itch, or bruise. Vomiting, black stool, abdominal pain, collapse, or a severe generalized reaction needs prompt care. Ask whether an antihistamine or stomach-protection plan is appropriate, but do not start or change medication without veterinary instructions.',
    'soft tissue sarcoma': 'Measure a visible mass consistently and report rapid growth, skin breakdown, bleeding, pain, reduced limb use, or a new mass near the scar. A painless recurrence can still matter. New coughing, breathing difficulty, or unexplained decline warrants reassessment in higher-risk disease.',
    'hemangiosarcoma': 'Collapse, pale gums, sudden weakness, a swollen abdomen, rapid breathing, or breathing distress can indicate internal bleeding or fluid around the heart and is urgent. After surgery, report new weakness or pallor promptly. A superficial skin lesion does not carry the same immediate bleeding risk as visceral disease.',
    'osteosarcoma': 'Increasing pain, sudden inability to bear weight, or a new deformity can signal severe bone weakening or fracture and needs urgent assessment. Track comfort, sleep, mobility, appetite, and breathing. Do not rely on a dog hiding pain as evidence that the bone is safe.',
    'oral melanoma': 'Report increasing mouth pain, bleeding, odor, dropping food, difficulty chewing or swallowing, weight loss, facial swelling, or breathing changes. Significant bleeding, inability to eat or drink, or respiratory distress should not wait. Check the mouth only if it can be done safely and comfortably.',
    'melanoma': 'Watch the primary site for growth, bleeding, ulceration, pain, or recurrence and report enlarged nodes, coughing, breathing changes, or unexplained weight loss in higher-risk sites. A digital tumor can first appear as persistent nail loss, swelling, lameness, or a wound that does not heal.',
    'oral squamous cell carcinoma': 'Eating more slowly, dropping food, drooling, bleeding, mouth odor, weight loss, facial swelling, or difficulty opening the mouth can reflect local progression. Inability to eat or drink, uncontrolled bleeding, or breathing difficulty needs prompt care. Nutrition and pain control should be addressed early.',
    'squamous cell carcinoma': 'Report persistent ulceration, bleeding, pain, growth, or loss of function at the primary site. Urgency depends on anatomy: breathing difficulty, inability to eat, uncontrolled bleeding, or rapidly worsening pain should not wait for a routine visit.',
    'urothelial carcinoma': 'Blood in urine, frequent attempts, accidents, pain, recurrent infection-like signs, or a weakening urine stream can occur. Repeated straining with little or no urine, vomiting with urinary difficulty, marked pain, or collapse is urgent. Symptoms can worsen even when the last scan was stable.',
    'hepatocellular carcinoma': 'Report reduced appetite, vomiting, abdominal swelling or pain, weakness, weight loss, jaundice, or pale gums. Collapse, marked abdominal distension, severe weakness, or suspected internal bleeding is urgent. Large tumors can cause mechanical or bleeding problems even before liver function fails.',
    'mammary carcinoma': 'Track growth, new nodules, redness, ulceration, discharge, bleeding, pain, or swelling of a regional node. Fever, rapidly spreading inflammation, uncontrolled bleeding, breathing difficulty, or inability to rest comfortably needs earlier care.',
    'thyroid carcinoma': 'Report changes in the neck mass, coughing, gagging, noisy breathing, swallowing difficulty, voice change, weakness, or reduced exercise tolerance. Breathing distress or sudden neck swelling is urgent. Hormone-producing tumors may also cause changes in heart rate, thirst, appetite, or weight.',
    'prostate cancer': 'Watch the urine stream, frequency, straining, blood in urine, difficulty defecating, pelvic or back pain, hind-limb lameness, and appetite. Inability to pass urine, severe pain, vomiting with urinary difficulty, or sudden weakness needs urgent assessment.',
    'primary lung tumor': 'Report increasing cough, faster breathing at rest, reduced stamina, appetite or weight loss, pain, or lameness. Labored breathing, blue or very pale gums, collapse, or inability to settle because of breathing is urgent.',
    'glioma': 'Keep a seizure log with duration and recovery and track circling, behavior, vision, balance, weakness, appetite, and steroid dose. A seizure lasting about five minutes, repeated seizures without normal recovery, rapidly worsening consciousness, or inability to stand needs emergency assessment.',
    'meningioma': 'Track seizures, behavior, vision, balance, walking, appetite, and medication changes. A prolonged seizure, repeated seizures without recovery, rapidly worsening awareness, or sudden inability to stand needs urgent assessment.',
    'nasal tumor': 'Track airflow through each nostril, discharge, nosebleeds, sneezing, facial swelling, eye changes, appetite, and sleep. Heavy or persistent bleeding, labored breathing, severe distress, or sudden neurologic signs should not wait for a routine visit.',
    'leukemia': 'Report fever, profound tiredness, pale gums, bruising, pinpoint bleeding, nosebleeds, repeated infections, appetite loss, or breathing changes. Collapse, uncontrolled bleeding, breathing difficulty, or marked weakness can reflect severe anemia, low platelets, or infection and is urgent.',
    'multiple myeloma': 'Watch for weakness, pale gums, bleeding, increased thirst or urination, vomiting, confusion, vision changes, bone pain, lameness, or sudden inability to walk. Collapse, fracture, severe neurologic change, uncontrolled bleeding, or profound weakness needs urgent care.',
    'chemodectoma': 'Track breathing rate and effort, stamina, cough, abdominal swelling, weakness, and collapse. Sudden collapse, labored breathing, very pale gums, or inability to settle can accompany fluid around the heart or chest and is urgent.',
}

# Most record-reading principles are shared. Feline overrides prevent canine rules
# from being silently applied where feline biology or terminology differs.
CAT_REPORT = dict(DOG_REPORT)
CAT_REPORT.update({
    'histiocytic sarcoma': 'Because feline histiocytic sarcoma is rare and can resemble other poorly differentiated cancers, ask whether morphology and immunohistochemistry support the diagnosis. The report should clarify whether disease is localized or present in multiple organs. Keep the tumor block and slides available for expert review or trial screening.',
    'lymphoma': 'The useful record identifies the anatomic form—such as intestinal, nasal, mediastinal, renal, or multicentric—and low- or high-grade behavior when possible. Cell lineage can matter in selected cases. Biopsy, cytology, flow cytometry, PARR, and immunohistochemistry answer different questions; not every cat needs every test.',
    'mast cell tumor': 'The record should state whether this is a solitary skin tumor or disease involving the spleen, intestine, multiple skin sites, or other organs. Canine Patnaik and Kiupel grading systems should not be used to interpret a feline mast cell tumor. Margins and mitotic activity may still add useful context.',
    'soft tissue sarcoma': 'The report may use fibrosarcoma, injection-site sarcoma, peripheral nerve sheath tumor, myxosarcoma, or another mesenchymal diagnosis. Grade, mitotic count, necrosis, and measured margins are central. If an injection-site sarcoma is possible, that history and the tumor location belong with the pathology record.',
    'hemangiosarcoma': 'The record should distinguish cutaneous, subcutaneous, splenic, cardiac, hepatic, or other visceral disease because feline evidence is limited and these forms do not share one outlook. An internal mass on imaging is not a confirmed hemangiosarcoma until tissue establishes the diagnosis.',
    'osteosarcoma': 'The record should identify the affected bone and whether the tumor is appendicular, axial, or extraskeletal. Feline osteosarcoma should not automatically be assigned canine metastatic expectations. Imaging may be highly suspicious, while pathology supplies the definitive tumor type.',
    'oral melanoma': 'Feline oral melanoma is rare and may be poorly pigmented. Immunohistochemistry may be needed to distinguish it from other oral cancers. Record the exact site, tumor size, bone invasion, margins, lymph-node findings, and distant stage rather than applying canine melanoma assumptions.',
    'melanoma': 'The exact primary site—skin, mouth, eye, digit, or another location—is essential because feline melanomas do not share one behavior. Poorly pigmented tumors may require immunohistochemistry. Canine oral-melanoma staging or vaccine evidence should not be treated as feline evidence.',
    'oral squamous cell carcinoma': 'The record should identify whether the tumor arises from the tongue, mandible, maxilla, tonsil, or another oral site and whether bone is invaded. CT and biopsy together are often more informative than “oral mass.” Margin measurements and lymph-node results matter when surgery is performed.',
    'squamous cell carcinoma': 'Keep the precise primary site with the diagnosis. Sun-associated superficial SCC of the ear, eyelid, or nasal planum is very different from oral SCC. Depth, invasion, measured margins, and lymph-node findings matter more than treating every feline SCC as one disease.',
    'urothelial carcinoma': 'The same disease may be called urothelial or transitional cell carcinoma. The record should identify the bladder or urethral location and any obstruction. Canine urine BRAF testing and canine treatment assumptions should not be applied automatically to cats; tissue or cytology requirements depend on the case and trial.',
    'mammary carcinoma': 'Record every mammary mass and its size. Useful pathology includes tumor type, grade, measured margins, lymphovascular invasion, and regional lymph-node status. Feline mammary tumors should not be assigned the generally more variable behavior of canine mammary tumors.',
    'thyroid carcinoma': 'The first record-reading question is whether this is carcinoma rather than ordinary benign hyperthyroid disease. Imaging should describe one or both lobes, mobility or invasion, vessels, and visible spread. Functional status and iodine avidity are separate questions that may affect treatment.',
    'prostate cancer': 'Feline prostate carcinoma is exceptionally rare, so confirmation of tumor origin is important. The record should distinguish prostatic carcinoma from urothelial disease involving the prostate when possible and document effects on the urethra, bladder, bowel, nodes, lungs, and bone.',
    'glioma': 'MRI may support a presumptive glioma diagnosis, while biopsy or surgery supplies tissue confirmation. Because feline glioma evidence is sparse, keep the MRI report and images, neurologic examination, medications, and any pathology available for specialist review.',
    'nasal tumor': 'Nasal lymphoma and nasal carcinoma can look alike clinically but follow different treatment pathways. A biopsy diagnosis should be paired with CT-defined local extent, including nearby bone, orbit, and cribriform plate. “Nasal mass” alone is not a final diagnosis.',
    'leukemia': 'The useful diagnosis states acute or chronic and lymphoid or myeloid lineage. Leukemia is not the same as feline leukemia virus, although FeLV testing may be part of the workup. Keep serial CBCs and the results of flow cytometry, PARR, marrow evaluation, or other classification tests when performed.',
    'multiple myeloma': 'Feline myeloma is uncommon and diagnosis usually rests on several findings together. Keep protein studies, marrow or tissue results, imaging, calcium, kidney values, CBC, and the marker chosen to follow response rather than relying on a single abnormal protein result.',
    'chemodectoma': 'The imaging report may use heart-base tumor, aortic-body tumor, or chemodectoma. Because this is exceptionally rare in cats and biopsy can be difficult, record the degree of diagnostic certainty together with tumor size, compression, fluid, rhythm abnormalities, and visible spread.',
})
CAT_SIGNS = dict(DOG_SIGNS)
CAT_SIGNS.update({
    'lymphoma': 'Track appetite, weight, vomiting or diarrhea, breathing, nasal airflow, drinking and urination, and any enlarged nodes according to the lymphoma site. Marked weakness, repeated vomiting, breathing difficulty, inability to eat, or rapid decline should not wait. Remission is control of detectable disease, not the same as cure.',
    'mast cell tumor': 'Track changes in skin tumors and report vomiting, appetite loss, black stool, abdominal pain, weakness, or collapse. Visceral mast cell disease can behave very differently from one skin tumor. Sudden severe illness, collapse, or evidence of gastrointestinal bleeding needs prompt care.',
    'soft tissue sarcoma': 'Measure a visible mass consistently and report rapid growth, skin breakdown, bleeding, pain, reduced movement, or a new mass near the scar. For a suspected injection-site sarcoma, do not wait for it to become very large before obtaining a planned surgical or oncology assessment.',
    'osteosarcoma': 'Increasing pain, sudden inability to bear weight, or a new deformity can signal severe bone weakening or fracture and needs urgent assessment. Cats often hide pain, so reduced jumping, hiding, irritability, or reluctance to use the litter box can be meaningful.',
    'oral melanoma': 'Report drooling, mouth odor, bleeding, dropping food, facial swelling, weight loss, or reduced grooming. Inability to eat or drink, uncontrolled bleeding, or breathing difficulty needs prompt care. Oral comfort and nutrition should be addressed while the diagnosis and plan are refined.',
    'melanoma': 'Watch the primary site for growth, bleeding, ulceration, pain, vision change, or recurrence and report enlarged nodes, breathing changes, or weight loss when the site carries metastatic concern. Eye pain or sudden visual change deserves prompt ophthalmic assessment.',
    'oral squamous cell carcinoma': 'Drooling, mouth odor, pawing at the mouth, dropping food, hiding, reduced grooming, weight loss, or difficulty swallowing often reflect local pain and progression. Inability to eat or drink, uncontrolled bleeding, or breathing difficulty needs prompt care. Nutritional support should be discussed early.',
    'urothelial carcinoma': 'Blood in urine, frequent trips to the litter box, urinating outside the box, pain, or repeated straining can resemble lower urinary tract disease. Little or no urine, vomiting with urinary difficulty, marked pain, or collapse is an emergency.',
    'mammary carcinoma': 'Track growth, new nodules, redness, ulceration, discharge, bleeding, pain, or swelling near regional nodes. Cats may hide discomfort; reduced grooming, hiding, or reluctance to lie in a normal position can matter. Breathing difficulty or uncontrolled bleeding needs prompt care.',
    'thyroid carcinoma': 'Report changes in the neck mass, noisy breathing, swallowing difficulty, coughing, weakness, or reduced activity. Functional tumors may also cause weight loss despite appetite, restlessness, vomiting, thirst, or a fast heart rate. Breathing distress or sudden neck swelling is urgent.',
    'prostate cancer': 'Watch for repeated litter-box visits, straining to urinate or defecate, blood in urine, constipation, pelvic pain, hiding, or reduced appetite. Little or no urine, vomiting with urinary difficulty, severe pain, or collapse is an emergency.',
    'primary lung tumor': 'Report faster breathing during sleep, increased effort, cough, reduced activity, appetite loss, weight loss, pain, or lameness. Open-mouth breathing, blue or very pale gums, collapse, or inability to settle because of breathing is an emergency in a cat.',
    'glioma': 'Keep a seizure log and track behavior, vision, balance, walking, hiding, appetite, and medication changes. A prolonged seizure, repeated seizures without normal recovery, rapidly worsening awareness, or inability to stand needs emergency assessment.',
    'meningioma': 'Track seizures, behavior, vision, balance, walking, grooming, appetite, and medication changes. A prolonged seizure, repeated seizures without recovery, rapidly worsening awareness, or sudden inability to stand needs urgent assessment.',
    'nasal tumor': 'Track airflow, discharge, nosebleeds, sneezing, facial or eye changes, appetite, and weight. Cats with nasal obstruction may stop eating when they cannot smell food. Open-mouth breathing, heavy bleeding, severe distress, or sudden neurologic signs is urgent.',
    'leukemia': 'Report fever, profound tiredness, pale gums, bruising, pinpoint bleeding, repeated infections, appetite loss, or breathing changes. Collapse, uncontrolled bleeding, open-mouth breathing, or marked weakness can reflect severe anemia, low platelets, or infection and is urgent.',
    'multiple myeloma': 'Watch for weakness, pale gums, bleeding, increased thirst or urination, vomiting, confusion, vision changes, bone pain, reduced jumping, or sudden inability to walk. Collapse, fracture, severe neurologic change, or profound weakness needs urgent care.',
    'chemodectoma': 'Track sleeping breathing rate and effort, activity, weakness, and collapse. Open-mouth breathing, sudden collapse, very pale gums, or inability to settle can accompany fluid around the heart or chest and is an emergency.',
})
