import streamlit as st

OPTIONS = [
    {"id":"hsa-fidocure-genomic-guidance","species":"Dog","countries":["USA"],"cancers":["Hemangiosarcoma"],"situations":["Splenic hemangiosarcoma"],"name":"FidoCure genomic guidance","summary":"Tumor genomic profiling to guide targeted therapy after splenic hemangiosarcoma diagnosis.","access":"USA — ordered and managed through the treating veterinarian/oncologist; FFPE tumor tissue can be used.","evidence":"Retrospective real-world comparative evidence. A 2025 Scientific Reports study analyzed 508 dogs with splenic hemangiosarcoma; treatment records were available for 421 dogs from 257 U.S. veterinary practices. In stage II disease, median overall survival was 249 days with chemotherapy plus targeted therapy versus 141 days with chemotherapy; in stage III, 139 versus 89 days.","evidence_level":"Comparative real-world clinical evidence","sample":"FFPE tumor tissue / pathology material","travel":"No research-center travel inherently required","url":"https://www.nature.com/articles/s41598-025-89862-9","access_url":"https://fidocure.com/for-veterinarians/","limitations":"Retrospective observational data; treatment selection and other confounding factors may influence outcomes. Do not generalize this HSA evidence to other cancers. Current public FidoCure material does not establish a Canadian treatment-access pathway, so Canada is not shown for this option."},
    {"id":"bcell-lymphoma-apavac-vaxkit","species":"Dog","countries":["USA","Canada","Europe"],"cancers":["B-cell lymphoma"],"situations":["Newly diagnosed / treatment planning","Tumor or lymph-node tissue available"],"name":"APAVAC / Vaxkit","summary":"Personalized autologous tumor vaccine used alongside chemotherapy for B-cell lymphoma.","access":"USA / Canada / Europe — veterinarian-directed autologous vaccine platform. Vaxkit states that it is the exclusive North American distributor and specifically serves the U.S. and Canada; European access is marketed as APAVAC.","evidence":"Comparative clinical evidence includes a randomized placebo-controlled double-blind study in canine DLBCL and a larger comparative clinical cohort. A published series compared 152 dogs receiving chemotherapy plus APAVAC with 148 dogs receiving chemotherapy alone; reported lymphoma-specific median survival was 401 versus 220 days, and in DLBCL one-year survival was 51% versus 20%.","evidence_level":"Randomized clinical evidence + comparative clinical cohort evidence","sample":"Adequate fresh/autologous tumor or lymph-node tissue is required for vaccine preparation. Confirm collection requirements before biopsy/excision.","travel":"Potentially usable through the treating veterinarian; Vaxkit lists North American distribution from Montreal, Quebec. Confirm logistics before tissue collection.","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC6554898/","access_url":"https://vaxkit.com/","limitations":"Not a contemporary standard-of-care replacement. Evidence should not be extrapolated to solid tumors simply because the platform is commercially offered for other cancers."},
    {"id":"gilvetmab-mct","species":"Dog","countries":["USA"],"cancers":["Mast cell tumor"],"situations":["Stage I–III mast cell tumor"],"name":"Gilvetmab","summary":"Anti-PD-1 immunotherapy available through veterinary oncology specialists for canine mast cell tumor.","access":"USA — available through veterinary oncology specialists under USDA conditional licensure. Canadian specialist sources reviewed in September 2026 state that other immunotherapies beyond melanoma vaccine are not yet available in Canada, so Canada is not shown.","evidence":"Prospective multicenter clinical efficacy data support activity in mast cell tumors. Gilvetmab is included here because it is an officially available regulated veterinary oncology therapy, not because uncontrolled data prove superiority over standard treatment.","evidence_level":"Regulated veterinary therapy + prospective clinical data","sample":"No special tumor-manufacturing sample required; oncologist determines diagnostic/staging requirements.","travel":"Usually through a veterinary oncology specialist in the USA","url":"https://pubmed.ncbi.nlm.nih.gov/42247661/","access_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","limitations":"The published efficacy study was single-arm. This is not evidence that gilvetmab is superior to appropriate surgery, radiation, chemotherapy, or targeted therapy for an individual dog."},
    {"id":"gilvetmab-melanoma","species":"Dog","countries":["USA"],"cancers":["Oral melanoma","Melanoma — other"],"situations":["Stage II–III malignant melanoma"],"name":"Gilvetmab","summary":"Anti-PD-1 immunotherapy available through veterinary oncology specialists for canine malignant melanoma.","access":"USA — available through veterinary oncology specialists under USDA conditional licensure. Canadian specialist sources reviewed in September 2026 state that other immunotherapies beyond melanoma vaccine are not yet available in Canada, so Canada is not shown.","evidence":"Prospective multicenter clinical efficacy data support activity in malignant melanoma. Gilvetmab is included because it is an officially available regulated veterinary oncology therapy.","evidence_level":"Regulated veterinary therapy + prospective clinical data","sample":"No special tumor-manufacturing sample required; oncologist determines diagnostic/staging requirements.","travel":"Usually through a veterinary oncology specialist in the USA","url":"https://pubmed.ncbi.nlm.nih.gov/42247661/","access_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","limitations":"The published efficacy study was single-arm. Do not infer superiority over appropriate local control or other standard treatment from response-rate data alone."},
    {"id":"canada-ect-dog-mct","species":"Dog","countries":["Canada"],"cancers":["Mast cell tumor"],"situations":["Localized cutaneous mast cell tumor","Surgery or radiation is difficult / not preferred"],"name":"Electrochemotherapy (ECT)","summary":"Local electroporation combined with chemotherapy to increase drug delivery into a tumor. Canadian veterinary oncology access is confirmed.","access":"Canada — Toronto Animal Cancer Centre currently offers tumour-specific electroporation/electrochemotherapy for remaining or gross tumor sites.","evidence":"A 2026 cohort of 29 dogs with 39 nonmetastatic cutaneous mast cell tumors treated with ECT alone reported 79% complete remission overall: 100% for low-grade tumors and 45% for high-grade tumors. Outcomes were strongest for low-grade and small-volume disease.","evidence_level":"Clinical cohort evidence","sample":"No special manufacturing sample; pathology and staging are used to determine whether a local tumor is an appropriate ECT target.","travel":"Treatment is performed at an ECT-equipped oncology center; Toronto access is confirmed.","url":"https://academic.oup.com/jvim/article/40/1/aalaf081/8466339","access_url":"https://www.torontoacc.com/services","limitations":"Local treatment, not systemic therapy. Evidence is strongest for localized low-grade cutaneous MCT; high-grade or metastatic disease requires broader oncologic planning."},
    {"id":"canada-ect-dog-melanoma","species":"Dog","countries":["Canada"],"cancers":["Oral melanoma","Melanoma — other"],"situations":["Accessible local tumor","Standard local control is difficult / not feasible"],"name":"Electrochemotherapy (ECT)","summary":"Local electroporation plus chemotherapy for an accessible melanoma tumor site.","access":"Canada — Toronto Animal Cancer Centre currently offers tumour-specific electroporation/electrochemotherapy for remaining or gross tumor sites.","evidence":"Veterinary clinical series support antitumor activity of ECT in canine melanoma, including oral melanoma. Response depends strongly on tumor burden and stage, so ECT is best considered a local-control option rather than systemic melanoma treatment.","evidence_level":"Prospective/clinical series evidence","sample":"No special manufacturing sample; the tumor must be physically accessible to the electrode treatment field.","travel":"Treatment is performed at an ECT-equipped oncology center; Toronto access is confirmed.","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC2082020/","access_url":"https://www.torontoacc.com/services","limitations":"ECT treats the local tumor and does not address occult or established distant metastases. Suitability depends on anatomy, size and stage."},
    {"id":"canada-ect-dog-sts","species":"Dog","countries":["Canada"],"cancers":["Soft tissue sarcoma","Spindle cell sarcoma","Other sarcoma"],"situations":["Gross / measurable local tumor","Incomplete or dirty surgical margins"],"name":"Electrochemotherapy (ECT)","summary":"Local electroporation plus chemotherapy for residual, recurrent or accessible soft-tissue sarcoma, including selected incompletely excised tumors.","access":"Canada — Toronto Animal Cancer Centre currently offers tumour-specific electroporation/electrochemotherapy for remaining or gross tumor sites.","evidence":"ECT has clinical evidence in canine soft-tissue sarcoma. A 2026 comparative study of incompletely excised canine STS reported lower recurrence with surgery plus ECT than surgery alone (33.3% versus 68.2%) and improved time to recurrence, supporting discussion particularly when margins are dirty and further local control is needed.","evidence_level":"Comparative clinical evidence + clinical series","sample":"Pathology/surgical report and current assessment of the local treatment field are important; no special manufacturing sample is required.","travel":"Treatment is performed at an ECT-equipped oncology center; Toronto access is confirmed.","url":"https://pubmed.ncbi.nlm.nih.gov/42421602/","access_url":"https://www.torontoacc.com/services","limitations":"ECT is local control, not systemic sarcoma therapy. Dirty microscopic margins and a gross recurrent tumor are different clinical situations and require oncologist assessment; evidence does not imply that ECT is preferable to feasible definitive surgery or radiation in every case."},
    {"id":"canada-ect-cat-cutaneous-scc","species":"Cat","countries":["Canada"],"cancers":["Squamous cell carcinoma"],"situations":["Cutaneous squamous cell carcinoma","Accessible local SCC"],"name":"Electrochemotherapy (ECT)","summary":"Local bleomycin-based electrochemotherapy for accessible feline cutaneous squamous cell carcinoma.","access":"Canada — Toronto Animal Cancer Centre currently offers tumour-specific electroporation/electrochemotherapy for remaining or gross tumor sites.","evidence":"A 2026 study of 35 cats with histologically confirmed cutaneous SCC treated with bleomycin ECT reported a 100% objective response rate (65.7% complete, 34.3% partial), median progression-free survival of 285 days and median overall survival of 300 days. Tumor size materially affected response and toxicity.","evidence_level":"Clinical cohort evidence","sample":"Histologic confirmation and staging/local assessment; no special manufacturing sample.","travel":"Treatment is performed at an ECT-equipped oncology center; Toronto access is confirmed.","url":"https://pubmed.ncbi.nlm.nih.gov/42349630/","access_url":"https://www.torontoacc.com/services","limitations":"Evidence cited here is for cutaneous SCC, not a blanket recommendation for feline oral SCC. Larger tumors had poorer response and greater toxicity; anatomy and stage matter."},
]

st.markdown("<div style='height:1.45rem'></div>", unsafe_allow_html=True)
st.markdown("<div style='font-size:1.55rem;line-height:1.08;font-weight:700;margin:.1rem 0 .15rem;color:#356fa8'>🧬 Other Options</div>", unsafe_allow_html=True)
st.markdown("<div style='height:.65rem'></div>", unsafe_allow_html=True)
st.write("A short list of non-routine treatment options with enough clinical evidence and current access to be worth discussing with a veterinary oncologist.")
with st.expander("How options qualify"):
    st.write("Experimental, off-label, precision, or research-derived ideas are not shown without meaningful comparative clinical evidence. A regulated veterinary oncology therapy may be included without a comparator when it has prospective clinical efficacy data and a real specialist-access pathway. Options shown to perform worse than an appropriate standard treatment are excluded.")

species=st.selectbox("1. Species",["Dog","Cat"])
country=st.selectbox("2. Country / region",["USA","Canada","Europe"])
country_options=[x for x in OPTIONS if x["species"]==species and country in x.get("countries",[])]
available_cancers=sorted({c for x in country_options for c in x["cancers"]})
cancer=st.selectbox("3. Cancer type",["Select cancer type"]+available_cancers)
if cancer=="Select cancer type":
    if not country_options:
        st.info(f"No {species.lower()}-specific additional option currently passes the evidence and access screen for {country}. Clinical trials and standard oncology care may still be available.")
    else:
        st.caption("Choose a cancer type to continue.")
else:
    cancer_matches=[x for x in country_options if cancer in x["cancers"]]
    situations=sorted({s for x in cancer_matches for s in x["situations"]})
    situation=st.selectbox("4. Clinical situation",["Show all relevant situations"]+situations)
    matches=cancer_matches if situation=="Show all relevant situations" else [x for x in cancer_matches if situation in x["situations"]]
    if not matches:
        st.info("No additional evidence-screened option currently matches this situation. This does not mean there are no standard treatments or clinical trials.")
    else:
        st.success(f"{len(matches)} additional option{'s' if len(matches)!=1 else ''} found to discuss with a veterinary oncologist.")
        for x in matches:
            with st.container(border=True):
                st.subheader(x["name"])
                st.write(x["summary"])
                st.caption("Best match: "+" · ".join(x["situations"]))
                with st.expander("Evidence"):
                    st.markdown(f"**Evidence level:** {x['evidence_level']}")
                    st.write(x["evidence"])
                    st.link_button("Clinical evidence",x["url"],use_container_width=True)
                with st.expander("Access & sample"):
                    st.markdown(f"**Current access:** {x['access']}")
                    st.markdown(f"**Sample:** {x['sample']}")
                    st.markdown(f"**Travel:** {x['travel']}")
                    st.link_button("How to access",x["access_url"],use_container_width=True)
                with st.expander("Limitations"):
                    st.write(x["limitations"])

st.caption("Discussion prompts for a veterinary oncologist, not treatment recommendations or eligibility determinations. Evidence and access can change. Last review: September 4, 2026.")