import streamlit as st

OPTIONS = [
    {"id":"ect-usa-europe","species":"Dog","countries":["USA","Europe"],"cancers":["Mast cell tumor","Soft tissue sarcoma","Squamous cell carcinoma","Oral melanoma","Solid tumor — other"],"situations":["Incomplete surgical margins / scar treatment","Superficial or localized tumor","Surgery difficult or not feasible"],"name":"Veterinary electrochemotherapy (ECT)","summary":"Local treatment combining chemotherapy, commonly bleomycin, with brief electric pulses to increase drug uptake in tumor tissue or a surgical bed.","access":"USA and Europe — available at selected veterinary oncology/referral centers; access is center-specific.","evidence":"Multiple canine and feline studies and a 2024 Veterinary and Comparative Oncology review support ECT for selected tumors; current referral services describe use for incomplete excision and gross superficial/localized tumors.","evidence_level":"Published veterinary clinical evidence + current specialty-center access","sample":"Definitive diagnosis and staging are generally required; no manufacturing sample required.","travel":"Requires a center with an electroporator and trained oncology team; short anesthesia or deep sedation is commonly used.","url":"https://pubmed.ncbi.nlm.nih.gov/38866596/","provider_url":"https://www.rvc.ac.uk/small-animal-vet/specialist-referrals/clinical-services/veterinary-oncology/electrochemotherapy-for-small-animals","access_url":"https://www.rvc.ac.uk/small-animal-vet/specialist-referrals/clinical-services/veterinary-oncology/electrochemotherapy-for-small-animals","access_label":"Example specialist ECT service","contact_note":"Ask an oncologist whether ECT is appropriate and identify the nearest center currently performing it.","limitations":"Local treatment, not systemic metastasis treatment. Suitability and evidence vary by tumor type, size, location and treatment setting."},
    {"id":"oral-melanoma-oncept","species":"Dog","countries":["USA"],"cancers":["Oral melanoma"],"situations":["Stage II–III after local disease control","Adjuvant immunotherapy"],"name":"ONCEPT Canine Melanoma Vaccine, DNA","summary":"USDA-licensed DNA immunotherapy used as an adjunct after local control of stage II or III canine oral melanoma.","access":"USA — supplied to approved veterinary practices; manufacturer has a current purchase-application pathway.","evidence":"Licensed indication is to aid in extending survival after local disease control. Published clinical evidence exists, while later literature has raised uncertainty about magnitude of benefit.","evidence_level":"USDA-licensed veterinary cancer immunotherapy + mixed clinical evidence","sample":"No personalized manufacturing sample required; local disease control and staging are prerequisites for labeled use.","travel":"Administered through practices able to obtain and deliver ONCEPT using the VET JET system.","url":"https://animalhealth.boehringer-ingelheim.com/pets/canine/products/therapeutics/oncept","provider_url":"https://animalhealth.boehringer-ingelheim.com/pets/canine/products/therapeutics/oncept","access_url":"https://animalhealth.boehringer-ingelheim.com/pets/canine/products/therapeutics/oncept","access_label":"ONCEPT product & access","contact_note":"After local control, ask the oncologist whether ONCEPT is appropriate and whether their practice can obtain/administer it.","limitations":"Adjunctive treatment, not local tumor control. Licensed status does not prove benefit for every patient."},
    {"id":"lymphoma-laverdia","species":"Dog","countries":["USA"],"cancers":["Lymphoma"],"situations":["Lymphoma treatment planning","Oral / at-home treatment option"],"name":"LAVERDIA (verdinexor)","summary":"Oral selective inhibitor of nuclear export for canine lymphoma, administered at home under veterinary prescription.","access":"USA — FDA fully approved for canine lymphoma; full approval replaced earlier conditional approval in 2026.","evidence":"FDA granted full approval after effectiveness data required to convert the earlier conditional approval were generated.","evidence_level":"FDA fully approved veterinary anticancer drug","sample":"No manufacturing sample required; confirmed diagnosis and monitoring are required.","travel":"Oral at-home administration; monitoring visits remain necessary.","url":"https://www.fda.gov/animal-veterinary/cvm-updates/fda-grants-full-approval-first-oral-treatment-lymphoma-dogs","provider_url":"https://www.anivive.com/","access_url":"https://www.fda.gov/animal-veterinary/cvm-updates/fda-grants-full-approval-first-oral-treatment-lymphoma-dogs","access_label":"FDA approval information","contact_note":"Discuss fit with the treating veterinarian/oncologist and review cytotoxic-handling instructions before home dosing.","limitations":"Response rates may be lower than standard multidrug chemotherapy in many lymphomas. Cytotoxic handling precautions and adverse-effect monitoring apply."},
    {"id":"lymphoma-tanovea","species":"Dog","countries":["USA"],"cancers":["Lymphoma"],"situations":["Lymphoma treatment planning","Relapsed / rescue treatment"],"name":"TANOVEA (rabacfosadine)","summary":"FDA fully approved intravenous antineoplastic drug specifically indicated for canine lymphoma.","access":"USA — prescription oncology treatment administered as a 30-minute IV infusion, generally every 3 weeks for up to five treatments.","evidence":"FDA approval and prospective canine lymphoma studies support antitumor activity.","evidence_level":"FDA fully approved veterinary anticancer drug","sample":"No manufacturing sample required; lymphoma diagnosis and clinical assessment are required.","travel":"Given in a veterinary clinic as an IV infusion.","url":"https://my.elanco.com/us/tanovea","provider_url":"https://my.elanco.com/us/tanovea","access_url":"https://my.elanco.com/us/tanovea","access_label":"TANOVEA information","contact_note":"Discuss with a veterinary oncologist, especially for rescue therapy or an alternative lymphoma regimen.","limitations":"Can cause GI toxicity, neutropenia, dermatologic adverse effects and potentially life-threatening pulmonary fibrosis."},
    {"id":"mct-stelfonta","species":"Dog","countries":["USA","Europe"],"cancers":["Mast cell tumor"],"situations":["Non-metastatic injectable mast cell tumor","Surgery unsuitable / local treatment alternative"],"name":"STELFONTA (tigilanol tiglate)","summary":"Intratumoral anticancer treatment for eligible non-metastatic canine mast cell tumors.","access":"USA — FDA-approved with a current Virbac veterinarian locator. Europe — centrally authorized for eligible non-metastatic canine mast cell tumors.","evidence":"Regulatory approval is supported by prospective efficacy and safety data.","evidence_level":"FDA-approved / EU-authorized veterinary anticancer drug","sample":"Confirmed diagnosis and staging; no manufacturing sample required.","travel":"Administered intratumorally by a veterinarian; availability depends on clinic and country.","url":"https://www.ema.europa.eu/en/medicines/veterinary/EPAR/stelfonta","provider_url":"https://vet-us.virbac.com/stelfonta","access_url":"https://us.virbac.com/stelfonta-find-a-vet","access_label":"Find a STELFONTA veterinarian","contact_phone":"800-338-3659","contact_note":"Ask whether tumor location, volume and metastatic status meet the indication.","limitations":"Local therapy only; not systemically active or for metastatic disease. Wound formation is expected and mast-cell degranulation can cause severe reactions."},
    {"id":"osa-elias-eci","species":"Dog","countries":["USA"],"cancers":["Osteosarcoma"],"situations":["After amputation / adjuvant treatment planning"],"name":"ELIAS Cancer Immunotherapy (ECI)","summary":"USDA-approved autologous vaccine-enhanced adoptive T-cell therapy for canine osteosarcoma after amputation.","access":"USA — veterinarian-directed ELIAS Cancer Immunotherapy (ECI), distributed under a USDA Autologous Prescription Product license. The treating veterinary team coordinates tumor collection, personalized vaccine preparation, vaccination and autologous T-cell infusion.","evidence":"USDA licensure is supported by canine safety and efficacy studies. ELIAS also reported an 18-month 2026 ASCENT analysis evaluating ECI after amputation with a single carboplatin dose; this newer combination analysis was presented at the 2026 VCS/VSSO conference and should be interpreted as conference-level evidence rather than a completed peer-reviewed randomized comparison.","evidence_level":"USDA-approved autologous prescription product + canine clinical evidence","sample":"Autologous tumor material is required to manufacture the personalized vaccine component; coordinate with an ECI-trained veterinary team before or at amputation so collection and shipping requirements are met.","travel":"Treatment can be coordinated through veterinary practices that offer ECI; availability is practice-dependent. Contact ELIAS or an oncology team before surgery to confirm logistics.","url":"https://www.aphis.usda.gov/sites/default/files/2025-04/691-95a750.pdf","provider_url":"https://eliasanimalhealth.com/","access_url":"https://eliasanimalhealth.com/","access_label":"ELIAS access information","contact_note":"Ask the veterinary oncologist whether ECI is appropriate before amputation/tumor disposal because autologous tumor material is part of manufacturing. ELIAS provides practice access information for veterinarians.","limitations":"This is a regulated personalized therapy, not evidence that ECI is superior to every contemporary osteosarcoma protocol. It requires amputation and usable autologous tumor material. The 2026 ASCENT combination findings are an interim/conference analysis and should not be overstated as definitive comparative evidence."},
    {"id":"hsa-fidocure-genomic-guidance","species":"Dog","countries":["USA"],"cancers":["Hemangiosarcoma"],"situations":["Splenic hemangiosarcoma"],"name":"FidoCure genomic guidance","summary":"Tumor genomic profiling to guide targeted therapy after splenic hemangiosarcoma diagnosis.","access":"USA — ordered and managed through the treating veterinarian/oncologist; FFPE tumor tissue can be used.","evidence":"Retrospective real-world comparative evidence. A 2025 Scientific Reports study analyzed 508 dogs with splenic hemangiosarcoma; treatment records were available for 421 dogs from 257 U.S. veterinary practices. In stage II disease, median overall survival was 249 days with chemotherapy plus targeted therapy versus 141 days with chemotherapy; in stage III, 139 versus 89 days.","evidence_level":"Comparative real-world clinical evidence","sample":"FFPE tumor tissue / pathology material","travel":"No research-center travel inherently required","url":"https://www.nature.com/articles/s41598-025-89862-9","provider_url":"https://fidocure.com/","access_url":"https://fidocure.com/pet-parents/","access_label":"Start with FidoCure","contact_email":"support@fidocure.com","contact_phone":"855-701-8047","contact_note":"Pet owners can start on FidoCure's current Pet Parents page or ask their veterinarian/oncologist to enroll the patient. FidoCure works directly with the veterinary care team.","limitations":"Retrospective observational data; treatment selection and other confounding factors may influence outcomes. Do not generalize this HSA evidence to other cancers. Current public FidoCure material does not establish a Canadian treatment-access pathway, so Canada is not shown for this option."},
    {"id":"bcell-lymphoma-aurelius-act","species":"Dog","countries":["USA"],"cancers":["B-cell lymphoma"],"situations":["After initial chemotherapy / in clinical remission"],"name":"Aurelius adoptive T-cell therapy","summary":"Autologous adoptive T-cell immunotherapy for canine B-cell lymphoma. T cells are collected from the dog’s blood, expanded and activated by Aurelius, then shipped back for intravenous infusion.","access":"USA — veterinarian-directed experimental treatment from Aurelius Biotherapeutics in Bellingham, Washington. The treating veterinarian sends a 20 mL chilled blood sample; expanded cells are returned for infusion. Aurelius states USDA licensure is pending.","evidence":"Published canine clinical evidence supports adoptive T-cell transfer after chemotherapy in B-cell lymphoma. Aurelius also supplied expanded autologous T cells used in a published canine high-grade B-cell lymphoma transplant/ACT series. Current Aurelius material continues to offer the treatment while explicitly describing it as experimental.","evidence_level":"Published canine clinical evidence + current experimental access","sample":"20 mL peripheral blood in purple-top tubes, shipped chilled overnight; confirm timing and eligibility with Aurelius before collection.","travel":"The blood sample can be sent by the treating veterinarian and the expanded cells shipped back for infusion, so travel to Bellingham is not inherently required for the standard ACT service. Confirm case-specific logistics directly.","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC8688351/","provider_url":"https://aureliusbio.com/","access_url":"https://aureliusbio.com/veterinarians/","access_label":"Aurelius access & protocol","contact_email":"info@AureliusBio.com","contact_phone":"360-734-0720","contact_note":"Best suited after the first chemotherapy course when the dog is in clinical remission. The veterinarian should contact Aurelius with the medical history before blood collection. Perseus Foundation also maintains the current T-cell infusion project information.","limitations":"Experimental therapy; safety and efficacy have not been established for USDA licensure and licensure is pending. It should not replace indicated lymphoma chemotherapy. Published evidence is limited and does not establish superiority over contemporary standard protocols for every patient."},
    {"id":"bcell-lymphoma-apavac-vaxkit","species":"Dog","countries":["USA","Canada","Europe"],"cancers":["B-cell lymphoma"],"situations":["Newly diagnosed / treatment planning","Tumor or lymph-node tissue available"],"name":"APAVAC / Vaxkit","summary":"Personalized autologous tumor vaccine used alongside chemotherapy for B-cell lymphoma.","access":"USA / Canada / Europe — veterinarian-directed autologous vaccine platform. Vaxkit is the North American distributor for the U.S. and Canada; European access is through Hastim under the APAVAC name.","evidence":"Comparative clinical evidence includes a randomized placebo-controlled double-blind study in canine DLBCL and a larger comparative clinical cohort. A published series compared 152 dogs receiving chemotherapy plus APAVAC with 148 dogs receiving chemotherapy alone; reported lymphoma-specific median survival was 401 versus 220 days, and in DLBCL one-year survival was 51% versus 20%.","evidence_level":"Randomized clinical evidence + comparative clinical cohort evidence","sample":"Adequate fresh/autologous tumor or lymph-node tissue is required for vaccine preparation. Confirm collection requirements before biopsy/excision.","travel":"Potentially usable through the treating veterinarian. Confirm logistics before tissue collection.","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC6554898/","provider_url":"https://vaxkit.com/","access_url":"https://vaxkit.com/","access_label":"Vaxkit access & contact","contact_email":"info@vaxkit.com","contact_email_europe":"contact@hastim.fr","contact_note":"USA/Canada: contact Vaxkit for access and ordering logistics. Europe: contact Hastim directly for APAVAC. Confirm tissue collection requirements before biopsy/excision.","limitations":"Not a contemporary standard-of-care replacement. Evidence should not be extrapolated to solid tumors simply because the platform is commercially offered for other cancers."},
    {"id":"gilvetmab-mct","species":"Dog","countries":["USA"],"cancers":["Mast cell tumor"],"situations":["Stage I–III mast cell tumor"],"name":"Gilvetmab","summary":"Anti-PD-1 immunotherapy available through veterinary oncology specialists for canine mast cell tumor.","access":"USA — available through specialists practicing veterinary oncology under USDA conditional licensure.","evidence":"Prospective multicenter clinical efficacy data support activity in mast cell tumors.","evidence_level":"Regulated veterinary therapy + prospective clinical data","sample":"No special tumor-manufacturing sample required; oncologist determines diagnostic/staging requirements.","travel":"Treatment is administered intravenously in a veterinary clinic; Merck's current Gilvetmab page directs owners to veterinary oncology specialists.","url":"https://pubmed.ncbi.nlm.nih.gov/42247661/","provider_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_label":"Gilvetmab access / oncologist","contact_phone":"800-521-5767","contact_note":"Gilvetmab is supplied through veterinary oncology specialists. Use Merck's current Gilvetmab page for the specialist-access route; Merck Animal Health Customer Service can answer U.S. product/access questions.","limitations":"The published efficacy study was single-arm. This is not evidence that gilvetmab is superior to appropriate surgery, radiation, chemotherapy, or targeted therapy for an individual dog."},
    {"id":"gilvetmab-melanoma","species":"Dog","countries":["USA"],"cancers":["Oral melanoma","Melanoma — other"],"situations":["Stage II–III malignant melanoma"],"name":"Gilvetmab","summary":"Anti-PD-1 immunotherapy available through veterinary oncology specialists for canine malignant melanoma.","access":"USA — available through specialists practicing veterinary oncology under USDA conditional licensure.","evidence":"Prospective multicenter clinical efficacy data support activity in malignant melanoma.","evidence_level":"Regulated veterinary therapy + prospective clinical data","sample":"No special tumor-manufacturing sample required; oncologist determines diagnostic/staging requirements.","travel":"Treatment is administered intravenously in a veterinary clinic; Merck's current Gilvetmab page directs owners to veterinary oncology specialists.","url":"https://pubmed.ncbi.nlm.nih.gov/42247661/","provider_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_label":"Gilvetmab access / oncologist","contact_phone":"800-521-5767","contact_note":"Gilvetmab is supplied through veterinary oncology specialists. Use Merck's current Gilvetmab page for the specialist-access route; Merck Animal Health Customer Service can answer U.S. product/access questions.","limitations":"The published efficacy study was single-arm. Do not infer superiority over appropriate local control or other standard treatment from response-rate data alone."},
    {"id":"torigen-vimclara-cat-solid-tumors","species":"Cat","countries":["USA"],"cancers":["Adenocarcinoma","Solid tumor — other"],"situations":["Tumor tissue available after biopsy or surgery","Post-surgical treatment planning"],"name":"Torigen VimClara autologous cancer vaccine","summary":"Personalized autologous immunotherapy prepared in-clinic from the cat’s own tumor tissue using the VimClara veterinary kit.","access":"USA — veterinarian-directed point-of-care treatment. Ask the treating veterinarian/oncologist to contact Torigen before tissue collection when possible; Torigen supplies VimClara kits and clinic training for dogs, cats and horses.","evidence":"Published feline data primarily establish safety rather than anticancer efficacy. Torigen also cites broader veterinary autologous cancer-vaccine literature, but efficacy for an individual feline tumor type remains uncertain.","evidence_level":"Available veterinary advanced treatment; limited tumor-specific efficacy evidence","sample":"Approximately 5 g of fresh, unfixed tumor tissue is requested in Torigen's current owner/veterinarian material. Confirm collection, storage and timing requirements with Torigen before biopsy/surgery when possible, and before tissue is discarded or fixed.","travel":"May be prepared and administered through a participating/trained veterinary clinic; a university trial center is not inherently required.","url":"https://clinics.torigen.com/hubfs/Torigen%20Literature%202025/VimClara-Only%20Distributor%20Detailer.pdf","provider_url":"https://torigen.com/","access_url":"https://torigen.com/","access_label":"Torigen website","contact_email":"info@torigen.com","contact_phone":"860-519-9956","contact_note":"Veterinarian/clinic should contact Torigen directly to discuss the case, order a VimClara kit and arrange training.","limitations":"VimClara is a veterinary-use point-of-care kit, not a licensed cancer vaccine or a clinical trial. Evidence of efficacy in cats and for specific tumor types such as adenocarcinoma is limited. It should not be presented as a proven replacement for indicated surgery, chemotherapy or radiation. Torigen states it can be used alongside chemotherapy or radiation when clinically appropriate."},
]

def contact_line(x, country):
    parts=[]
    if x.get("provider_url"): parts.append(f"🌐 [Official website]({x['provider_url']})")
    if x.get("contact_email"): parts.append(f"✉️ [{x['contact_email']}](mailto:{x['contact_email']})")
    if x.get("contact_email_europe") and country=="Europe": parts.append(f"✉️ [{x['contact_email_europe']}](mailto:{x['contact_email_europe']})")
    if x.get("contact_phone"): parts.append(f"☎️ [{x['contact_phone']}](tel:{x['contact_phone'].replace('-', '')})")
    return "    ".join(parts)

st.markdown("<div style='height:1.45rem'></div>", unsafe_allow_html=True)
st.markdown("<div style='font-size:1.55rem;line-height:1.08;font-weight:700;margin:.1rem 0 .15rem;color:#356fa8'>🧬 Other Options</div>", unsafe_allow_html=True)
st.markdown("<div style='height:.65rem'></div>", unsafe_allow_html=True)
st.write("A short list of non-routine treatment options with current access and enough evidence or clinical relevance to be worth discussing with a veterinary oncologist.")
with st.expander("How options qualify"):
    st.write("This section can include regulated, experimental, off-label, precision, or personalized anticancer treatments with a real current access pathway. The evidence level and limitations are shown explicitly; inclusion does not mean the treatment is proven superior to standard care.")

species=st.selectbox("1. Species",["Dog","Cat"])
country=st.selectbox("2. Country / region",["USA","Canada","Europe"])
country_options=[x for x in OPTIONS if x["species"]==species and country in x.get("countries",[])]
available_cancers=sorted({c for x in country_options for c in x["cancers"]})
cancer=st.selectbox("3. Cancer type",["Select cancer type"]+available_cancers)
if cancer=="Select cancer type":
    if not country_options:
        st.info(f"No {species.lower()}-specific additional option currently passes the evidence and access screen for {country}. Clinical trials and standard oncology care may still be available.")
    else:
        st.caption("Choose a cancer type to continue.")
else:
    cancer_matches=[x for x in country_options if cancer in x["cancers"]]
    situations=sorted({s for x in cancer_matches for s in x["situations"]})
    situation=st.selectbox("4. Clinical situation",["Show all relevant situations"]+situations)
    matches=cancer_matches if situation=="Show all relevant situations" else [x for x in cancer_matches if situation in x["situations"]]
    if not matches:
        st.info("No additional evidence-screened option currently matches this situation. This does not mean there are no standard treatments or clinical trials.")
    else:
        st.success(f"{len(matches)} additional option{'s' if len(matches)!=1 else ''} found to discuss with a veterinary oncologist.")
        for x in matches:
            with st.container(border=True):
                st.subheader(x["name"])
                st.write(x["summary"])
                st.caption("Best match: "+" · ".join(x["situations"]))
                contacts=contact_line(x,country)
                if contacts:
                    st.markdown("**Contact / next step**")
                    st.markdown(contacts)
                with st.expander("Evidence"):
                    st.markdown(f"**Evidence level:** {x['evidence_level']}")
                    st.write(x["evidence"])
                    st.link_button("Clinical evidence",x["url"],use_container_width=True)
                with st.expander("Access & sample"):
                    st.markdown(f"**Current access:** {x['access']}")
                    if x.get("contact_note"):
                        st.markdown(f"**Next step:** {x['contact_note']}")
                    if contacts:
                        st.markdown("**Contact:** "+contacts)
                    st.markdown(f"**Sample:** {x['sample']}")
                    st.markdown(f"**Travel:** {x['travel']}")
                    if x.get("access_url"):
                        st.link_button(x.get("access_label","How to access"),x["access_url"],use_container_width=True)
                with st.expander("Limitations"):
                    st.write(x["limitations"])

st.caption("Discussion prompts for a veterinary oncologist, not treatment recommendations or eligibility determinations. Evidence and access can change. Last review: September 6, 2026.")