import streamlit as st
from pathlib import Path
import json, math, urllib.request

OPTIONS = [
    {"id":"vidium-searchlight-genomic-guidance","species":"Dog","countries":["USA","Canada","Europe"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Unclear or limited treatment options","Tumor tissue or FNA material available"],"name":"Vidium SearchLight DNA","summary":"Tumor genomic profiling of 120 cancer-related genes to identify diagnostic, prognostic and therapeutic biomarkers and potential mutation-matched drugs.","access":"Veterinarian-ordered genomic test. Vidium currently accepts international orders; treatment is selected and prescribed separately by the veterinary team.","evidence":"SearchLight DNA reports identify mutation-associated treatment options and can also flag therapies predicted to be ineffective or potentially harmful. Vidium provides targeted-drug monographs and complimentary veterinarian consultations for SearchLight DNA cases.","evidence_level":"Commercial targeted tumor sequencing + treatment guidance; strength of evidence varies by biomarker and drug","sample":"FNA, FFPE tissue, or fresh-frozen tumor sample.","travel":"No research-center travel is inherently required for testing; the sample is submitted by the veterinary team. Any recommended treatment is obtained separately.","url":"https://vidiumah.com/searchlight-dna/","provider_url":"https://vidiumah.com/","access_url":"https://vidiumah.com/searchlight-dna/","access_label":"SearchLight DNA information","contact_phone":"833-794-0318","limitations":"This is a genomic diagnostic and treatment-guidance service, not a treatment provider. Some treatment associations rely partly on human oncology or limited canine evidence, and a genomic match does not establish clinical benefit for an individual dog."},
    {"id":"vetomics-cgp-genomic-guidance","species":"Dog","countries":["USA"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Few standard treatment options remain","Tumor tissue or FNA material available"],"name":"VetOmics Canine CGP","summary":"Whole-exome tumor genomic profiling across 20,257 coding genes, with genomics-guided treatment recommendations.","access":"USA — ordered through a veterinarian or veterinary hospital. VetOmics lists the Canine CGP price as $900 to hospitals/veterinarians; the hospital may add its own markup. Treatment is separate.","evidence":"VetOmics provides clinical interpretation and potential therapeutic recommendations from tumor genomic findings. Actionability and canine-specific evidence vary by finding.","evidence_level":"Commercial comprehensive genomic profiling + treatment guidance; actionability varies by finding","sample":"FFPE tumor tissue, FNA slides, or fresh-frozen tumor tissue; requirements vary by specimen type.","travel":"No research-center travel is inherently required for testing; the treating veterinarian coordinates sample submission. Any recommended treatment is obtained separately.","url":"https://vetomicsanimalhealth.com/our-approach/","provider_url":"https://vetomicsanimalhealth.com/","access_url":"https://vetomicsanimalhealth.com/order/","access_label":"Order Canine CGP","contact_email":"CustomerCare@VetomicsAnimalHealth.com","limitations":"This is a genomic testing and treatment-guidance service, not a treatment provider. A genomic match does not establish that a recommended therapy will work in an individual dog; canine-specific evidence is limited for some matches."},
    {"id":"fidocure-genomic-guidance","species":"Dog","countries":["USA"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Few standard treatment options remain","Tumor tissue available"],"name":"FidoCure genomic guidance","summary":"Tumor genomic profiling with precision-treatment guidance for dogs with cancer.","access":"USA — ordered and managed through the treating veterinarian/oncologist; treatment and medications are separate from testing.","evidence":"FidoCure provides tumor genomic profiling and treatment guidance across canine cancers. Cancer-specific clinical evidence varies; published real-world comparative evidence is available for splenic hemangiosarcoma.","evidence_level":"Commercial precision-oncology service + cancer-specific real-world clinical evidence","sample":"Tumor pathology material; confirm current specimen requirements with FidoCure before submission.","travel":"No research-center travel inherently required.","url":"https://www.nature.com/articles/s41598-025-89862-9","provider_url":"https://fidocure.com/","access_url":"https://fidocure.com/pet-parents/","access_label":"Start with FidoCure","contact_email":"support@fidocure.com","contact_phone":"855-701-8047","limitations":"This is genomic testing and treatment guidance, not a guarantee that a matched therapy will be effective. The strongest published outcome evidence is cancer-specific and should not be generalized to every tumor type."},
    {"id":"vidium-searchlight-dna","species":"Dog","countries":["USA"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Few standard treatment options remain","Tumor tissue or FNA material available"],"name":"Vidium SearchLight DNA","summary":"Tumor genomic profiling of 120 cancer-related genes with clinical interpretation and potential matched-drug guidance.","access":"USA — veterinarian-directed commercial genomic testing. Treatment and medications are obtained separately.","evidence":"SearchLight DNA reports genomic alterations with diagnostic, prognostic, and potential therapeutic interpretation. Published clinical-utility data exist, but actionability and canine-specific treatment evidence vary by finding.","evidence_level":"Commercial genomic profiling + published veterinary clinical-utility evidence","sample":"FFPE tissue, FNA/cytology material, or fresh/frozen tumor material may be accepted; confirm current submission requirements with Vidium.","travel":"No research-center travel inherently required for testing; the treating veterinarian coordinates submission and any resulting treatment.","url":"https://pubmed.ncbi.nlm.nih.gov/36862546/","provider_url":"https://vidiumah.com/","access_url":"https://vidiumah.com/searchlight-dna/","access_label":"SearchLight DNA information","limitations":"This is a genomic testing and treatment-guidance service, not a treatment provider. A reported drug match does not establish efficacy for an individual dog, and canine-specific evidence varies by alteration and drug."},
    {"id":"bcell-lymphoma-apavac-vaxkit","species":"Dog","countries":["USA","Canada","Europe"],"cancers":["B-cell lymphoma"],"situations":["Newly diagnosed / treatment planning","Tumor or lymph-node tissue available"],"name":"APAVAC / Vaxkit","summary":"Personalized autologous tumor vaccine used alongside chemotherapy for B-cell lymphoma.","access":"USA / Canada / Europe — veterinarian-directed autologous vaccine platform.","evidence":"Comparative clinical evidence includes randomized and cohort data.","evidence_level":"Randomized clinical evidence + comparative clinical cohort evidence","sample":"Adequate fresh/autologous tumor or lymph-node tissue is required.","travel":"Potentially usable through the treating veterinarian.","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC6554898/","provider_url":"https://vaxkit.com/","access_url":"https://vaxkit.com/","access_label":"Vaxkit access & contact","contact_email":"info@vaxkit.com","limitations":"Not a contemporary standard-of-care replacement."},
    {"id":"bcell-lymphoma-aurelius-act","species":"Dog","countries":["USA"],"cancers":["B-cell lymphoma"],"situations":["After initial chemotherapy / in clinical remission"],"name":"Aurelius adoptive T-cell therapy","summary":"Autologous adoptive T-cell immunotherapy for canine B-cell lymphoma. T cells are collected from the dog’s blood, expanded and activated by Aurelius, then shipped back for intravenous infusion.","access":"USA — veterinarian-directed experimental treatment from Aurelius Biotherapeutics in Bellingham, Washington.","evidence":"Published canine clinical evidence supports adoptive T-cell transfer after chemotherapy in B-cell lymphoma.","evidence_level":"Published canine clinical evidence + current experimental access","sample":"20 mL peripheral blood in purple-top tubes, shipped chilled overnight; confirm timing and eligibility with Aurelius before collection.","travel":"The blood sample can be sent by the treating veterinarian and the expanded cells shipped back for infusion.","url":"https://pmc.ncbi.nlm.nih.gov/articles/PMC8688351/","provider_url":"https://aureliusbio.com/","access_url":"https://aureliusbio.com/veterinarians/","access_label":"Aurelius access & protocol","contact_email":"info@AureliusBio.com","contact_phone":"360-734-0720","limitations":"Experimental therapy; USDA licensure is pending."},
    {"id":"osa-elias-eci","species":"Dog","countries":["USA"],"cancers":["Osteosarcoma"],"situations":["After amputation / adjuvant treatment planning"],"name":"ELIAS Cancer Immunotherapy (ECI)","summary":"USDA-approved autologous vaccine-enhanced adoptive T-cell therapy for canine osteosarcoma after amputation.","access":"USA — veterinarian-directed ELIAS Cancer Immunotherapy (ECI).","evidence":"USDA licensure is supported by canine safety and efficacy studies.","evidence_level":"USDA-approved autologous prescription product + canine clinical evidence","sample":"Autologous tumor material is required; coordinate before or at amputation.","travel":"Treatment can be coordinated through veterinary practices that offer ECI.","url":"https://www.aphis.usda.gov/sites/default/files/2025-04/691-95a750.pdf","provider_url":"https://eliasanimalhealth.com/","access_url":"https://eliasanimalhealth.com/","access_label":"ELIAS access information","limitations":"Requires amputation and usable autologous tumor material."},
    {"id":"gilvetmab-mct","species":"Dog","countries":["USA"],"cancers":["Mast cell tumor"],"situations":["Stage I–III mast cell tumor"],"name":"Gilvetmab","summary":"Anti-PD-1 immunotherapy available through veterinary oncology specialists for canine mast cell tumor.","access":"USA — available through specialists practicing veterinary oncology under USDA conditional licensure.","evidence":"Prospective multicenter clinical efficacy data support activity in mast cell tumors.","evidence_level":"Regulated veterinary therapy + prospective clinical data","sample":"No special tumor-manufacturing sample required.","travel":"Treatment is administered intravenously in a veterinary clinic.","url":"https://pubmed.ncbi.nlm.nih.gov/42247661/","provider_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_label":"Gilvetmab access / oncologist","contact_phone":"800-521-5767","limitations":"The published efficacy study was single-arm."},
    {"id":"gilvetmab-melanoma","species":"Dog","countries":["USA"],"cancers":["Oral melanoma","Melanoma — other"],"situations":["Stage II–III malignant melanoma"],"name":"Gilvetmab","summary":"Anti-PD-1 immunotherapy available through veterinary oncology specialists for canine malignant melanoma.","access":"USA — available through specialists practicing veterinary oncology under USDA conditional licensure.","evidence":"Prospective multicenter clinical efficacy data support activity in malignant melanoma.","evidence_level":"Regulated veterinary therapy + prospective clinical data","sample":"No special tumor-manufacturing sample required.","travel":"Treatment is administered intravenously in a veterinary clinic.","url":"https://pubmed.ncbi.nlm.nih.gov/42247661/","provider_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_url":"https://www.merck-animal-health-usa.com/hub/gilvetmab/","access_label":"Gilvetmab access / oncologist","contact_phone":"800-521-5767","limitations":"The published efficacy study was single-arm."},
    {"id":"thyroid-i131","species":"Dog","countries":["USA"],"cancers":["Thyroid carcinoma","Thyroid tumor / carcinoma"],"situations":["Non-resectable or invasive thyroid carcinoma","Residual disease after surgery","Metastatic thyroid carcinoma","Iodine-avid tumor"],"name":"Radioactive iodine (I-131)","summary":"Systemic radioiodine therapy for canine thyroid carcinoma that concentrates iodine; it may be used for invasive, non-resectable, residual, or metastatic disease when scintigraphy indicates useful uptake.","access":"USA — available at a limited number of nuclear-medicine centers, including University of Missouri Veterinary Health Center and Advanced Veterinary Medical Imaging (AVMI), Tustin, California.","evidence":"Published canine case series support meaningful tumor control and prolonged survival in selected dogs with non-resectable or invasive thyroid carcinoma.","evidence_level":"Published canine clinical evidence + current specialty-center access","sample":"No tumor-manufacturing sample required. Thyroid scintigraphy is generally used to assess uptake/candidacy before treatment.","travel":"Requires treatment at a licensed veterinary nuclear-medicine facility and a radiation-safety hospitalization period after I-131.","url":"https://www.avmi.net/services/radiotherapy/thyroid-carcinoma/radioiodine-for-thyroid-carcinoma/","provider_url":"https://vhc.missouri.edu/small-animal-hospital/oncology/cancer-treatment/radiation-therapy/","limitations":"Not every canine thyroid carcinoma takes up enough iodine for treatment. Recent iodinated CT contrast can interfere with uptake; candidacy and timing must be determined by the treating center."},
    {"id":"thyroid-toceranib","species":"Dog","countries":["USA"],"cancers":["Thyroid carcinoma","Thyroid tumor / carcinoma"],"situations":["Non-resectable thyroid carcinoma","Metastatic disease","Progressive disease / systemic treatment planning"],"name":"Toceranib (Palladia)","summary":"Off-label targeted tyrosine-kinase inhibitor used by veterinary oncologists as a systemic treatment option for selected dogs with thyroid carcinoma.","access":"USA — prescription treatment managed by a veterinary oncologist; no single research center is required.","evidence":"A multicenter retrospective study of 42 dogs with thyroid carcinoma reported clinical benefit in both treatment-naive and previously treated dogs.","evidence_level":"Published multicenter retrospective canine clinical evidence","sample":"No special tumor-manufacturing sample required.","travel":"Usually managed through the treating veterinary oncologist with routine laboratory and clinical monitoring.","url":"https://pubmed.ncbi.nlm.nih.gov/32012432/","limitations":"Off-label for canine thyroid carcinoma; retrospective evidence rather than a randomized trial. Response is not guaranteed and adverse effects require veterinary monitoring."},
]

def contact_line(x, country):
    parts=[]
    if x.get("provider_url"): parts.append(f"🌐 [Official website]({x['provider_url']})")
    if x.get("contact_email"): parts.append(f"✉️ [{x['contact_email']}](mailto:{x['contact_email']})")
    if x.get("contact_phone"): parts.append(f"☎️ [{x['contact_phone']}](tel:{x['contact_phone'].replace('-', '')})")
    return "    ".join(parts)

def miles(a,b,c,d):
    r=3958.8;p1=math.radians(a);p2=math.radians(c);dp=math.radians(c-a);dl=math.radians(d-b)
    q=math.sin(dp/2)**2+math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*r*math.asin(math.sqrt(q))

def zip_coords(z):
    for cc in ("us","ca"):
        try:
            req=urllib.request.Request(f"https://api.zippopotam.us/{cc}/{z}",headers={"User-Agent":"VetCancerTreatmentFinder/1.0"})
            with urllib.request.urlopen(req,timeout=5) as resp:data=json.load(resp)
            p=data["places"][0];return float(p["latitude"]),float(p["longitude"]),p.get("place name",""),p.get("state abbreviation",p.get("state",""))
        except Exception:pass
    return None

st.markdown("<div style='font-size:1.55rem;line-height:1.08;font-weight:700;margin:.1rem 0 .15rem;color:#356fa8'>💊 More Treatment Options</div>", unsafe_allow_html=True)
st.markdown("<div style='height:.65rem'></div>", unsafe_allow_html=True)
st.write("Explore treatment access beyond standard clinical trials.")

# Calm, card-like route buttons rather than questionnaire-style radio controls.
st.markdown("""<style>
/* Route buttons: target Streamlit key classes so mobile stacking keeps distinct shades. */
.st-key-route_ect button {background-color:#e7f2fa !important;border-color:#bfd8e9 !important;color:#285b7a !important;}
.st-key-route_advanced button {background-color:#d6e9f6 !important;border-color:#a9cce3 !important;color:#245674 !important;}
.st-key-route_compassionate button {background-color:#c5dfef !important;border-color:#91bdd8 !important;color:#1f4f6c !important;}
.st-key-route_ect button,.st-key-route_advanced button,.st-key-route_compassionate button {border-radius:12px !important;min-height:3.25rem !important;font-weight:500 !important;}
.st-key-route_ect button:hover,.st-key-route_advanced button:hover,.st-key-route_compassionate button:hover {filter:brightness(.97);}
</style>""",unsafe_allow_html=True)
if "treatment_option_route" not in st.session_state: st.session_state.treatment_option_route="⚡ Electrochemotherapy (ECT)"
c1,c2,c3=st.columns(3)
with c1:
 if st.button("⚡ Electrochemotherapy (ECT)",use_container_width=True,key="route_ect"): st.session_state.treatment_option_route="⚡ Electrochemotherapy (ECT)"
with c2:
 if st.button("🧬 Advanced / Novel Treatments",use_container_width=True,key="route_advanced"): st.session_state.treatment_option_route="🧬 Advanced / Novel Treatments"
with c3:
 if st.button("🧪 Compassionate / Expanded Access",use_container_width=True,key="route_compassionate"): st.session_state.treatment_option_route="🧪 Compassionate / Expanded Access"
route=st.session_state.treatment_option_route

if route=="⚡ Electrochemotherapy (ECT)":
 with st.expander("⚡ Find ECT Centers near you",expanded=True):
     st.write("Find veterinary centers offering electrochemotherapy (ECT) in the USA and Canada.")
     zip_code=st.text_input("ZIP / postal code",placeholder="e.g. 01095 or M5V 3L9",key="ect_zip")
     if st.button("Find nearest ECT centers",use_container_width=True,key="ect_find"):
         loc=zip_coords(zip_code.strip().replace(" ",""))
         if not loc:st.error("ZIP / postal code not found. Try a valid US ZIP or Canadian postal code.")
         else:
             centers=json.loads((Path(__file__).resolve().parents[1]/"data"/"ect_centers_usa_canada.json").read_text())["centers"]
             coords={("Toronto","ON"):(43.6532,-79.3832),("Brossard","QC"):(45.4501,-73.4658),("Auburn","AL"):(32.6099,-85.4808),("Laguna Hills","CA"):(33.6125,-117.7128),("Los Angeles","CA"):(34.0522,-118.2437),("San Francisco","CA"):(37.7749,-122.4194),("Boulder","CO"):(40.015,-105.2705),("Colorado Springs","CO"):(38.8339,-104.8214),("Lafayette","CO"):(39.9936,-105.0897),("Lakewood","CO"):(39.7047,-105.0814),("Boca Raton","FL"):(26.3683,-80.1289),("Coral Springs","FL"):(26.2712,-80.2706),("Gainesville","FL"):(29.6516,-82.3248),("Melbourne","FL"):(28.0836,-80.6081),("Marietta","GA"):(33.9526,-84.5499),("Savannah","GA"):(32.0809,-81.0912),("Buzzards Bay","MA"):(41.7454,-70.6181),("South Weymouth","MA"):(42.1751,-70.9495),("Walpole","MA"):(42.1418,-71.2495),("Rockville","MD"):(39.084,-77.1528),("Auburn Hills","MI"):(42.6875,-83.2455),("Bloomfield Hills","MI"):(42.5836,-83.2455),("Arden Hills","MN"):(45.0502,-93.1566),("Oakdale","MN"):(44.963,-92.9649),("Raleigh","NC"):(35.7796,-78.6382),("Stratham","NH"):(43.0231,-70.9137),("Eatontown","NJ"):(40.2962,-74.0509),("Woodbridge","NJ"):(40.5576,-74.2846),("Santa Fe","NM"):(35.687,-105.9378),("New York","NY"):(40.7128,-74.006),("Bend","OR"):(44.0582,-121.3153),("Milwaukie","OR"):(45.4462,-122.6393),("Tacoma","WA"):(47.2529,-122.4443),("Waukesha","WI"):(43.0117,-88.2315)}
             lat,lon,place,region=loc;ranked=[]
             for x in centers:
                 c=coords.get((x["city"],x["region"]))
                 if c:ranked.append((miles(lat,lon,*c),x))
             ranked.sort(key=lambda v:v[0]);st.success(f"Nearest listed ECT centers to {place}{', '+region if region else ''}")
             for dist,x in ranked[:8]:
                 with st.container(border=True):
                     st.subheader(x["center"]);st.write(f"{x['city']}, {x['region']} · approximately {dist:.0f} miles away");st.markdown(f"☎️ [{x['phone']}](tel:{x['phone'].replace('-', '')})");st.link_button("Center website",x["website"],use_container_width=True)
             st.caption("Distances are straight-line estimates, not driving distances. Confirm that ECT is currently available before travel.")
elif route=="🧪 Compassionate / Expanded Access":
 st.subheader("Compassionate / Expanded Access")
 st.write("Investigational anticancer treatment access outside ordinary trial enrollment. We list a program only when a current owner contact pathway can be verified.")
 with st.container(border=True):
     st.markdown("### UT Southwestern VROC — Compassionate-Use Protocol")
     st.write("**Dogs and cats · advanced non-resectable tumors · Dallas, Texas**")
     st.write("A current prospective, non-randomized compassionate-use protocol for pets with advanced non-resectable tumors. Treatment may use investigational therapy, chemotherapy, immunotherapy, and combination approaches selected through the VROC protocol.")
     st.write("**Access:** contact VROC for case review and eligibility. Enrollment is required for patients treated by the clinic; exact treatment, visits, risks and costs depend on the protocol and individual case.")
     st.markdown("✉️ [VROC@UTSouthwestern.edu](mailto:VROC@UTSouthwestern.edu)    ☎️ [214-645-6221](tel:2146456221)")
     st.link_button("Official VROC compassionate-use listing","https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html",use_container_width=True)
 st.caption("Compassionate / expanded access does not mean a treatment is proven or guaranteed to be available for an individual pet. Eligibility is determined by the treating program.")
else:
 with st.expander("How options qualify"):
     st.write("This section can include regulated, experimental, off-label, precision, or personalized anticancer treatments with a real current access pathway.")
 species=st.selectbox("1. Species",["Dog","Cat"])
 country=st.selectbox("2. Country / region",["USA","Canada","Europe"])
 country_options=[x for x in OPTIONS if x["species"]==species and country in x.get("countries",[])]
 available_cancers=sorted({c for x in country_options for c in x["cancers"]})
 cancer=st.selectbox("3. Cancer type",["Select cancer type"]+available_cancers)
 if cancer!="Select cancer type":
     cancer_matches=[x for x in country_options if cancer in x["cancers"]]
     situations=sorted({s for x in cancer_matches for s in x["situations"]})
     situation=st.selectbox("4. Clinical situation",["Show all relevant situations"]+situations)
     matches=cancer_matches if situation=="Show all relevant situations" else [x for x in cancer_matches if situation in x["situations"]]
     st.success(f"{len(matches)} additional option{'s' if len(matches)!=1 else ''} found to discuss with a veterinary oncologist.")
     for x in matches:
         with st.container(border=True):
             st.subheader(x["name"]); st.write(x["summary"])
             contacts=contact_line(x,country)
             if contacts: st.markdown(contacts)
             with st.expander("Evidence"):
                 st.markdown(f"**Evidence level:** {x['evidence_level']}"); st.write(x["evidence"]); st.link_button("Clinical evidence",x["url"],use_container_width=True)
             with st.expander("Access & sample"):
                 st.markdown(f"**Current access:** {x['access']}"); st.markdown(f"**Sample:** {x['sample']}"); st.markdown(f"**Travel:** {x['travel']}")
             with st.expander("Limitations"): st.write(x["limitations"])