from pathlib import Path

p = Path('pages/2_Additional_Oncology_Options.py')
s = p.read_text()
needle = 'OPTIONS = [\n'
record = '''    {"id":"vidium-searchlight-genomic-guidance","species":"Dog","countries":["USA","Canada","Europe"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Unclear or limited treatment options","Tumor tissue or FNA material available"],"name":"Vidium SearchLight DNA","summary":"Tumor genomic profiling of 120 cancer-related genes to identify diagnostic, prognostic and therapeutic biomarkers and potential mutation-matched drugs.","access":"Veterinarian-ordered genomic test. Vidium currently accepts international orders; treatment is selected and prescribed separately by the veterinary team.","evidence":"SearchLight DNA reports identify mutation-associated treatment options and can also flag therapies predicted to be ineffective or potentially harmful. Vidium provides targeted-drug monographs and complimentary veterinarian consultations for SearchLight DNA cases.","evidence_level":"Commercial targeted tumor sequencing + treatment guidance; strength of evidence varies by biomarker and drug","sample":"FNA, FFPE tissue, or fresh-frozen tumor sample.","travel":"No research-center travel is inherently required for testing; the sample is submitted by the veterinary team. Any recommended treatment is obtained separately.","url":"https://vidiumah.com/searchlight-dna/","provider_url":"https://vidiumah.com/","access_url":"https://vidiumah.com/searchlight-dna/","access_label":"SearchLight DNA information","contact_phone":"833-794-0318","limitations":"This is a genomic diagnostic and treatment-guidance service, not a treatment provider. Some treatment associations rely partly on human oncology or limited canine evidence, and a genomic match does not establish clinical benefit for an individual dog."},\n'''
if 'vidium-searchlight-genomic-guidance' not in s:
    s = s.replace(needle, needle + record, 1)
p.write_text(s)
