import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UPDATES = ROOT / 'data' / 'trial_updates.json'
BASE = ROOT / 'data' / 'trials_base.json'
STATS = ROOT / 'data' / 'catalog_stats.json'

V='2026-09-05'
def tr(id,title,center,state,species,cancers,url,notes,funding='Confirm current study-covered and owner-paid costs with the study team.',requires=None,excludes=None):
    return {'id':id,'title':title,'center':center,'country':'USA','state':state,'species':species,'cancers':cancers,'status':'Actively recruiting — confirmed on the institution’s current clinical-trials page','url':url,'contacts':'See official study page for current study contact and prescreening instructions','funding':funding,'requires':requires or {'active_treatment_target':True},'excludes':excludes or {},'notes':notes,'verified':V,'study_type':'treatment','available_for_matching':True,'status_confidence':'confirmed_current','owner_prescreen_required':True}

R=[
tr('umn-sarcoma-trike-rt','TriKE immunotherapy plus hypofractionated radiation for canine sarcoma','University of Minnesota Veterinary Medical Center','Minnesota','Dog',['Soft tissue sarcoma','Other sarcoma'],'https://vetmed.umn.edu/departments/centers-and-programs/clinical-investigation-center/current-clinical-trials/trike-new','Novel TriKE immunotherapy is given with hypofractionated radiation. Confirmed sarcoma at least 2 cm; prior chemotherapy/radiation may be allowed after washout; prior immunotherapy excluded.','Once enrolled, the study covers study blood/urine tests, imaging, radiation planning and treatment, TriKE immunotherapy and follow-up exams.',{'confirmed':True,'active_treatment_target':True,'min_tumor_cm':2,'min_weight_kg':7},{'prior_immunotherapy':True}),
tr('umn-oral-melanoma-aav-vaccine','AAV cancer vaccine for canine oral malignant melanoma','University of Minnesota Veterinary Medical Center','Minnesota','Dog',['Oral melanoma'],'https://vetmed.umn.edu/departments/centers-and-programs/clinical-investigation-center/current-clinical-trials/new-vaccine','Adeno-associated-virus cancer vaccine integrated with local therapy. Biopsy-confirmed oral malignant melanoma; no prior ONCEPT vaccine.','Study-associated visits are covered and qualifying dogs receive a $4,000 credit toward surgery or radiation performed at the University of Minnesota.',{'confirmed':True,'active_treatment_target':True,'min_weight_kg':5},{'prior_melanoma_vaccine':True}),
tr('umn-feline-mammary-olaparib-meloxicam','Olaparib plus meloxicam for feline mammary carcinoma','University of Minnesota Veterinary Medical Center','Minnesota','Cat',['Feline mammary carcinoma','Mammary carcinoma'],'https://vetmed.umn.edu/departments/centers-and-programs/clinical-investigation-center/current-clinical-trials/olaparib','Pilot treatment study combining PARP inhibition with meloxicam for measurable feline mammary carcinoma.','Screening, study medications, required visits/labs/imaging are covered; $2,000 surgical credit and up to $1,000 for study-medication complications.',{'confirmed':True,'active_treatment_target':True,'min_tumor_cm':1},{}),
tr('tufts-z007-solid-tumors','TLR agonist Z-007 for canine solid tumors','Tufts Cummings School of Veterinary Medicine','Massachusetts','Dog',['Other solid tumor','Soft tissue sarcoma','Other sarcoma','Melanoma — other','Squamous cell carcinoma','Mammary carcinoma'],'https://vet.tufts.edu/clinical-trials/evaluation-tlr-agonist-z-007-dogs-cancer','Weekly intratumoral or IV Z-007 immunotherapy for measurable solid tumors; prior surgery, chemotherapy or radiation may be allowed; metastasis is not automatically exclusionary.','All cancer-treatment costs associated with Z-007 are covered through Day 63, including treatment of study-related adverse effects.',{'active_treatment_target':True,'min_tumor_cm':2,'max_tumor_cm':7,'min_weight_kg':7},{'prior_immunotherapy':True}),
tr('tufts-sts-fap-car-t','FAP CAR-T cell therapy for canine soft tissue sarcoma','Tufts Cummings School of Veterinary Medicine','Massachusetts','Dog',['Soft tissue sarcoma'],'https://vet.tufts.edu/clinical-trials/treatment-canine-soft-tissue-sarcoma-fap-car-t-cells','Recruiting interventional cellular-immunotherapy study targeting fibroblast activation protein in canine soft tissue sarcoma.'),
tr('tufts-met-osa-vaccine-tme','Tumor-microenvironment modification plus allogeneic vaccine for metastatic canine osteosarcoma','Tufts Cummings School of Veterinary Medicine','Massachusetts','Dog',['Osteosarcoma'],'https://vet.tufts.edu/clinical-trials/treatment-canine-metastatic-osteosarcoma-combined-tumor-microenvironment-modification-and-allogeneic-vaccination','For dogs with pulmonary metastatic osteosarcoma after amputation and chemotherapy; combines toceranib, losartan and ladarixin with a tumor vaccine.','Study provides the oral drugs and tumor vaccines and covers nearly all study costs; limited specified bloodwork/side-effect medications remain owner-paid.',{'confirmed':True,'active_treatment_target':True,'primary_removed':True,'measurable_lung_metastases':True},{}),
tr('upenn-extremity-sarcoma-proton-flash','Proton FLASH radiation for canine extremity soft tissue sarcoma','Penn Vet Ryan Hospital','Pennsylvania','Dog',['Soft tissue sarcoma'],'https://www.vet.upenn.edu/clinical-trial/evaluation-of-proton-flash-rt-in-naturally-occurring-canine-extremity-sarcoma/','Investigational ultra-high-dose-rate proton FLASH radiation for extremity soft tissue sarcomas where surgery is not feasible or has been declined.'),
tr('upenn-met-osa-car-inkt','CAR-iNKT cell therapy for canine metastatic osteosarcoma','Penn Vet Ryan Hospital','Pennsylvania','Dog',['Osteosarcoma'],'https://www.vet.upenn.edu/clinical-trial/cell-therapy-for-metastatic-osteosarcoma/','Interventional donor-derived CAR invariant natural killer T-cell therapy for osteosarcoma metastatic to the lungs.',requires={'confirmed':True,'active_treatment_target':True,'measurable_lung_metastases':True}),
tr('upenn-prostate-psma-theranostic','PSMA-targeted theranostic therapy for canine prostate cancer','Penn Vet Ryan Hospital','Pennsylvania','Dog',['Prostate cancer'],'https://www.vet.upenn.edu/clinical-trial/psma-ligand-based-theranostic-to-treat-canine-prostatic-cancer/','Investigational PSMA-MMAE-Pc413 targeted agent combined with laser treatment for local and metastatic canine prostate cancer.'),
tr('osu-sts-mic-nk','Anti-MIC antibody plus adoptive NK-cell therapy for canine soft tissue sarcoma','The Ohio State University Veterinary Medical Center','Ohio','Dog',['Soft tissue sarcoma'],'https://vmc.vet.osu.edu/clinical-trials/targeting-mic-augment-adoptive-nk-therapy-using-canine-soft-tissue-sarcoma-model','Localized confirmed STS treated with anti-MIC antibody and expanded natural-killer-cell infusion.','All trial-related procedures are covered and $700 compensation is provided upon trial completion.',{'confirmed':True,'active_treatment_target':True},{'prior_local_radiation':True}),
tr('osu-oral-melanoma-r3lcmv','r3LCMV immunotherapy for canine oral melanoma','The Ohio State University Veterinary Medical Center','Ohio','Dog',['Oral melanoma'],'https://vmc.vet.osu.edu/clinical-trials-office/current-trials','Current OSU oncology treatment trial using r3LCMV-based immunotherapy for canine mucosal/oral melanoma.'),
tr('illinois-oral-melanoma-il12-il15','IL-12/IL-15 treatment for canine oral melanoma','University of Illinois Veterinary Teaching Hospital','Illinois','Dog',['Oral melanoma'],'https://vetmed.illinois.edu/research/clinical-trials/','Funded current treatment study for canine oral melanoma using IL-12/IL-15 immunotherapy.'),
tr('illinois-osa-pulm-met-treatment','Treatment study for canine appendicular osteosarcoma with pulmonary metastasis','University of Illinois Veterinary Teaching Hospital','Illinois','Dog',['Osteosarcoma'],'https://vetmed.illinois.edu/research/clinical-trials/','Funded current treatment study for dogs with appendicular osteosarcoma and pulmonary metastasis.',requires={'confirmed':True,'active_treatment_target':True,'measurable_lung_metastases':True}),
tr('illinois-osa-radiation','Radiation treatment study for canine appendicular osteosarcoma','University of Illinois Veterinary Teaching Hospital','Illinois','Dog',['Osteosarcoma'],'https://vetmed.illinois.edu/research/clinical-trials/','Funded current radiation-treatment study for canine appendicular osteosarcoma.'),
tr('illinois-sts-surgery','Surgical treatment study for resectable canine soft tissue sarcoma','University of Illinois Veterinary Teaching Hospital','Illinois','Dog',['Soft tissue sarcoma'],'https://vetmed.illinois.edu/research/clinical-trials/','Funded current interventional study for canine soft tissue sarcoma amenable to surgical removal.'),
tr('illinois-sts-treatment','Treatment study for canine soft tissue sarcoma','University of Illinois Veterinary Teaching Hospital','Illinois','Dog',['Soft tissue sarcoma'],'https://vetmed.illinois.edu/research/clinical-trials/','Funded current treatment study for canine soft tissue sarcoma.'),
tr('illinois-ucc-gilvetmab-epacadostat','Gilvetmab plus epacadostat for canine bladder urothelial carcinoma','University of Illinois Veterinary Teaching Hospital','Illinois','Dog',['Urothelial / transitional cell carcinoma','Urothelial carcinoma'],'https://vetmed.illinois.edu/research/clinical-trials/','Funded current treatment study combining canine anti-PD-1 antibody gilvetmab with IDO1 inhibitor epacadostat for bladder urothelial carcinoma.'),
tr('auburn-palbociclib-solid-cancers','Palbociclib for selected progressive canine solid tumors','Auburn University College of Veterinary Medicine','Alabama','Dog',['Mammary carcinoma','Squamous cell carcinoma','Histiocytic sarcoma','Anal sac adenocarcinoma (AGASACA)','Melanoma — other'],'https://www.vetmed.auburn.edu/research/clinical-trials/mammary-carcinoma-squamous-cell-carcinoma-agasaca-and-melanoma-clinical-trial/','Dose-finding oral palbociclib treatment study for measurable progressive mammary carcinoma, SCC, histiocytic sarcoma, AGASACA or melanoma; prior cancer treatment is allowed if disease is progressing.','After owner-paid initial exam/screening, up to two months of trial treatment including biopsy, rechecks, bloodwork and chemotherapy are funded.',{'confirmed':True,'active_treatment_target':True,'measurable':True},{}),
tr('vtech-thyroid-histotripsy','Histotripsy for canine thyroid tumors','Virginia Tech Animal Cancer Care and Research Center','Virginia','Dog',['Thyroid tumor / carcinoma','Thyroid carcinoma'],'https://research.vetmed.vt.edu/clinical-trials/current-studies.html','Recruiting non-invasive histotripsy treatment study designed to ablate canine thyroid tumors without incision or radiation.'),
tr('lsu-scc-intratumoral-chemo','Intratumoral chemotherapy for non-metastatic canine squamous cell carcinoma','LSU Veterinary Teaching Hospital','Louisiana','Dog',['Squamous cell carcinoma','Squamous cell carcinoma — other'],'https://www.lsu.edu/vetmed/veterinary_hospital/clinical_trials.php','Direct intratumoral chemotherapy for confirmed non-metastatic SCC; lesion must be greater than 1 cm; no prior radiation, immunotherapy or chemotherapy.','Treatment is free and the study provides a $400 gift card upon completion.',{'confirmed':True,'active_treatment_target':True,'min_tumor_cm':1,'min_weight_kg':5,'no_metastasis':True},{'prior_chemo':True,'prior_immunotherapy':True,'prior_local_radiation':True}),
tr('ucd-glioma-care','CARE trial: experimental drug plus radiation for canine glioma','UC Davis Weill School of Veterinary Medicine','California','Dog',['Brain tumor / glioma'],'https://behavior.vetmed.ucdavis.edu/index.php/news/clinical-trials-dogs-glioma-brain-tumors','Recruiting CARE treatment trial for dogs with diagnosed or MRI-suspected glioma, combining an experimental drug with radiation therapy.'),
tr('ucd-glioma-prism-radiation','PRISM radiation pathway for canine glioma','UC Davis Weill School of Veterinary Medicine','California','Dog',['Brain tumor / glioma'],'https://behavior.vetmed.ucdavis.edu/index.php/news/clinical-trials-dogs-glioma-brain-tumors','Recruiting PRISM study includes a radiation-therapy treatment pathway for dogs with diagnosed or suspected glioma. Only the therapeutic radiation pathway is represented in matching.'),
tr('utsw-glioma-car-neutrophil-rt','CAR-neutrophils plus radiation for canine glioma','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Brain tumor / glioma'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Current VROC treatment trial combining CAR-neutrophils with radiation for canine glioma.'),
tr('utsw-glioma-ferumoxytol-rt','Ferumoxytol plus radiation for canine glioma','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Brain tumor / glioma'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Current VROC treatment trial combining ferumoxytol with radiation therapy for canine glioma.'),
tr('utsw-solid-cpmv','Intratumoral cowpea mosaic virus immunotherapy for canine solid tumors','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Other solid tumor','Soft tissue sarcoma','Other sarcoma','Melanoma — other'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Weekly intratumoral CPMV immunotherapy for naturally occurring canine solid tumors.'),
tr('utsw-solid-rt-histotripsy','Radiation plus histotripsy for canine/feline solid tumors','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Soft tissue sarcoma','Other solid tumor'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Current VROC treatment study combining radiation and high-intensity focused ultrasound histotripsy for naturally occurring tumors.'),
tr('utsw-melanoma-crtnp-hifu-pdl1','CRT-nanoparticle plus HIFU immunotherapy with or without anti-PD-L1 for canine melanoma','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Oral melanoma','Melanoma — other'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Calreticulin-nanoparticle immunotherapy combined with HIFU, with or without anti-PD-L1, for advanced canine melanoma.'),
tr('utsw-melanoma-carboplatin-hifu','Intratumoral versus IV carboplatin with or without HIFU for canine melanoma','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Oral melanoma','Melanoma — other'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Current VROC melanoma treatment trial comparing carboplatin delivery routes with or without HIFU enhancement.'),
tr('utsw-advanced-tumor-compassionate','Compassionate-use investigational therapy for advanced non-resectable tumors','UT Southwestern Veterinary Research and Oncology Clinic','Texas','Dog',['Cancer — any type','Other solid tumor'],'https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html','Prospective compassionate-use protocol for advanced non-resectable tumors using investigational therapy, chemotherapy, immunotherapy and combination approaches.'),
]

doc=json.loads(UPDATES.read_text(encoding='utf-8'))
by={x['id']:x for x in doc.get('upsert',[])}
for x in R: by[x['id']]=x
doc['upsert']=list(by.values())
UPDATES.write_text(json.dumps(doc,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

base=json.loads(BASE.read_text(encoding='utf-8'))
eff={x['id']:x for x in base}
for x in doc.get('delete',[]): eff.pop(x,None)
for x in doc.get('upsert',[]):
    if x['id'] in eff: eff[x['id']].update(x)
    else: eff[x['id']]=x
vals=list(eff.values())
match=[x for x in vals if x.get('available_for_matching') and x.get('study_type')=='treatment' and x.get('status_confidence') in {'current','confirmed_current'}]
stats={'generated':V,'effective_catalog_records':len(vals),'current_treatment_opportunities':len(match),'dogs':sum(x.get('species')=='Dog' for x in match),'cats':sum(x.get('species')=='Cat' for x in match),'usa':sum(x.get('country')=='USA' for x in match),'canada':sum(x.get('country')=='Canada' for x in match),'europe_uk':sum(x.get('country') not in {'USA','Canada'} for x in match),'new_primary_source_records_in_this_audit':len(R)}
STATS.write_text(json.dumps(stats,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(stats)
