from pathlib import Path
p=Path('pages/2_Additional_Oncology_Options.py')
s=p.read_text()
marker='OPTIONS = [\n'
assert marker in s
additions='''    {"id":"osa-elias-eci","species":"Dog","countries":["USA"],"cancers":["Osteosarcoma"],"situations":["After amputation / local control","Adjuvant systemic treatment planning"],"name":"ELIAS Cancer Immunotherapy (ECI)","summary":"USDA-approved autologous vaccine-enhanced adoptive T-cell therapy for canine osteosarcoma.","access":"USA — available through authorized ECI treatment centers; ELIAS maintains a current nationwide provider directory.","evidence":"Prospective canine clinical evidence supports ECI after amputation; a 2026 ASCENT update evaluated carboplatin followed by ECI against matched historical controls.","evidence_level":"USDA-approved autologous prescription product + prospective canine clinical evidence","sample":"Tumor tissue is required; coordinate with an authorized ECI center before surgery/tissue handling when possible.","travel":"Available through authorized centers across the USA; repeated visits are required.","url":"https://eliasanimalhealth.com/ascent-study-summary-18-month-update/","provider_url":"https://eliasanimalhealth.com/","access_url":"https://eliasanimalhealth.com/available-locations/","access_label":"Find an ECI provider","contact_note":"Contact an authorized ECI center before or around amputation so tissue collection and treatment sequencing can be coordinated.","limitations":"Specialized multimodal treatment, not a substitute for local control. The 2026 ASCENT update used matched historical rather than randomized concurrent controls."},
    {"id":"mct-stelfonta","species":"Dog","countries":["USA","Europe"],"cancers":["Mast cell tumor"],"situations":["Non-metastatic injectable mast cell tumor","Surgery unsuitable / local treatment alternative"],"name":"STELFONTA (tigilanol tiglate)","summary":"Intratumoral anticancer treatment for eligible non-metastatic canine mast cell tumors.","access":"USA — FDA-approved with a current Virbac veterinarian locator. Europe — centrally authorized veterinary medicine for eligible non-metastatic canine mast cell tumors.","evidence":"Regulatory approval is supported by prospective efficacy and safety data.","evidence_level":"FDA-approved / EU-authorized veterinary anticancer drug","sample":"Confirmed diagnosis and staging; no manufacturing sample required.","travel":"Administered intratumorally by a veterinarian; availability depends on clinic and country.","url":"https://www.ema.europa.eu/en/medicines/veterinary/EPAR/stelfonta","provider_url":"https://vet-us.virbac.com/stelfonta","access_url":"https://us.virbac.com/stelfonta-find-a-vet","access_label":"Find a STELFONTA veterinarian","contact_phone":"800-338-3659","contact_note":"Ask whether tumor location, volume and metastatic status meet the indication.","limitations":"Local therapy only; not systemically active or for metastatic disease. Wound formation is expected and mast-cell degranulation can cause severe reactions."},
    {"id":"lymphoma-tanovea","species":"Dog","countries":["USA"],"cancers":["Lymphoma"],"situations":["Lymphoma treatment planning","Relapsed / rescue treatment"],"name":"TANOVEA (rabacfosadine)","summary":"FDA fully approved intravenous antineoplastic drug specifically indicated for canine lymphoma.","access":"USA — prescription oncology treatment administered as a 30-minute IV infusion, generally every 3 weeks for up to five treatments.","evidence":"FDA approval and prospective canine lymphoma studies support antitumor activity.","evidence_level":"FDA fully approved veterinary anticancer drug","sample":"No manufacturing sample required; lymphoma diagnosis and clinical assessment are required.","travel":"Given in a veterinary clinic as an IV infusion.","url":"https://my.elanco.com/us/tanovea","provider_url":"https://my.elanco.com/us/tanovea","access_url":"https://my.elanco.com/us/tanovea","access_label":"TANOVEA information","contact_note":"Discuss with a veterinary oncologist, especially for rescue therapy or an alternative lymphoma regimen.","limitations":"Can cause GI toxicity, neutropenia, dermatologic adverse effects and potentially life-threatening pulmonary fibrosis."},
    {"id":"lymphoma-laverdia","species":"Dog","countries":["USA"],"cancers":["Lymphoma"],"situations":["Lymphoma treatment planning","Oral / at-home treatment option"],"name":"LAVERDIA (verdinexor)","summary":"Oral selective inhibitor of nuclear export for canine lymphoma, administered at home under veterinary prescription.","access":"USA — FDA fully approved for canine lymphoma; full approval replaced earlier conditional approval in 2026.","evidence":"FDA granted full approval after effectiveness data required to convert the earlier conditional approval were generated.","evidence_level":"FDA fully approved veterinary anticancer drug","sample":"No manufacturing sample required; confirmed diagnosis and monitoring are required.","travel":"Oral at-home administration; monitoring visits remain necessary.","url":"https://www.fda.gov/animal-veterinary/cvm-updates/fda-grants-full-approval-first-oral-treatment-lymphoma-dogs","provider_url":"https://www.anivive.com/","access_url":"https://www.fda.gov/animal-veterinary/cvm-updates/fda-grants-full-approval-first-oral-treatment-lymphoma-dogs","access_label":"FDA approval information","contact_note":"Discuss fit with the treating veterinarian/oncologist and review cytotoxic-handling instructions before home dosing.","limitations":"Response rates may be lower than standard multidrug chemotherapy in many lymphomas. Cytotoxic handling precautions and adverse-effect monitoring apply."},
    {"id":"oral-melanoma-oncept","species":"Dog","countries":["USA"],"cancers":["Oral melanoma"],"situations":["Stage II–III after local disease control","Adjuvant immunotherapy"],"name":"ONCEPT Canine Melanoma Vaccine, DNA","summary":"USDA-licensed DNA immunotherapy used as an adjunct after local control of stage II or III canine oral melanoma.","access":"USA — supplied to approved veterinary practices; manufacturer has a current purchase-application pathway.","evidence":"Licensed indication is to aid in extending survival after local disease control. Published clinical evidence exists, while later literature has raised uncertainty about magnitude of benefit.","evidence_level":"USDA-licensed veterinary cancer immunotherapy + mixed clinical evidence","sample":"No personalized manufacturing sample required; local disease control and staging are prerequisites for labeled use.","travel":"Administered through practices able to obtain and deliver ONCEPT using the VET JET system.","url":"https://animalhealth.boehringer-ingelheim.com/pets/canine/products/therapeutics/oncept","provider_url":"https://animalhealth.boehringer-ingelheim.com/pets/canine/products/therapeutics/oncept","access_url":"https://animalhealth.boehringer-ingelheim.com/pets/canine/products/therapeutics/oncept","access_label":"ONCEPT product & access","contact_note":"After local control, ask the oncologist whether ONCEPT is appropriate and whether their practice can obtain/administer it.","limitations":"Adjunctive treatment, not local tumor control. Licensed status does not prove benefit for every patient."},
    {"id":"ect-usa-europe","species":"Dog","countries":["USA","Europe"],"cancers":["Mast cell tumor","Soft tissue sarcoma","Squamous cell carcinoma","Oral melanoma","Solid tumor — other"],"situations":["Incomplete surgical margins / scar treatment","Superficial or localized tumor","Surgery difficult or not feasible"],"name":"Veterinary electrochemotherapy (ECT)","summary":"Local treatment combining chemotherapy, commonly bleomycin, with brief electric pulses to increase drug uptake in tumor tissue or a surgical bed.","access":"USA and Europe — available at selected veterinary oncology/referral centers; access is center-specific.","evidence":"Multiple canine and feline studies and a 2024 Veterinary and Comparative Oncology review support ECT for selected tumors; current referral services describe use for incomplete excision and gross superficial/localized tumors.","evidence_level":"Published veterinary clinical evidence + current specialty-center access","sample":"Definitive diagnosis and staging are generally required; no manufacturing sample required.","travel":"Requires a center with an electroporator and trained oncology team; short anesthesia or deep sedation is commonly used.","url":"https://pubmed.ncbi.nlm.nih.gov/38866596/","provider_url":"https://www.rvc.ac.uk/small-animal-vet/specialist-referrals/clinical-services/veterinary-oncology/electrochemotherapy-for-small-animals","access_url":"https://www.rvc.ac.uk/small-animal-vet/specialist-referrals/clinical-services/veterinary-oncology/electrochemotherapy-for-small-animals","access_label":"Example specialist ECT service","contact_note":"Ask an oncologist whether ECT is appropriate and identify the nearest center currently performing it.","limitations":"Local treatment, not systemic metastasis treatment. Suitability and evidence vary by tumor type, size, location and treatment setting."},
'''
ids=['osa-elias-eci','mct-stelfonta','lymphoma-tanovea','lymphoma-laverdia','oral-melanoma-oncept','ect-usa-europe']
for i in ids:
    if f'"id":"{i}"' in s:
        raise SystemExit(f'already present: {i}')
s=s.replace(marker,marker+additions,1)
s=s.replace('Last review: September 6, 2026.','Last review: September 6, 2026.')
p.write_text(s)
