from pathlib import Path

p=Path('pages/2_Additional_Oncology_Options.py')
s=p.read_text()
old='''    {"id":"hsa-fidocure-genomic-guidance","species":"Dog","countries":["USA"],"cancers":["Hemangiosarcoma"],"situations":["Splenic hemangiosarcoma"],"name":"FidoCure genomic guidance","summary":"Tumor genomic profiling to guide targeted therapy after splenic hemangiosarcoma diagnosis.","access":"USA — ordered and managed through the treating veterinarian/oncologist; FFPE tumor tissue can be used.","evidence":"Retrospective real-world comparative evidence.","evidence_level":"Comparative real-world clinical evidence","sample":"FFPE tumor tissue / pathology material","travel":"No research-center travel inherently required","url":"https://www.nature.com/articles/s41598-025-89862-9","provider_url":"https://fidocure.com/","access_url":"https://fidocure.com/pet-parents/","access_label":"Start with FidoCure","contact_email":"support@fidocure.com","contact_phone":"855-701-8047","limitations":"Retrospective observational data."},'''
new='''    {"id":"fidocure-genomic-guidance","species":"Dog","countries":["USA"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Few standard treatment options remain","Tumor tissue available"],"name":"FidoCure genomic guidance","summary":"Tumor genomic profiling with precision-treatment guidance for dogs with cancer.","access":"USA — ordered and managed through the treating veterinarian/oncologist; treatment and medications are separate from testing.","evidence":"FidoCure provides tumor genomic profiling and treatment guidance across canine cancers. Cancer-specific clinical evidence varies; published real-world comparative evidence is available for splenic hemangiosarcoma.","evidence_level":"Commercial precision-oncology service + cancer-specific real-world clinical evidence","sample":"Tumor pathology material; confirm current specimen requirements with FidoCure before submission.","travel":"No research-center travel inherently required.","url":"https://www.nature.com/articles/s41598-025-89862-9","provider_url":"https://fidocure.com/","access_url":"https://fidocure.com/pet-parents/","access_label":"Start with FidoCure","contact_email":"support@fidocure.com","contact_phone":"855-701-8047","limitations":"This is genomic testing and treatment guidance, not a guarantee that a matched therapy will be effective. The strongest published outcome evidence is cancer-specific and should not be generalized to every tumor type."},
    {"id":"vidium-searchlight-dna","species":"Dog","countries":["USA"],"cancers":["Cancer — any type"],"situations":["Tumor genomic profiling / treatment planning","Few standard treatment options remain","Tumor tissue or FNA material available"],"name":"Vidium SearchLight DNA","summary":"Tumor genomic profiling of 120 cancer-related genes with clinical interpretation and potential matched-drug guidance.","access":"USA — veterinarian-directed commercial genomic testing. Treatment and medications are obtained separately.","evidence":"SearchLight DNA reports genomic alterations with diagnostic, prognostic, and potential therapeutic interpretation. Published clinical-utility data exist, but actionability and canine-specific treatment evidence vary by finding.","evidence_level":"Commercial genomic profiling + published veterinary clinical-utility evidence","sample":"FFPE tissue, FNA/cytology material, or fresh/frozen tumor material may be accepted; confirm current submission requirements with Vidium.","travel":"No research-center travel inherently required for testing; the treating veterinarian coordinates submission and any resulting treatment.","url":"https://pubmed.ncbi.nlm.nih.gov/36862546/","provider_url":"https://vidiumah.com/","access_url":"https://vidiumah.com/searchlight-dna/","access_label":"SearchLight DNA information","limitations":"This is a genomic testing and treatment-guidance service, not a treatment provider. A reported drug match does not establish efficacy for an individual dog, and canine-specific evidence varies by alteration and drug."},'''
if old not in s:
    raise SystemExit('expected FidoCure record not found')
s=s.replace(old,new,1)
p.write_text(s)
