from pathlib import Path
p=Path('pages/2_Additional_Oncology_Options.py')
s=p.read_text(encoding='utf-8')
old='route=st.radio("Choose an option",["⚡ Electrochemotherapy (ECT)","🧬 Advanced / Novel Treatments","🧪 Compassionate / Expanded Access"],horizontal=True,label_visibility="collapsed",key="treatment_option_route")'
new='''# Calm, card-like route buttons rather than questionnaire-style radio controls.\nst.markdown("""<style>\ndiv[data-testid="stHorizontalBlock"] div[data-testid="stButton"] button {background:#f2f6f8;border:1px solid #d7e0e6;color:#334155;border-radius:12px;min-height:3.25rem;font-weight:500;}\ndiv[data-testid="stHorizontalBlock"] div[data-testid="stButton"] button:hover {border-color:#9fb6c5;background:#eaf1f5;color:#243746;}\n</style>""",unsafe_allow_html=True)\nif "treatment_option_route" not in st.session_state: st.session_state.treatment_option_route="⚡ Electrochemotherapy (ECT)"\nc1,c2,c3=st.columns(3)\nwith c1:\n if st.button("⚡ Electrochemotherapy (ECT)",use_container_width=True,key="route_ect"): st.session_state.treatment_option_route="⚡ Electrochemotherapy (ECT)"\nwith c2:\n if st.button("🧬 Advanced / Novel Treatments",use_container_width=True,key="route_advanced"): st.session_state.treatment_option_route="🧬 Advanced / Novel Treatments"\nwith c3:\n if st.button("🧪 Compassionate / Expanded Access",use_container_width=True,key="route_compassionate"): st.session_state.treatment_option_route="🧪 Compassionate / Expanded Access"\nroute=st.session_state.treatment_option_route'''
if old not in s: raise SystemExit('route radio not found')
s=s.replace(old,new)
old2='''elif route=="🧪 Compassionate / Expanded Access":\n st.subheader("Compassionate / Expanded Access")\n st.write("Investigational anticancer treatments that may be available outside a conventional recruiting clinical trial. Availability is verified program by program; contact and eligibility details are shown only when there is a real current access pathway.")\n st.info("Verified compassionate and special-access programs are being added here separately from clinical trials so they are not confused with ordinary trial enrollment.")'''
new2='''elif route=="🧪 Compassionate / Expanded Access":\n st.subheader("Compassionate / Expanded Access")\n st.write("Investigational anticancer treatment access outside ordinary trial enrollment. We list a program only when a current owner contact pathway can be verified.")\n with st.container(border=True):\n     st.markdown("### UT Southwestern VROC — Compassionate-Use Protocol")\n     st.write("**Dogs and cats · advanced non-resectable tumors · Dallas, Texas**")\n     st.write("A current prospective, non-randomized compassionate-use protocol for pets with advanced non-resectable tumors. Treatment may use investigational therapy, chemotherapy, immunotherapy, and combination approaches selected through the VROC protocol.")\n     st.write("**Access:** contact VROC for case review and eligibility. Enrollment is required for patients treated by the clinic; exact treatment, visits, risks and costs depend on the protocol and individual case.")\n     st.markdown("✉️ [VROC@UTSouthwestern.edu](mailto:VROC@UTSouthwestern.edu)    ☎️ [214-645-6221](tel:2146456221)")\n     st.link_button("Official VROC compassionate-use listing","https://www.utsouthwestern.edu/departments/radiation-oncology/veterinary-research-oncology-clinic/clinical-trials.html",use_container_width=True)\n st.caption("Compassionate / expanded access does not mean a treatment is proven or guaranteed to be available for an individual pet. Eligibility is determined by the treating program.")'''
if old2 not in s: raise SystemExit('compassionate placeholder not found')
s=s.replace(old2,new2)
p.write_text(s,encoding='utf-8')
print('refined buttons and compassionate access')
